"""Prepare BLE builds for pioarduino's SDK compilation pass."""

# AI: below section was generated by an AI
import re
import hashlib
import json
from pathlib import Path

Import("env")

# SDK options are maintained in the profiles. Kconfig otherwise gives a stale
# generated sdkconfig precedence over changed defaults on a later SDK rebuild.
sdk_options = env.GetProjectOption("custom_sdkconfig", "")
if sdk_options:
    # pioarduino's SDK cache key omits flash mode and component selection.
    # Include them so a different target cannot reuse incompatible headers.
    inputs = {name: env.GetProjectOption(name, "") for name in (
        "board", "board_build.flash_mode", "board_build.f_flash",
        "board_build.arduino.memory_type", "board_upload.flash_size",
        "custom_component_remove",
    )}
    signature = hashlib.sha256(json.dumps(inputs, sort_keys=True).encode()).hexdigest()
    sdk_options += "\n# WLED SDK inputs: " + signature
    env.GetProjectConfig().set("env:" + env["PIOENV"], "custom_sdkconfig", sdk_options)
    generated_config = Path(env["PROJECT_DIR"]) / ("sdkconfig." + env["PIOENV"])
    generated_config.unlink(missing_ok=True)

# HybridCompile clears build_unflags while compiling IDF components. Resolve
# the release-name override before that pass so its -Werror components see
# exactly one definition. Keep every other inherited compiler flag intact.
flags = env.GetProjectOption("build_flags")
release_name = re.compile(r"(?<!\S)-D\s*WLED_RELEASE_NAME=\S+")
names = release_name.findall(" ".join(flags))
if names:
    flags = [release_name.sub("", flag).strip() for flag in flags]
    flags = [flag for flag in flags if flag] + [names[-1]]
    env.GetProjectConfig().set("env:" + env["PIOENV"], "build_flags", flags)
    env.Replace(BUILD_FLAGS=flags)
# AI: end
