#pragma once
#include <stddef.h>
#include <stdint.h>

// AI: below section was generated by an AI
// Keep the previous file intact until every staged write has completed. The
// writer must close its handles and return the expected final length. A failed
// copy, mutation, verification or rename only removes the staging file.
template <class Filesystem, class Writer>
bool replaceFileTransactionally(Filesystem& fs, const char* path, const char* staged, Writer writer) {
  size_t copied = 0;
  auto source = fs.open(path, "r");
  if (!source && fs.exists(path)) return false;
  auto output = fs.open(staged, "w");
  if (!output) { source.close(); return false; }

  bool complete = true;
  const size_t originalSize = source ? source.size() : 0;
  uint8_t buffer[256];
  while (copied < originalSize) {
    const size_t remaining = originalSize - copied;
    const size_t amount = remaining < sizeof(buffer) ? remaining : sizeof(buffer);
    const size_t count = source.read(buffer, amount);
    if (count != amount || output.write(buffer, count) != count) { complete = false; break; }
    copied += count;
  }
  output.flush();
  complete = complete && output.size() == originalSize;
  source.close();
  output.close();

  if (complete) {
    auto verifyCopy = fs.open(staged, "r");
    complete = verifyCopy && verifyCopy.size() == originalSize;
    verifyCopy.close();
  }

  size_t expected = 0;
  if (complete) complete = writer(staged, expected);
  if (complete) {
    auto verify = fs.open(staged, "r");
    complete = verify && verify.size() == expected;
    verify.close();
  }
  if (complete) complete = fs.rename(staged, path);
  if (!complete) fs.remove(staged);
  return complete;
}
// AI: end
