#pragma once

#include <stdint.h>

// AI: below section was generated by an AI
// Generations advance after an operation completes, including a failed write.
// A busy JSON lock leaves the operation pending and does not advance its counter.
// Read the result only after observing a new generation, never as an acceptance
// acknowledgement for a command that has merely queued a save.
uint32_t configWriteGeneration();
bool configWriteSucceeded();
uint32_t presetWriteGeneration();
bool presetWriteSucceeded();
// AI: end
