#pragma once

#include <Arduino.h>

// AI: below section was generated by an AI
// Ordered form access shared by the HTTP and encrypted Bluetooth adapters.
// Duplicate keys are significant for usermod type descriptors and arrays.
class WLEDSettingsForm {
public:
  virtual ~WLEDSettingsForm() = default;
  virtual String arg(const String& name) const = 0;
  virtual String arg(size_t index) const = 0;
  virtual String argName(size_t index) const = 0;
  virtual size_t args() const = 0;
  virtual bool hasArg(const String& name) const = 0;
};

enum class SettingsFormResult { Applied, Busy, Invalid, Reset, StorageFailure };

// Callers authenticate their own session before invoking this function. The
// mutation logic deliberately does not borrow the HTTP global PIN-unlock state.
SettingsFormResult applySettingsForm(WLEDSettingsForm& form, byte subPage);
// AI: end
