#!/usr/bin/env python3
"""Functional WLED API scenarios over BLE, with independent HTTP verification."""
# AI: below section was generated by an AI
import asyncio
import copy
import json
import sys

from hil_runner import CoverageMissing, HilRunner, HttpOracle, check, mac_identity
from hil_runner import parse_args as base_parse_args


# json.cpp deserializeSegment/serializeSegment and FX_fcn.cpp setMode define these
# fields. fxdef:false prevents effect defaults from altering mapping/custom controls.
SEGMENT_FIELDS = ("on", "bri", "col", "fx", "sx", "ix", "pal", "sel", "frz")
INVARIANT_FIELDS = ("start", "stop", "len", "startY", "stopY", "grp", "spc", "of", "n",
                    "m12", "si", "rev", "mi", "rY", "mY", "tp", "cct", "set",
                    "c1", "c2", "c3", "o1", "o2", "o3", "bm", "lc")
SCENARIOS = (
    ("api_power_brightness", "global_controls"),
    ("api_segment_power_brightness_selection", "segment_controls"),
    ("api_rgb_formats_and_channel_preservation", "color_formats"),
    ("api_effect_selection", "effect_selection"),
    ("api_effect_speed_intensity", "effect_parameters"),
    ("api_palette_selection", "palette_selection"),
    ("api_http_to_ble_controls_and_live_state", "reverse_controls"),
    ("api_invalid_requests_preserve_state", "invalid_requests"),
)


def api_projection(state):
    """Only compare stable state fields; omit transient errors and usermod connection status."""
    return {"on": state["on"], "bri": state["bri"], "mainseg": state.get("mainseg"),
            "seg": [{key: copy.deepcopy(segment[key]) for key in ("id", *SEGMENT_FIELDS, *INVARIANT_FIELDS)
                     if key in segment} for segment in state["seg"]]}


class ApiHilRunner(HilRunner):
    """Verify application behavior and restore every API-visible field the suite changes."""
    def __init__(self, args, client_factory=None, oracle=None):
        super().__init__(args, client_factory, oracle or HttpOracle(args.http_url, args.timeout))
        self.api_baseline = None
        self.invariants = None
        self.target = None
        self.effects = []
        self.palettes = []
        self.mutated = False

    async def setup_api(self):
        await self.setup()
        snapshot = await self.oracle_snapshot()
        state = await self.request("GET", "/json/state")
        if state.get("pl", -1) >= 0 or state.get("ps", -1) > 0:
            raise CoverageMissing("Functional fixture must have no active playlist or preset identity")
        if state.get("nl", {}).get("on") or snapshot["info"].get("live"):
            raise CoverageMissing("Functional fixture must have no nightlight or realtime input")
        if not state.get("seg"):
            raise CoverageMissing("No existing active segment is available")
        for segment in state["seg"]:
            check(all(field in segment for field in SEGMENT_FIELDS), "Segment lacks required restorable API fields")
        baseline = {"on": state["on"], "bri": state["bri"],
                    "seg": [{"id": segment["id"], **{field: copy.deepcopy(segment[field]) for field in SEGMENT_FIELDS}}
                            for segment in state["seg"]]}
        restore = self.state_payload(baseline)
        check(len(("POST /json/state\n\n" + json.dumps(restore)).encode()) <= self.max_request,
              "Complete runtime restoration exceeds the fixture BLE request limit")
        self.api_baseline = baseline
        self.invariants = api_projection(state)
        self.target = next((segment for segment in state["seg"] if segment.get("lc", 0) & 1), state["seg"][0])
        (self.output / "api-baseline-state.json").write_text(json.dumps(baseline, indent=2) + "\n")
        await self.verify_state(baseline)

        metadata = await self.request("GET", "/json/fxdata")
        names = await self.request("GET", "/json/effects")
        count = snapshot["info"].get("fxcount")
        check(isinstance(metadata, list) and isinstance(names, list), "Effects API did not return arrays")
        check(len(metadata) == len(names) == count, "Effect arrays cannot be mapped reliably to advertised IDs")
        self.effects = [(index, name) for index, name in enumerate(names)
                        if name in ("Solid", "Blink", "Breathe") and isinstance(metadata[index], str)]
        # HTTP /json embeds the fixed palette-name array. Custom palette IDs are not
        # contiguous, so info.palcount must never be treated as the highest valid ID.
        fixed = snapshot.get("palettes", [])
        self.palettes = [(index, fixed[index]) for index in (0, 2, 6)
                         if index < len(fixed) and isinstance(fixed[index], str)]
        return f"Saved power/brightness and {len(baseline['seg'])} existing segments; target segment {self.target['id']}"

    def state_payload(self, update):
        """Allow only reversible controls; suppress sync broadcasts without changing UDP settings."""
        check(set(update) <= {"on", "bri", "seg", "v"}, "Unexpected functional-suite state field")
        payload = {"tt": 0, "udpn": {"nn": True}, **copy.deepcopy(update)}
        segments = payload.get("seg", [])
        check(isinstance(segments, list), "Segment updates must be explicit-id arrays")
        for segment in segments:
            check("id" in segment and set(segment) <= {"id", *SEGMENT_FIELDS}, "Unsafe segment mutation requested")
            if "fx" in segment:
                segment["fxdef"] = False
        return payload

    async def apply(self, update, *, method="ble", path="/json/state"):
        payload = self.state_payload(update)
        self.mutated = True  # A lost response cannot prove that a mutation did not occur.
        if method == "http":
            return await self.oracle_snapshot(payload)
        return await self.request("POST", path, json.dumps(payload))

    async def apply_segment(self, values, *, method="ble"):
        return await self.apply({"seg": [{"id": self.target["id"], **values}]}, method=method)

    def assert_invariants(self, state, source):
        original = self.invariants
        check(state.get("mainseg") == original["mainseg"], f"{source}: main segment changed unexpectedly")
        check([segment["id"] for segment in state["seg"]] == [segment["id"] for segment in original["seg"]],
              f"{source}: existing segment IDs changed")
        for expected, actual in zip(original["seg"], state["seg"]):
            for key in INVARIANT_FIELDS:
                check(actual.get(key) == expected.get(key), f"{source}: segment {expected['id']} invariant {key} changed")

    def assert_fields(self, state, expected, source):
        for key in ("on", "bri"):
            if key in expected:
                check(state.get(key) == expected[key], f"{source}: global {key} mismatch")
        for segment in expected.get("seg", []):
            actual = next((item for item in state["seg"] if item["id"] == segment["id"]), None)
            check(actual is not None, f"{source}: expected segment missing")
            for key, value in segment.items():
                check(actual.get(key) == value, f"{source}: segment {segment['id']} field {key} mismatch")
        self.assert_invariants(state, source)

    async def verify_state(self, expected):
        ble = await self.request("GET", "/json/state")
        http = (await self.oracle_snapshot())["state"]
        self.assert_fields(ble, expected, "BLE")
        self.assert_fields(http, expected, "HTTP")
        return ble

    async def verify_segment(self, fields):
        state = await self.verify_state({"seg": [{"id": self.target["id"], **fields}]})
        return next(segment for segment in state["seg"] if segment["id"] == self.target["id"])

    async def global_controls(self):
        for update in ({"on": False}, {"on": True, "bri": 1}, {"bri": 128}, {"bri": 255}):
            await self.apply(update)
            await self.verify_state(update)
        await self.apply({"bri": 0})
        await self.verify_state({"on": False, "bri": 255})  # /state reports briLast, not zero.
        response = await self.apply({"on": True, "bri": 91, "v": True}, path="/json")
        check("state" in response and "info" in response, "Verbose POST /json did not return state/info")
        await self.verify_state({"on": True, "bri": 91})
        return "Power off/on; brightness 0/1/128/255; retained briLast; verbose POST /json verified by HTTP"

    async def segment_controls(self):
        await self.apply_segment({"on": False, "sel": False})
        await self.verify_segment({"on": False, "sel": False})
        for brightness in (1, 127, 255):
            await self.apply_segment({"bri": brightness})
            await self.verify_segment({"bri": brightness, "on": True})
        await self.apply_segment({"bri": 0, "sel": True})
        await self.verify_segment({"bri": 255, "on": False, "sel": True})
        await self.apply_segment({"on": True})
        await self.verify_segment({"on": True})
        return f"Segment {self.target['id']}: selection, power, brightness 0/1/127/255 and retained opacity verified by HTTP"

    def require_rgb(self):
        if not self.target.get("lc", 0) & 1:
            raise CoverageMissing("Selected fixture segment has no RGB capability")

    async def color_formats(self):
        self.require_rgb()
        width = len(self.target["col"][0])
        colors = [[11, 47, 89], [131, 173, 211], [29, 71, 113]]
        if width == 4:
            for color, white in zip(colors, (23, 53, 83)):
                color.append(white)
        await self.apply_segment({"col": colors})
        await self.verify_segment({"col": colors})
        await self.apply_segment({"col": [{"g": 101}, [], []]})
        colors[0][1] = 101
        await self.verify_segment({"col": colors})
        await self.apply_segment({"col": ["336699", [], []]})
        colors[0] = [51, 102, 153] + ([0] if width == 4 else [])
        await self.verify_segment({"col": colors})
        return "Three color slots, partial green-channel preservation, empty-slot no-op and hex RGB verified by HTTP" + (
            "; RGBW white preserved by object update and cleared by six-digit hex" if width == 4 else "; RGB-only fixture")

    def require_effects(self):
        if len(self.effects) < 2:
            raise CoverageMissing("Two advertised simple effects are required for effect selection")

    async def effect_selection(self):
        self.require_effects()
        selected = self.effects[:3]
        for effect, _name in selected:
            previous = await self.verify_segment({})
            await self.apply_segment({"fx": effect})
            await self.verify_segment({"fx": effect, **{key: previous[key] for key in ("sx", "ix", "pal")}})
        return "Selected " + ", ".join(f"{name} ({effect})" for effect, name in selected) + "; HTTP matched IDs; fxdef:false preserved parameters/mapping"

    async def effect_parameters(self):
        for speed, intensity in ((0, 255), (1, 254), (127, 128), (255, 0)):
            await self.apply_segment({"sx": speed, "ix": intensity})
            await self.verify_segment({"sx": speed, "ix": intensity})
        return "Effect speed/intensity combinations 0/255, 1/254, 127/128 and 255/0 verified by HTTP"

    async def palette_selection(self):
        self.require_rgb()
        if len(self.palettes) < 2:
            raise CoverageMissing("HTTP /json did not advertise two fixed palette names")
        for palette, _name in self.palettes:
            await self.apply_segment({"pal": palette})
            await self.verify_segment({"pal": palette})
        return "Selected fixed palettes " + ", ".join(f"{name} ({palette})" for palette, name in self.palettes) + "; HTTP matched each selection"

    async def reverse_controls(self):
        self.require_effects()
        fields = {"on": True, "bri": 83, "sx": 37, "ix": 219, "fx": self.effects[0][0]}
        if self.palettes and self.target.get("lc", 0) & 1:
            fields["pal"] = self.palettes[-1][0]
        await self.client.subscribe_live()
        try:
            await self.apply_segment(fields, method="http")
            await self.verify_segment(fields)
            async with asyncio.timeout(self.args.timeout):
                while True:
                    value = await self.client.next_live(timeout=self.args.timeout)
                    check(mac_identity(value["info"]) == self.identity, "LIVE identity changed")
                    target = next((segment for segment in value["state"]["seg"] if segment["id"] == self.target["id"]), {})
                    if all(target.get(key) == expected for key, expected in fields.items()):
                        break
        finally:
            await self.client.unsubscribe_live()
        return "HTTP changed segment power/brightness/effect/speed/intensity/palette; BLE reads and LIVE converged"

    async def invalid_requests(self):
        before = api_projection(await self.verify_state({}))
        for method, path, body, status in (("POST", "/json/state", "{", 400),
                                           ("POST", "/json/state", "[]", 400),
                                           ("POST", "/json/state", "null", 400),
                                           ("POST", "/unsupported", "{}", 404),
                                           ("DELETE", "/json/state", "", 405)):
            await self.request(method, path, body, expected=status)
            check(api_projection(await self.verify_state(before)) == before, "Rejected request changed API state")
        await self.apply_segment({"sx": -1, "ix": -1})  # getVal ignores negatives; this is not a 400 contract.
        check(api_projection(await self.verify_state(before)) == before, "Negative effect parameters were not ignored")
        return "Malformed/non-object JSON 400, unsupported route 404 and method 405 preserved state; negative speed/intensity ignored"

    async def restore_api(self):
        if self.api_baseline is None or not self.mutated:
            return "No functional API state changes require restoration"
        if self.client is None or not self.client.client.is_connected:
            await self.connect()
        check(mac_identity(await self.request("GET", "/json/info")) == self.identity, "Refusing API restoration onto another device")
        await self.oracle_snapshot()
        await self.apply(self.api_baseline)
        await self.verify_state(self.api_baseline)
        return "Exact power/brightness and all touched fields on every original segment restored through BLE and verified by HTTP"

    def write_reports(self):
        super().write_reports()
        path = self.output / "results.json"
        result = json.loads(path.read_text())
        result["api_scenarios"] = [name for name, _ in SCENARIOS]
        result["coverage_limits"] = [
            "API-visible state verified; physical LED colors, animation timing and effect phase are not observed",
            "Existing segments only; no segment creation/deletion, bounds, LED mapping, pins or length changes",
            "No preset/configuration/filesystem writes; active presets, playlists, realtime input and nightlights require another fixture",
            "Fixed advertised palettes and simple effects only; custom palettes and audio/2D effects are outside this suite",
        ]
        path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        report = self.output / "report.md"
        prefix = report.read_text().split("## Coverage limits", 1)[0]
        report.write_text(prefix + "## Coverage limits\n\n" + "\n".join("- " + item for item in result["coverage_limits"]) + "\n")

    async def run(self):
        try:
            self.write_reports()
            if await self.case("api_fixture_and_runtime_baseline", self.setup_api,
                               timeout=self.args.connect_timeout + self.args.timeout * 10 + 15, recover=False):
                for name, method in SCENARIOS:
                    passed = await self.case(name, getattr(self, method))
                    if not passed and self.records[-1]["status"] == "fail":
                        break
        except asyncio.CancelledError:
            self.records.append({"name": "interruption", "status": "fail", "detail": "Run interrupted", "duration_s": 0})
            raise
        finally:
            await self.case("restore_api_runtime_baseline", self.restore_api,
                            timeout=self.args.connect_timeout + self.args.timeout * 6 + 15, recover=False)
            if self.api_baseline is not None and self.previous_uptime is not None:
                await self.case("final_health", self.sample, recover=False)
            await self.case("disconnect", self.disconnect, timeout=12, recover=False)
            await self.case("close_oracle", self.oracle.close, timeout=self.args.timeout + 3, recover=False)
            self.finish_reports()
        return self.exit_code()


def parse_args(argv=None):
    args = base_parse_args(argv)
    if not args.http_url or args.serial_port:
        raise ValueError("Functional API scenarios require --http-url and no --serial-port")
    args.suite = "functional_api"
    return args


async def main(argv=None):
    return await ApiHilRunner(parse_args(argv)).run()


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(130)
# AI: end
