#include "ble_api_bridge.h"
#include <Preferences.h>
#include <algorithm>
#include <new>

// AI: below section was generated by an AI
namespace ble_api_bridge {

// WLED settings callbacks can run on a network task. Only copy small configuration snapshots under the mutex.
bool BleApiBridgeUsermod::copyConfig(Config& config) {
  if (_configMutex && xSemaphoreTake(_configMutex, pdMS_TO_TICKS(20)) != pdTRUE) return false;
  config = _config;
  if (_configMutex) xSemaphoreGive(_configMutex);
  return true;
}

bool BleApiBridgeUsermod::storeConfig(const Config& config) {
  if (_configMutex && xSemaphoreTake(_configMutex, pdMS_TO_TICKS(20)) != pdTRUE) return false;
  _config = config;
  _configChanged.store(true);
  if (_configMutex) xSemaphoreGive(_configMutex);
  return true;
}

void BleApiBridgeUsermod::setLastError(const String& error) {
  DEBUG_PRINT(F("[BleApiBridge] "));
  DEBUG_PRINTLN(error);
}

void BleApiBridgeUsermod::clearRequestAssembly() { _request = {}; }
void BleApiBridgeUsermod::clearResponse() { _response = {}; }

void BleApiBridgeUsermod::syncDeviceName() {
  if (_deviceName.isEmpty()) {
    _deviceName = String(F("WLED-")) + escapedMac.substring(escapedMac.length() > 6 ? escapedMac.length() - 6 : 0);
  }
  // A scan response has 31 bytes including the AD type and length. Do not split UTF-8 characters.
  if (_deviceName.length() > 29) {
    size_t end = 29;
    while (end && (static_cast<uint8_t>(_deviceName[end]) & 0xc0) == 0x80) --end;
    _deviceName.remove(end);
  }
}

// Apply settings on WLED's loop, never on NimBLE's host task or an HTTP callback.
void BleApiBridgeUsermod::applyConfig() {
  Config config;
  if (!copyConfig(config)) { _configChanged.store(true); return; }
  const String oldName = _deviceName;
  const bool settingsChanged = _enabled != config.enabled || _maxRequestBytes != config.maxRequestBytes;
  _enabled = config.enabled;
  _deviceName = config.name;
  syncDeviceName();
  _maxRequestBytes = config.maxRequestBytes;
  if (config.passkey >= 100000 && config.passkey <= 999999 && config.passkey != _passkey.load()) {
    Preferences preferences;
    if (preferences.begin("wled-ble", false)) {
      if (preferences.putUInt("passkey", config.passkey) == sizeof(uint32_t)) {
        stopBle();
        if (_bleInitialized) NimBLEDevice::deleteAllBonds();
        _passkey.store(config.passkey);
        if (_bleInitialized) NimBLEDevice::setSecurityPasskey(config.passkey);
        _restartBlePending = true;
      } else { setLastError(F("Could not save pairing code")); }
      preferences.end();
    }
  }
  if (_setupDone && (settingsChanged || oldName != _deviceName)) _restartBlePending = true;
}

void BleApiBridgeUsermod::setup() {
  _configMutex = xSemaphoreCreateMutex();
  _events = xQueueCreate(32, sizeof(Event));
  _requestBuffer.reset(new (std::nothrow) uint8_t[MAX_REQUEST_BYTES_LIMIT]);
  if (!_configMutex || !_events || !_requestBuffer) {
    _enabled = false;
    setLastError(F("Not enough memory for Bluetooth bridge"));
    return;
  }
  // Each installation gets its own persistent code; bonding keys are separately managed by NimBLE in NVS.
  Preferences preferences;
  if (!preferences.begin("wled-ble", false)) { _enabled = false; return; }
  uint32_t passkey = preferences.getUInt("passkey", 0);
  if (passkey < 100000 || passkey > 999999) {
    passkey = 100000 + esp_random() % 900000;
    if (preferences.putUInt("passkey", passkey) != sizeof(uint32_t)) { preferences.end(); _enabled = false; return; }
  }
  preferences.end();
  _passkey.store(passkey);
  applyConfig();
  _configChanged.store(false);
  _setupDone = true;
  if (_enabled) initBleStack();
}

void BleApiBridgeUsermod::loop() {
  if (!_setupDone) return;
  if (!_response.active && _configChanged.exchange(false)) applyConfig();
  handleEvents();
  if (!_enabled) { if (_acceptConnections.load()) stopBle(); return; }
  if (_restartBlePending && !_response.active) refreshBleConfiguration();
  if (!_bleInitialized) return;
  if (_bleConnected && !_secure && millis() - _connectedAt >= PAIRING_TIMEOUT) {
    failConnection("Bluetooth pairing timed out");
  }
  if (_request.expired(millis(), DEFAULT_REQUEST_TIMEOUT)) {
    failConnection("BLE request assembly timed out");
  }
  if (_stateChanged.exchange(false) && _liveUpdatesEnabled) {
    if (!_livePushPending) _livePushDueAt = millis() + LIVE_PUSH_DEBOUNCE_MS;
    _livePushPending = true;
  }
  if (_request.ready && !_response.active) processBleRequest();
  if (_livePushPending && _secure && !_response.active && !_request.active && !_request.ready
      && static_cast<int32_t>(millis() - _livePushDueAt) >= 0) {
    if (queueLiveStatePush()) _livePushPending = false;
    else _livePushDueAt = millis() + 500;
  }
  sendNextResponseChunk();
  if (!_bleConnected && static_cast<int32_t>(millis() - _nextAdvertiseAt) >= 0) startAdvertising();
}

void BleApiBridgeUsermod::addToJsonInfo(JsonObject& root) {
  JsonObject user = root["u"];
  if (user.isNull()) user = root.createNestedObject("u");
  JsonArray bridge = user.createNestedArray(F("BLE API"));
  bridge.add(_acceptConnections.load() ? F("enabled") : F("disabled"));
  JsonObject capabilities = root.createNestedObject("ble");
  capabilities["protocol"] = 1;
  Config config;
  capabilities["maxRequest"] = copyConfig(config) ? config.maxRequestBytes : DEFAULT_MAX_REQUEST_BYTES;
  capabilities["security"] = "passkey";
}

void BleApiBridgeUsermod::addToJsonState(JsonObject& root) {
  JsonObject state = root.createNestedObject(UM_NAME);
  state["enabled"] = _acceptConnections.load();
  state["connected"] = _bleConnected.load();
  state["live"] = _liveUpdatesEnabled.load();
}

void BleApiBridgeUsermod::addToConfig(JsonObject& root) {
  Config config;
  if (!copyConfig(config)) return;
  JsonObject top = root.createNestedObject(UM_NAME);
  top["enabled"] = config.enabled;
  top["device-name"] = config.name;
  top["max-request-bytes"] = config.maxRequestBytes;
  // Config may be saved before loop() applies the change (or while its reply is still being confirmed).
  // Persist the requested code so the next boot cannot restore the previous code over the new NVS value.
  top["pairing-code"] = config.passkey ? config.passkey : _passkey.load();
}

void BleApiBridgeUsermod::appendConfigData() {
  oappend(F("addInfo('BleApiBridge:pairing-code',1,'Enter this code in the iOS pairing prompt. Changing it forgets paired phones.');"));
  oappend(F("addInfo('BleApiBridge:device-name',1,'Blank uses WLED plus a unique device suffix.');"));
  oappend(F("addInfo('BleApiBridge:max-request-bytes',1,'256-4096');"));
}

bool BleApiBridgeUsermod::readFromConfig(JsonObject& root) {
  JsonObject top = root[UM_NAME];
  if (top.isNull()) return false;
  Config config;
  if (!copyConfig(config)) return false;
  config.enabled = top["enabled"] | config.enabled;
  const char* name = top["device-name"] | config.name;
  // strlcpy is also safe when config.name is the fallback source.
  if (name != config.name) {
    size_t length = strnlen(name, sizeof(config.name) - 1);
    while (length && (static_cast<uint8_t>(name[length]) & 0xc0) == 0x80) --length;
    memcpy(config.name, name, length);
    config.name[length] = '\0';
  }
  int limit = top["max-request-bytes"] | static_cast<int>(config.maxRequestBytes);
  config.maxRequestBytes = std::max(256, std::min(static_cast<int>(MAX_REQUEST_BYTES_LIMIT), limit));
  uint32_t passkey = top["pairing-code"] | config.passkey;
  if (passkey >= 100000 && passkey <= 999999) config.passkey = passkey;
  return storeConfig(config);
}

void BleApiBridgeUsermod::onStateChange(uint8_t) { _stateChanged.store(true); }
} // namespace ble_api_bridge
// AI: end
