#include "ble_api_bridge.h"
#include <algorithm>
#include <cstring>

// AI: below section was generated by an AI
namespace ble_api_bridge {

// Only callbacks enqueue events. All buffers, WLED calls, and response state belong to loop().
void BleApiBridgeUsermod::enqueue(const Event& event) {
  if (!_events || xQueueSend(_events, &event, 0) != pdTRUE) {
    _queueOverflow.store(true);
    if (_server) _server->disconnect(event.connection);
  }
}

// NimBLE can deliver encryption/CCCD restoration before its delayed GAP CONNECT event.
// Admit the peer on its first callback, enqueue Connected before its other events, and
// make the later onConnect idempotent. Authentication still gates every RX/TX operation.
bool BleApiBridgeUsermod::acceptConnection(NimBLEConnInfo& info) {
  const uint16_t connection = info.getConnHandle();
  if (!_acceptConnections.load()) {
    _server->disconnect(connection);
    return false;
  }
  uint16_t expected = BLE_HS_CONN_HANDLE_NONE;
  if (_callbackConnHandle.compare_exchange_strong(expected, connection)) {
    enqueue({EventType::Connected, connection, 0, 0, 0, {}});
  } else if (expected != connection) {
    _server->disconnect(connection);
    return false;
  }
  return true;
}

void BleApiBridgeUsermod::onConnect(NimBLEServer*, NimBLEConnInfo& info) {
  acceptConnection(info);
  // Protected reads initiate pairing on iOS. Avoid racing discovery with unsolicited security requests.
}

void BleApiBridgeUsermod::onDisconnect(NimBLEServer*, NimBLEConnInfo& info, int reason) {
  uint16_t expected = info.getConnHandle();
  _callbackConnHandle.compare_exchange_strong(expected, BLE_HS_CONN_HANDLE_NONE);
  enqueue({EventType::Disconnected, info.getConnHandle(), 0, reason, 0, {}});
}

void BleApiBridgeUsermod::onAuthenticationComplete(NimBLEConnInfo& info) {
  if (!acceptConnection(info)) return;
  const bool secure = info.isEncrypted() && info.isAuthenticated() && info.isBonded();
  enqueue({EventType::Authenticated, info.getConnHandle(), 0, secure ? 0 : 1, 0, {}});
  if (!secure) _server->disconnect(info.getConnHandle());
}

void BleApiBridgeUsermod::onWrite(NimBLECharacteristic* characteristic, NimBLEConnInfo& info) {
  if (characteristic != _rx || !info.isEncrypted() || !info.isAuthenticated() || !info.isBonded()) {
    DEBUG_PRINTF("[BleApiBridge] Rejected RX: encrypted=%u authenticated=%u bonded=%u\n",
                 info.isEncrypted(), info.isAuthenticated(), info.isBonded());
    _server->disconnect(info.getConnHandle());
    return;
  }
  if (!acceptConnection(info)) return;
  const auto value = characteristic->getValue();
  if (value.size() == 0 || value.size() > MAX_RESPONSE_CHUNK) {
    _server->disconnect(info.getConnHandle());
    return;
  }
  Event event{EventType::Write, info.getConnHandle(), characteristic->getHandle(), 0,
              static_cast<uint16_t>(value.size()), {}};
  memcpy(event.data, value.data(), value.size());
  enqueue(event);
}

void BleApiBridgeUsermod::onSubscribe(NimBLECharacteristic* characteristic, NimBLEConnInfo& info, uint16_t value) {
  if (!acceptConnection(info)) return;
  enqueue({EventType::Subscribed, info.getConnHandle(), characteristic->getHandle(), value, 0, {}});
}

void BleApiBridgeUsermod::onStatus(NimBLECharacteristic* characteristic, NimBLEConnInfo&, int status) {
  // NimBLE-Arduino 2.5.1 leaves onStatus's connInfo zero-initialized (NimBLEServer.cpp, NOTIFY_TX).
  // This service allows one peer; capture its real handle when its first callback admits it.
  const uint16_t connection = _callbackConnHandle.load();
  if (connection != BLE_HS_CONN_HANDLE_NONE) {
    enqueue({EventType::Confirmed, connection, characteristic->getHandle(), status, 0, {}});
  }
}

// Process the ordered host event stream before dispatching requests or sending another indication.
void BleApiBridgeUsermod::handleEvents() {
  if (_queueOverflow.exchange(false)) {
    xQueueReset(_events);
    failConnection("BLE event queue full; reconnect required");
    return;
  }
  Event event;
  while (xQueueReceive(_events, &event, 0) == pdTRUE) {
    if (event.type == EventType::Connected) {
      if (!_enabled || _bleConnected) { _server->disconnect(event.connection); continue; }
      resetConnection();
      _activeConnHandle = event.connection;
      _bleConnected = true;
      _connectedAt = millis();
      continue;
    }
    if (event.connection != _activeConnHandle) continue;
    switch (event.type) {
      case EventType::Disconnected:
        resetConnection();
        break;
      case EventType::Authenticated:
        _secure = event.status == 0;
        if (!_secure) failConnection("Bluetooth pairing failed");
        break;
      case EventType::Subscribed:
        if (event.handle == _tx->getHandle()) {
          _indicationsEnabled = (event.status & 2) != 0;
        } else if (event.handle == _live->getHandle()) {
          _liveUpdatesEnabled = (event.status & 2) != 0;
          _livePushPending = _liveUpdatesEnabled;
          _livePushDueAt = millis() + LIVE_PUSH_DEBOUNCE_MS;
        }
        if (_response.active && _response.characteristic->getHandle() == event.handle && !(event.status & 2)) {
          failConnection("Indications disabled during response");
        }
        break;
      case EventType::Write:
        if (!_secure || !_indicationsEnabled || !processWriteChunk(event.data, event.size)) {
          DEBUG_PRINTF("[BleApiBridge] Rejected queued RX: secure=%u subscribed=%u bytes=%u active=%u ready=%u\n",
                       _secure, _indicationsEnabled, event.size, _request.active, _request.ready);
          failConnection("Invalid or overlapping BLE request");
        }
        break;
      case EventType::Confirmed:
        if (!_response.active || !_response.awaitingConfirmation
            || event.handle != _response.characteristic->getHandle()) break;
        if (event.status != BLE_HS_EDONE) {
          failConnection("BLE indication failed");
          break;
        }
        _response.awaitingConfirmation = false;
        if (_response.offset == _response.payload.length()) clearResponse();
        break;
      default: break;
    }
  }
}

// NimBLE-Arduino supplies its own host on Arduino 3 / IDF 5 and persists bonds in NVS.
bool BleApiBridgeUsermod::initBleStack() {
  if (_bleInitialized) return true;
  if (!NimBLEDevice::init(_deviceName.c_str())) { setLastError(F("NimBLE init failed")); return false; }
  NimBLEDevice::setSecurityAuth(true, true, true);
  NimBLEDevice::setSecurityIOCap(BLE_HS_IO_DISPLAY_ONLY);
  NimBLEDevice::setSecurityPasskey(_passkey.load());
  NimBLEDevice::setMTU(DEFAULT_MTU);
  const auto failed = [this]() {
    NimBLEDevice::deinit(true);
    _server = nullptr;
    _rx = _tx = _live = nullptr;
    setLastError(F("Could not initialize BLE services"));
    return false;
  };
  _server = NimBLEDevice::createServer();
  if (!_server) return failed();
  _server->setCallbacks(this, false);
  _server->advertiseOnDisconnect(false);
  auto service = _server->createService(SERVICE_UUID);
  if (!service) return failed();
  _rx = service->createCharacteristic(RX_UUID, NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::WRITE_ENC | NIMBLE_PROPERTY::WRITE_AUTHEN,
                                      MAX_RESPONSE_CHUNK);
  const auto flags = NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::READ_ENC | NIMBLE_PROPERTY::READ_AUTHEN | NIMBLE_PROPERTY::INDICATE;
  _tx = service->createCharacteristic(TX_UUID, flags, MAX_RESPONSE_CHUNK);
  _live = service->createCharacteristic(LIVE_UUID, flags, MAX_RESPONSE_CHUNK);
  if (!_rx || !_tx || !_live) return failed();
  _rx->setCallbacks(this);
  _tx->setCallbacks(this);
  _live->setCallbacks(this);
  _tx->setValue("ready");
  _live->setValue("live");
  if (!_server->start()) return failed();
  _bleInitialized = true;
  _acceptConnections.store(_enabled);
  return startAdvertising();
}

// Put the service in the advertisement and the (bounded) name in the scan response.
bool BleApiBridgeUsermod::startAdvertising() {
  if (!_bleInitialized || !_enabled || _bleConnected) return false;
  auto advertising = NimBLEDevice::getAdvertising();
  if (advertising->isAdvertising()) return true;
  _nextAdvertiseAt = millis() + 1000;
  NimBLEAdvertisementData data;
  data.setFlags(BLE_HS_ADV_F_DISC_GEN | BLE_HS_ADV_F_BREDR_UNSUP);
  data.setCompleteServices(NimBLEUUID(SERVICE_UUID));
  NimBLEAdvertisementData scan;
  scan.setName(_deviceName.c_str());
  if (!advertising->setAdvertisementData(data) || !advertising->setScanResponseData(scan)) return false;
  advertising->enableScanResponse(true);
  return advertising->start();
}

void BleApiBridgeUsermod::resetConnection() {
  _bleConnected = false;
  _secure = false;
  _activeConnHandle = BLE_HS_CONN_HANDLE_NONE;
  _indicationsEnabled = false;
  _liveUpdatesEnabled = false;
  _livePushPending = false;
  _nextAdvertiseAt = millis();
  clearRequestAssembly();
  clearResponse();
}

void BleApiBridgeUsermod::failConnection(const char* message) {
  setLastError(message);
  if (_server && _activeConnHandle != BLE_HS_CONN_HANDLE_NONE) _server->disconnect(_activeConnHandle);
  resetConnection();
}

void BleApiBridgeUsermod::stopBle() {
  _acceptConnections.store(false);
  if (!_bleInitialized) return;
  NimBLEDevice::getAdvertising()->stop();
  if (_activeConnHandle != BLE_HS_CONN_HANDLE_NONE) _server->disconnect(_activeConnHandle);
  resetConnection();
}

void BleApiBridgeUsermod::refreshBleConfiguration() {
  stopBle();
  _restartBlePending = false;
  if (_enabled) {
    if (!_bleInitialized) initBleStack();
    NimBLEDevice::setDeviceName(_deviceName.c_str());
    _acceptConnections.store(true);
    _nextAdvertiseAt = millis() + 100;
  }
}

// A live frame can finish while the next command is assembled; never discard that command as "busy".
bool BleApiBridgeUsermod::processWriteChunk(const uint8_t* data, size_t len) {
  return _request.append(data, len, _requestBuffer.get(), _maxRequestBytes, millis());
}

// ATT allows only one outstanding indication. Advance only after its confirmation event.
void BleApiBridgeUsermod::sendNextResponseChunk() {
  if (!_response.active || !_secure || !_bleConnected) return;
  if (_response.awaitingConfirmation) {
    if (millis() - _response.sentAt >= INDICATION_TIMEOUT) failConnection("BLE indication timed out");
    return;
  }
  const uint16_t mtu = _server->getPeerMTU(_activeConnHandle);
  if (mtu < 23) { failConnection("Invalid BLE MTU"); return; }
  const size_t budget = std::min<size_t>(mtu - 3, MAX_RESPONSE_CHUNK);
  uint8_t packet[MAX_RESPONSE_CHUNK];
  size_t prefix = _response.firstChunk ? 2 : 0;
  if (prefix) {
    packet[0] = _response.payload.length() & 0xff;
    packet[1] = _response.payload.length() >> 8;
  }
  size_t count = std::min(budget - prefix, _response.payload.length() - _response.offset);
  memcpy(packet + prefix, _response.payload.c_str() + _response.offset, count);
  if (!_response.characteristic->indicate(packet, count + prefix, _activeConnHandle)) {
    failConnection("BLE indication could not be queued");
    return;
  }
  _response.offset += count;
  _response.firstChunk = false;
  _response.awaitingConfirmation = true;
  _response.sentAt = millis();
}
} // namespace ble_api_bridge
// AI: end
