#include "ble_api_bridge.h"
#include "persistence_status.h"
#include <algorithm>

// Existing HTTP serializers, reused without creating network request objects.
void serializePalettes(JsonObject root, int page);
void serializeNetworks(JsonObject root);
void serializeNodes(JsonObject root);

// AI: below section was generated by an AI

namespace ble_api_bridge {

String BleApiBridgeUsermod::buildSuccessEnvelope() const {
  return F("{\"success\":true}");
}

String BleApiBridgeUsermod::buildErrorEnvelope(uint16_t status, const String& message) const {
  String payload;
  payload.reserve(message.length() + 48);
  payload += F("{\"success\":false,\"status\":");
  payload += status;
  payload += F(",\"error\":\"");
  for (size_t i = 0; i < message.length(); i++) {
    char c = message.charAt(i);
    if (c == '\\' || c == '"') payload += '\\';
    payload += c;
  }
  payload += F("\"}");
  return payload;
}

bool BleApiBridgeUsermod::queueResponse(uint16_t status, const char* contentType, const String& body) {
  if (!_tx || _response.active || body.isEmpty()) return false;
  String header;
  header.reserve(strlen(contentType) + 24);
  header += status;
  header += ' ';
  header += contentType;
  header += F("\n\n");

  if (header.length() + body.length() > UINT16_MAX) {
    setLastError(F("response exceeds BLE bridge size limit"));
    return false;
  }

  if (!_response.payload.reserve(header.length() + body.length() + 1)) return false;
  _response.payload = header;
  _response.payload += body;
  if (_response.payload.length() != header.length() + body.length()) return false;
  _response.offset = 0;
  _response.characteristic = _tx;
  _response.active = true;
  _response.firstChunk = true;
  _response.awaitingConfirmation = false;
  return true;
}

bool BleApiBridgeUsermod::queueErrorResponse(uint16_t status, const String& message) {
  return queueResponse(status, "application/json", buildErrorEnvelope(status, message));
}

bool BleApiBridgeUsermod::queueLiveStatePush() {
  if (!_liveUpdatesEnabled || _live == nullptr) return false;

  String body;
  if (!buildJsonBody(F("/json/si"), body)) {
    return false;
  }

  if (body.length() > UINT16_MAX) {
    setLastError(F("live push exceeds BLE bridge size limit"));
    return false;
  }

  if (!_response.payload.reserve(body.length() + 1)) return false;
  _response.payload = body;
  if (_response.payload.length() != body.length()) return false;
  _response.offset = 0;
  _response.characteristic = _live;
  _response.active = true;
  _response.firstChunk = true;
  _response.awaitingConfirmation = false;
  return true;
}

bool BleApiBridgeUsermod::buildJsonBody(const String& rawPath, String& body) {
  String path = normalizePath(rawPath);
  JSONBufferGuard jsonGuard(JSON_LOCK_UNKNOWN);
  if (!jsonGuard) {
    return false;
  }

  pDoc->clear();

  if (path == F("/json/state")) {
    JsonObject root = pDoc->to<JsonObject>();
    serializeState(root);
  } else if (path == F("/json/info")) {
    JsonObject root = pDoc->to<JsonObject>();
    serializeInfo(root);
  } else if (path == F("/json/si") || path == F("/json")) {
    JsonObject root = pDoc->to<JsonObject>();
    JsonObject state = root.createNestedObject("state");
    serializeState(state);
    JsonObject info = root.createNestedObject("info");
    serializeInfo(info);
    if (path == F("/json")) {
      JsonArray effects = root.createNestedArray("effects");
      serializeModeNames(effects);
      root["palettes"] = serialized((const __FlashStringHelper*)JSON_palette_names);
    }
  } else if (path == F("/json/palettes") || path == F("/json/pal")) {
    return body.concat(FPSTR(JSON_palette_names));
  } else if (path == F("/json/palx")) {
    int page = 0;
    int query = rawPath.indexOf("?page=");
    if (query >= 0) page = constrain(rawPath.substring(query + 6).toInt(), 0L, 255L);
    serializePalettes(pDoc->to<JsonObject>(), page);
  } else if (path == F("/json/nodes")) {
    serializeNodes(pDoc->to<JsonObject>());
  } else if (path == F("/json/net")) {
    serializeNetworks(pDoc->to<JsonObject>());
  } else if (path == F("/json/live")) {
    JsonObject root = pDoc->to<JsonObject>();
    JsonArray leds = root.createNestedArray("leds");
    size_t used = strip.getLengthTotal();
    size_t step = std::max<size_t>(1, (used + 255) / 256);
#ifndef WLED_DISABLE_2D
    if (strip.isMatrix && Segment::maxWidth && Segment::maxHeight) {
      used = size_t(Segment::maxWidth) * Segment::maxHeight;
      step = 1;
      while (((Segment::maxWidth + step - 1) / step) * ((Segment::maxHeight + step - 1) / step) > 256) ++step;
      root["w"] = (Segment::maxWidth + step - 1) / step;
      root["h"] = (Segment::maxHeight + step - 1) / step;
    }
#endif
    root["n"] = step;
    for (size_t i = 0; i < used && leds.size() < 256; ++i) {
#ifndef WLED_DISABLE_2D
      if (strip.isMatrix) { if ((i % Segment::maxWidth) % step || (i / Segment::maxWidth) % step) continue; }
      else
#endif
      if (i % step) continue;
      uint32_t color = strip.getPixelColor(i);
      char hex[7];
      snprintf(hex, sizeof(hex), "%02x%02x%02x", scale8(qadd8(W(color), R(color)), strip.getBrightness()),
        scale8(qadd8(W(color), G(color)), strip.getBrightness()), scale8(qadd8(W(color), B(color)), strip.getBrightness()));
      leds.add(hex);
    }
  } else if (path == F("/json/effects")) {
    JsonArray arr = pDoc->to<JsonArray>();
    serializeModeNames(arr);
  } else if (path == F("/json/fxdata")) {
    JsonArray arr = pDoc->to<JsonArray>();
    // Mode metadata has static lifetime; reference it instead of duplicating every string in the JSON pool.
    for (size_t i = 0; i < strip.getModeCount(); ++i) {
      const char* metadata = strchr(strip.getModeData(i), '@');
      arr.add(metadata ? metadata + 1 : "");
    }
  } else if (path == F("/json/pins")) {
    JsonObject root = pDoc->to<JsonObject>();
    serializePins(root);
  } else if (path == F("/json/cfg")) {
    JsonObject root = pDoc->to<JsonObject>();
    serializeConfig(root);
  } else {
    return false;
  }

  if (pDoc->overflowed()) return false;
  const size_t length = measureJson(*pDoc);
  if (!length || length > UINT16_MAX - 32 || !body.reserve(length + 1)) return false;
  body = "";
  return serializeJson(*pDoc, body) == length;
}

String BleApiBridgeUsermod::normalizePath(const String& rawPath) const {
  String path = rawPath;
  path.trim();

  {
    int queryPos = path.indexOf('?');
    if (queryPos >= 0) path.remove(queryPos);
    if (path.length() > 5 && path.endsWith(F("/"))) path.remove(path.length() - 1);
  }

  return path;
}

bool BleApiBridgeUsermod::dispatchGet(const String& rawPath) {
  String path = normalizePath(rawPath);

  if (path == F("/ble/capabilities")) return queueCapabilities();
  if (path == F("/ble/auth")) return queueAuthState();
  if (path == F("/ble/status")) {
    StaticJsonDocument<512> doc;
    JsonObject config = doc.createNestedObject("config");
    config["pending"] = configNeedsWrite || doInitBusses;
    config["generation"] = configWriteGeneration();
    config["success"] = configWriteSucceeded();
    JsonObject presets = doc.createNestedObject("presets");
    presets["pending"] = presetNeedsSaving();
    presets["generation"] = presetWriteGeneration();
    presets["success"] = presetWriteSucceeded();
    doc["rebootPending"] = _rebootAfterResponse;
    return queueDocument(doc);
  }
  if (path == F("/settings/lock")) {
    memset(_authorizedPIN, 0, sizeof(_authorizedPIN));
    cancelTransfer();
    return queueAuthState();
  }
  if (path == F("/settings/s.js")) return dispatchSettingsScript(rawPath);
  if (path == F("/reset")) {
    _rebootAfterResponse = true;
    return queueResponse(200, "application/json", F("{\"success\":true,\"reboot\":true}"));
  }
  if (path.startsWith(F("/win"))) return dispatchLegacy(rawPath);
  if (path == F("/version")) return queueResponse(200, "text/plain", String(VERSION));
  if (path == F("/uptime")) return queueResponse(200, "text/plain", String(millis()));
  if (path == F("/freeheap")) return queueResponse(200, "text/plain", String(getFreeHeapSize()));
  if ((path == F("/json/cfg") || path == F("/json/net")) && !settingsAuthorized()) {
    return queueErrorResponse(401, F("settings PIN required"));
  }
  const bool supported = path == F("/json") || path == F("/json/state") || path == F("/json/info")
    || path == F("/json/si") || path == F("/json/effects") || path == F("/json/fxdata")
    || path == F("/json/pins") || path == F("/json/cfg") || path == F("/json/palettes")
    || path == F("/json/pal") || path == F("/json/palx") || path == F("/json/nodes")
    || path == F("/json/net") || path == F("/json/live");
  if (!supported) return queueErrorResponse(404, F("unsupported GET path"));
  String body;
  if (!buildJsonBody(rawPath, body)) {
    return queueErrorResponse(503, F("JSON unavailable or response too large"));
  }

  return queueResponse(200, "application/json", body);
}

bool BleApiBridgeUsermod::dispatchPostJsonState(const String& bodyText) {
  return dispatchJson(bodyText, nullptr, false);
}

bool BleApiBridgeUsermod::dispatchPostJsonConfig(const String& bodyText) {
  return dispatchJson(bodyText, nullptr, true);
}

bool BleApiBridgeUsermod::dispatchJson(const String& bodyText, Stream* staged, bool configuration) {
  JSONBufferGuard guard(JSON_LOCK_UNKNOWN);
  if (!guard) return queueErrorResponse(503, F("json buffer busy"));
  pDoc->clear();
  DeserializationError error = staged ? deserializeJson(*pDoc, *staged) : deserializeJson(*pDoc, bodyText);
  JsonObject root = pDoc->as<JsonObject>();
  if (error || root.isNull()) return queueErrorResponse(400, F("invalid JSON object"));
  _configBefore = configWriteGeneration();
  _presetsBefore = presetWriteGeneration();
  if (configuration) {
    const char* suppliedPIN = root["pin"] | "";
    bool authorized = settingsAuthorized();
    if (root.containsKey("pin")) {
      if (_hasPINFailure && uint32_t(millis() - _lastPINFailure) < PIN_RETRY_COOLDOWN) return queueErrorResponse(429, F("wait before trying the PIN again"));
      authorized = !settingsPIN[0] || (strnlen(suppliedPIN, 5) == 4 && strncmp(settingsPIN, suppliedPIN, 5) == 0);
      if (!authorized) { _hasPINFailure = true; _lastPINFailure = millis(); }
    }
    if (!authorized) return queueErrorResponse(401, F("settings PIN required"));
    bool save = deserializeConfig(root);
    if (save) configNeedsWrite = true;
    guard.release();
    return queuePersistenceReply(save || doInitBusses || configNeedsWrite, false);
  }
  for (const char* key : {"psave", "pdel"}) {
    if (!root[key].isNull() && (!root[key].is<unsigned>() || root[key].as<unsigned>() > 250))
      return queueErrorResponse(400, F("preset mutation ID must be an integer from 0 to 250"));
  }
  unsigned saveId = root["psave"] | 0U, deleteId = root["pdel"] | 0U;
  if (saveId && deleteId) return queueErrorResponse(400, F("send preset saves and deletes separately"));
  bool savesPreset = (saveId > 0 && saveId <= 250) || (deleteId > 0 && deleteId <= 250);
  if (savesPreset && presetNeedsSaving()) return queueErrorResponse(409, F("preset save in progress"));
  bool verbose = deserializeState(root);
  deferReboot();
  guard.release();
  if (savesPreset) return queuePersistenceReply(configNeedsWrite || doInitBusses, true, verbose);
  if (!verbose) return queueResponse(200, "application/json", _rebootAfterResponse ? F("{\"success\":true,\"reboot\":true}") : buildSuccessEnvelope());
  String responseBody;
  if (!buildJsonBody(F("/json"), responseBody)) return queueErrorResponse(503, F("state unavailable"));
  return queueResponse(200, "application/json", responseBody);
}

bool BleApiBridgeUsermod::dispatchPost(const String& rawPath, const String& bodyText) {
  String path = normalizePath(rawPath);
  if (path == F("/json") || path == F("/json/state") || path == F("/json/si")) {
    return dispatchPostJsonState(bodyText);
  }
  if (path == F("/json/cfg")) {
    return dispatchPostJsonConfig(bodyText);
  }
  if (path.startsWith(F("/ble/"))) return dispatchBridge(path, bodyText);
  if (path.startsWith(F("/settings/"))) return dispatchSettings(path, bodyText);
  return queueErrorResponse(404, F("unsupported POST path"));
}

bool BleApiBridgeUsermod::processRequestText(const String& requestText) {
  int headerEnd = requestText.indexOf(F("\r\n\r\n"));
  int separatorSize = 4;
  if (headerEnd < 0) {
    headerEnd = requestText.indexOf(F("\n\n"));
    separatorSize = 2;
  }

  String header = requestText;
  String body;
  if (headerEnd >= 0) {
    header = requestText.substring(0, headerEnd);
    body = requestText.substring(headerEnd + separatorSize);
  }

  int lineEnd = header.indexOf('\n');
  String requestLine = (lineEnd >= 0) ? header.substring(0, lineEnd) : header;
  requestLine.trim();
  int split = requestLine.indexOf(' ');
  if (split < 0) {
    return queueErrorResponse(400, F("request line must be 'METHOD PATH'"));
  }

  String method = requestLine.substring(0, split);
  String path = requestLine.substring(split + 1);
  method.toUpperCase();
  path.trim();

  if (method == F("GET")) {
    return dispatchGet(path);
  }

  if (method == F("POST")) {
    return dispatchPost(path, body);
  }

  return queueErrorResponse(405, F("unsupported method"));
}

void BleApiBridgeUsermod::processBleRequest() {
  if (!_request.ready || !_requestBuffer) return;

  String requestText;
  if (!requestText.reserve(_request.expected + 1)) {
    clearRequestAssembly();
    if (!queueErrorResponse(503, F("not enough memory"))) failConnection("BLE response allocation failed");
    return;
  }
  for (size_t i = 0; i < _request.expected; i++) {
    if (_requestBuffer[i] == 0) {
      clearRequestAssembly();
      if (!queueErrorResponse(400, F("NUL in request"))) failConnection("BLE response allocation failed");
      return;
    }
    requestText += static_cast<char>(_requestBuffer[i]);
  }

  clearRequestAssembly();
  bool ok = processRequestText(requestText);

  if (!ok && !_response.active) {
    if (!queueErrorResponse(500, F("failed to queue response"))) failConnection("BLE response allocation failed");
  }
}

} // namespace ble_api_bridge

// AI: end
