#pragma once
#include "wled.h"
#include "ble_bridge_protocol.h"

#if !defined(ARDUINO_ARCH_ESP32) || defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32P4)
#error "ble_api_bridge requires an ESP32 with an integrated Bluetooth LE radio (ESP32, C3, S3, C6)."
#endif

#include <NimBLEDevice.h>
#if !MYNEWT_VAL(BLE_SM_SC_ONLY)
#error "BLE bridge requires -D MYNEWT_VAL_BLE_SM_SC_ONLY=1 (see the supplied build profiles)."
#endif
#include <atomic>
#include <memory>
#include "freertos/queue.h"
#include "freertos/semphr.h"

// AI: below section was generated by an AI
// NimBLE 2.x API: https://github.com/h2zero/NimBLE-Arduino/tree/2.5.1
namespace ble_api_bridge {
constexpr char UM_NAME[] = "BleApiBridge";
constexpr uint16_t USERMOD_ID_BLE_API_BRIDGE = 0xB106;
constexpr uint16_t DEFAULT_MAX_REQUEST_BYTES = 4096;
constexpr uint16_t MAX_REQUEST_BYTES_LIMIT = 4096;
constexpr uint16_t DEFAULT_MTU = 247;
constexpr uint16_t MAX_RESPONSE_CHUNK = DEFAULT_MTU - 3;
constexpr uint32_t DEFAULT_REQUEST_TIMEOUT = 10000;
constexpr uint32_t PAIRING_TIMEOUT = 120000;
constexpr uint32_t INDICATION_TIMEOUT = 10000;
constexpr uint32_t LIVE_PUSH_DEBOUNCE_MS = 150;
constexpr char SERVICE_UUID[] = "7c2e0001-5d2b-4fd0-b1c2-0cc8f5470101";
constexpr char RX_UUID[] = "7c2e0002-5d2b-4fd0-b1c2-0cc8f5470101";
constexpr char TX_UUID[] = "7c2e0003-5d2b-4fd0-b1c2-0cc8f5470101";
constexpr char LIVE_UUID[] = "7c2e0004-5d2b-4fd0-b1c2-0cc8f5470101";

class BleApiBridgeUsermod : public Usermod, private NimBLEServerCallbacks, private NimBLECharacteristicCallbacks {
public:
  void setup() override;
  void loop() override;
  void addToJsonInfo(JsonObject& root) override;
  void addToJsonState(JsonObject& root) override;
  void readFromJsonState(JsonObject&) override {}
  void addToConfig(JsonObject& root) override;
  void appendConfigData() override;
  bool readFromConfig(JsonObject& root) override;
  void onStateChange(uint8_t mode) override;
  uint16_t getId() override { return USERMOD_ID_BLE_API_BRIDGE; }

private:
  enum class EventType : uint8_t { Connected, Disconnected, Authenticated, Subscribed, Write, Confirmed };
  struct Event {
    EventType type;
    uint16_t connection;
    uint16_t handle;
    int status;
    uint16_t size;
    uint8_t data[MAX_RESPONSE_CHUNK];
  };
  FrameAssembly _request;
  struct ResponseState {
    String payload;
    size_t offset = 0;
    NimBLECharacteristic* characteristic = nullptr;
    bool active = false;
    bool firstChunk = true;
    bool awaitingConfirmation = false;
    uint32_t sentAt = 0;
  } _response;

  struct Config {
    bool enabled = true;
    uint16_t maxRequestBytes = DEFAULT_MAX_REQUEST_BYTES;
    char name[30] = {};
    uint32_t passkey = 0;
  } _config;
  SemaphoreHandle_t _configMutex = nullptr;
  std::atomic<bool> _configChanged{false};
  std::atomic<bool> _stateChanged{false};
  bool copyConfig(Config& config);
  bool storeConfig(const Config& config);
  void applyConfig();
  QueueHandle_t _events = nullptr;
  std::atomic<bool> _queueOverflow{false};
  std::atomic<bool> _acceptConnections{false};
  std::atomic<uint32_t> _passkey{0};
  std::atomic<uint16_t> _callbackConnHandle{BLE_HS_CONN_HANDLE_NONE};
  bool _enabled = true;
  bool _setupDone = false;
  std::atomic<bool> _bleInitialized{false};
  std::atomic<bool> _bleConnected{false};
  bool _secure = false;
  bool _indicationsEnabled = false;
  std::atomic<bool> _liveUpdatesEnabled{false};
  bool _livePushPending = false;
  bool _restartBlePending = false;
  uint16_t _maxRequestBytes = DEFAULT_MAX_REQUEST_BYTES;
  uint16_t _activeConnHandle = BLE_HS_CONN_HANDLE_NONE;
  uint32_t _livePushDueAt = 0;
  uint32_t _connectedAt = 0;
  uint32_t _nextAdvertiseAt = 0;
  String _deviceName;
  std::unique_ptr<uint8_t[]> _requestBuffer;
  NimBLEServer* _server = nullptr;
  NimBLECharacteristic* _rx = nullptr;
  NimBLECharacteristic* _tx = nullptr;
  NimBLECharacteristic* _live = nullptr;

  void onConnect(NimBLEServer*, NimBLEConnInfo& info) override;
  void onDisconnect(NimBLEServer*, NimBLEConnInfo& info, int reason) override;
  void onAuthenticationComplete(NimBLEConnInfo& info) override;
  void onWrite(NimBLECharacteristic* characteristic, NimBLEConnInfo& info) override;
  void onSubscribe(NimBLECharacteristic* characteristic, NimBLEConnInfo& info, uint16_t value) override;
  void onStatus(NimBLECharacteristic* characteristic, NimBLEConnInfo& info, int status) override;
  uint32_t onPassKeyDisplay() override { return _passkey.load(); }
  void onConfirmPassKey(NimBLEConnInfo& info, uint32_t) override { NimBLEDevice::injectConfirmPasskey(info, false); }
  void enqueue(const Event& event);
  void handleEvents();
  void resetConnection();
  void failConnection(const char* message);
  void setLastError(const String& error);
  void clearRequestAssembly();
  void clearResponse();
  void syncDeviceName();
  bool initBleStack();
  bool startAdvertising();
  void stopBle();
  void refreshBleConfiguration();
  String buildSuccessEnvelope() const;
  String buildErrorEnvelope(uint16_t status, const String& message) const;
  bool queueResponse(uint16_t status, const char* contentType, const String& body);
  bool queueErrorResponse(uint16_t status, const String& message);
  bool queueLiveStatePush();
  bool buildJsonBody(const String& path, String& body);
  String normalizePath(const String& rawPath) const;
  bool dispatchGet(const String& rawPath);
  bool dispatchPostJsonState(const String& bodyText);
  bool dispatchPostJsonConfig(const String& bodyText);
  bool dispatchPost(const String& rawPath, const String& bodyText);
  bool processRequestText(const String& requestText);
  void processBleRequest();
  void sendNextResponseChunk();
  bool processWriteChunk(const uint8_t* data, size_t len);
};
} // namespace ble_api_bridge
// AI: end
