#include "ble_api_bridge.h"
#include "settings_form.h"
#include "persistence_status.h"
#include <mbedtls/base64.h>
#include <mbedtls/sha256.h>
#include <algorithm>

// AI: below section was generated by an AI
namespace ble_api_bridge {
namespace {
// Print adapter bounds generated settings scripts instead of silently truncating them.
class StringPrinter : public Print {
public:
  String text;
  bool valid = true;
  size_t write(uint8_t byte) override { return write(&byte, 1); }
  size_t write(const uint8_t* bytes, size_t length) override {
    if (!valid || length > 60000 - text.length() || !text.concat(reinterpret_cast<const char*>(bytes), length)) {
      valid = false;
      return 0;
    }
    return length;
  }
};

int hexDigit(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

// Preserve repeated names and their order: usermod forms encode types and values
// using consecutive fields with the same name. A staged body stays on flash.
class BridgeSettingsForm : public WLEDSettingsForm {
  struct Field { String name; size_t offset, length; };
  std::vector<Field> fields;
  const String& text;
  File* file;
  size_t length;
  int at(size_t offset) const {
    if (!file) return static_cast<uint8_t>(text[offset]);
    if (file->position() != offset && !file->seek(offset)) return -1;
    return file->read();
  }
  String decode(size_t offset, size_t count, bool* ok = nullptr) const {
    String value;
    bool valid = count <= 8192 && value.reserve(count + 1);
    for (size_t i = 0; valid && i < count; ++i) {
      int c = at(offset + i);
      if (c == '%') {
        if (i + 2 >= count) { valid = false; break; }
        int a = hexDigit(at(offset + i + 1)), b = hexDigit(at(offset + i + 2));
        if (a < 0 || b < 0) { valid = false; break; }
        c = (a << 4) | b;
        i += 2;
      } else if (c == '+') c = ' ';
      if (c <= 0) { valid = false; break; }
      value += static_cast<char>(c);
    }
    if (ok) *ok = valid;
    return valid ? value : String();
  }
public:
  BridgeSettingsForm(const String& body, File* source) : text(body), file(source), length(source ? source->size() : body.length()) {}
  bool parse() {
    size_t begin = 0;
    while (begin < length) {
      if (fields.size() >= 1024) return false;
      size_t end = begin, equal = length;
      while (end < length) {
        int c = at(end);
        if (c < 0) return false;
        if (c == '&') break;
        if (c == '=' && equal == length) equal = end;
        ++end;
      }
      if (equal >= end || equal - begin > 192) return false;
      bool valid = false;
      String name = decode(begin, equal - begin, &valid);
      if (!valid || name.isEmpty()) return false;
      decode(equal + 1, end - equal - 1, &valid); // reject malformed escapes before any mutation
      if (!valid) return false;
      fields.push_back({name, equal + 1, end - equal - 1});
      begin = end + 1;
    }
    return !fields.empty();
  }
  String arg(const String& name) const override {
    for (const auto& field : fields) if (field.name == name) return decode(field.offset, field.length);
    return String();
  }
  String arg(size_t index) const override { return index < fields.size() ? decode(fields[index].offset, fields[index].length) : String(); }
  String argName(size_t index) const override { return index < fields.size() ? fields[index].name : String(); }
  size_t args() const override { return fields.size(); }
  bool hasArg(const String& name) const override {
    for (const auto& field : fields) if (field.name == name) return true;
    return false;
  }
};

byte settingsPage(const String& path) {
  const char* routes[] = {"", "/settings/wifi", "/settings/leds", "/settings/ui", "/settings/sync", "/settings/time", "/settings/sec", "/settings/dmx", "/settings/um", "", "/settings/2D"};
  for (byte i = 1; i <= 10; ++i) if (path == routes[i]) return i;
  return 0;
}
} // namespace

bool BleApiBridgeUsermod::settingsAuthorized() const {
  return !settingsPIN[0] || strncmp(settingsPIN, _authorizedPIN, sizeof(_authorizedPIN)) == 0;
}

bool BleApiBridgeUsermod::configurationWillDisconnect(bool& enabled) {
  enabled = _enabled;
  if (!_configChanged.load()) return false;
  Config config;
  if (!copyConfig(config)) return true; // conservative while the snapshot is busy
  enabled = config.enabled;
  String name = config.name;
  if (name.isEmpty()) name = String(F("WLED-")) + escapedMac.substring(escapedMac.length() > 6 ? escapedMac.length() - 6 : 0);
  return config.enabled != _enabled || config.maxRequestBytes != _maxRequestBytes || name != _deviceName
    || (config.passkey && config.passkey != _passkey.load());
}

size_t BleApiBridgeUsermod::transferChunkSize() const {
  return std::min<size_t>(MAX_TRANSFER_CHUNK, ((_maxRequestBytes - 112) / 4) * 3);
}

bool BleApiBridgeUsermod::queueDocument(const JsonDocument& document, uint16_t status) {
  String body;
  size_t size = measureJson(document);
  if (document.overflowed() || !body.reserve(size + 1) || serializeJson(document, body) != size)
    return queueErrorResponse(503, F("response unavailable"));
  return queueResponse(status, "application/json", body);
}

bool BleApiBridgeUsermod::queueAuthState() {
  StaticJsonDocument<160> doc;
  doc["authorized"] = settingsAuthorized();
  doc["pinRequired"] = settingsPIN[0] != 0;
  doc["success"] = true;
  return queueDocument(doc);
}

bool BleApiBridgeUsermod::queueCapabilities() {
  StaticJsonDocument<1024> doc;
  doc["version"] = 2;
  doc["protocol"] = 1;
  doc["maxChunk"] = transferChunkSize();
  doc["maxRequestSize"] = MAX_STAGED_REQUEST;
  doc["maxFileSize"] = getFsBytesTotal() > 4096 ? getFsBytesTotal() - 4096 : 0;
  doc["maxPathBytes"] = std::min<size_t>(254, _maxRequestBytes - 160);
  doc["maxFrameSize"] = _maxRequestBytes;
  doc["authorized"] = settingsAuthorized();
  doc["pinRequired"] = settingsPIN[0] != 0;
  JsonArray features = doc.createNestedArray("features");
  for (const char* feature : {"settings", "files", "stagedRequests", "palettes", "presets", "live", "ddp", "auth", "saveStatus", "usbPairing"}) features.add(feature);
  return queueDocument(doc);
}

// Reboots requested by a Bluetooth command occur after its final indication is
// confirmed and core persistence finishes. A lost link still honors the command.
void BleApiBridgeUsermod::deferReboot() {
  if (doReboot) { _rebootAfterResponse = true; doReboot = false; }
}

void BleApiBridgeUsermod::serviceBridgeOperations() {
  if (!_transfer.id.isEmpty() && uint32_t(millis() - _transfer.touched) >= TRANSFER_TIMEOUT) cancelTransfer();
  if (_operationResponsePending && !configNeedsWrite && !doInitBusses && !presetNeedsSaving() && !_response.active) {
    _operationResponsePending = false;
    if ((_replyConfig && (configWriteGeneration() == _configBefore || !configWriteSucceeded()))
        || (_replyPresets && (presetWriteGeneration() == _presetsBefore || !presetWriteSucceeded()))) {
      _rebootAfterResponse = false;
      if (_bleConnected && _replyAttached) queueErrorResponse(507, F("changes could not be saved"));
    } else if (_bleConnected && _replyAttached && _replyVerbose) {
      String body;
      if (!buildJsonBody(F("/json/si"), body) || !body.reserve(body.length() + 80)) queueErrorResponse(503, F("state unavailable after save"));
      else {
        body.remove(body.length() - 1);
        body += F(",\"saved\":true,\"success\":true,\"reboot\":");
        body += _rebootAfterResponse ? F("true}") : F("false}");
        queueResponse(200, "application/json", body);
      }
    } else if (_bleConnected && _replyAttached) {
      StaticJsonDocument<320> doc;
      doc["success"] = true;
      doc["saved"] = _replyConfig || _replyPresets;
      doc["reboot"] = _rebootAfterResponse;
      bool enabled;
      doc["reconnect"] = configurationWillDisconnect(enabled);
      doc["bluetoothEnabled"] = enabled;
      queueDocument(doc);
    }
  }
  if (_rebootAfterResponse && !_operationResponsePending && !_response.active && !configNeedsWrite && !doInitBusses) {
    _rebootAfterResponse = false;
    doReboot = true;
  }
}

bool BleApiBridgeUsermod::queuePersistenceReply(bool configuration, bool presets, bool verbose) {
  _replyConfig = configuration;
  _replyPresets = presets;
  _replyVerbose = verbose;
  _replyAttached = _bleConnected;
  _operationResponsePending = true;
  deferReboot();
  return true;
}

void BleApiBridgeUsermod::resetBridgeSession() {
  memset(_authorizedPIN, 0, sizeof(_authorizedPIN));
  cancelTransfer();
  _replyAttached = false; // never deliver an old receipt to a new connection
  // A disconnected save still has to finish and suppress reboot on failure.
  // Retain failure cooldown across reconnects; otherwise reconnect defeats it.
}

bool BleApiBridgeUsermod::dispatchSettings(const String& path, const String& body, File* staged) {
  if (!settingsAuthorized()) return queueErrorResponse(401, F("settings PIN required"));
  byte page = settingsPage(path);
  if (!page) return queueErrorResponse(404, F("unknown settings page"));
  if (page == SUBPAGE_WIFI && wifiLock && otaLock) return queueErrorResponse(401, F("Wi-Fi settings are locked"));
  BridgeSettingsForm form(body, staged);
  if (!form.parse()) return queueErrorResponse(400, F("invalid settings form"));
  _configBefore = configWriteGeneration();
  const SettingsFormResult result = applySettingsForm(form, page);
  deferReboot();
  if (result == SettingsFormResult::Busy) return queueErrorResponse(503, F("settings are busy"));
  if (result == SettingsFormResult::Invalid) return queueErrorResponse(400, F("invalid settings page"));
  if (result == SettingsFormResult::StorageFailure) return queueErrorResponse(507, F("settings storage failed"));
  return queuePersistenceReply(result != SettingsFormResult::Reset, false);
}

bool BleApiBridgeUsermod::dispatchSettingsScript(const String& path) {
  int query = path.indexOf("?p=");
  if (query < 0) return queueErrorResponse(400, F("missing settings page"));
  String number = path.substring(query + 3);
  int ampersand = number.indexOf('&');
  if (ampersand >= 0) number.remove(ampersand);
  if (number.isEmpty()) return queueErrorResponse(400, F("invalid settings page"));
  for (size_t i = 0; i < number.length(); ++i) if (!isDigit(number[i])) return queueErrorResponse(400, F("invalid settings page"));
  unsigned page = number.toInt();
  if (page > SUBPAGE_LAST) return queueErrorResponse(404, F("settings page unavailable"));
  if (page && !settingsAuthorized()) return queueErrorResponse(401, F("settings PIN required"));
  StringPrinter output;
  output.print(F("function GetV(){var d=document;"));
  getSettingsJS(page, output);
  output.print('}');
  if (!output.valid) return queueErrorResponse(503, F("settings script unavailable"));
  return queueResponse(200, "application/javascript", output.text);
}

bool BleApiBridgeUsermod::dispatchLegacy(const String& path) {
  handleSet(nullptr, path, true);
  deferReboot();
  StringPrinter output;
  XML_response(output);
  if (!output.valid) return queueErrorResponse(503, F("state unavailable"));
  return queueResponse(200, "text/xml", output.text);
}

bool BleApiBridgeUsermod::dispatchBridge(const String& path, const String& body) {
  if (path == F("/ble/fs")) return dispatchTransfer(body, false);
  if (path == F("/ble/request")) return dispatchTransfer(body, true);
  if (path == F("/ble/presets")) return dispatchPresets(body);
  if (path == F("/ble/ddp")) return dispatchDDP(body);
  if (path != F("/ble/auth")) return queueErrorResponse(404, F("unknown Bluetooth operation"));
  StaticJsonDocument<256> doc;
  if (deserializeJson(doc, body) || !doc.is<JsonObject>()) return queueErrorResponse(400, F("invalid authentication request"));
  if (doc["lock"] | false) {
    memset(_authorizedPIN, 0, sizeof(_authorizedPIN));
    cancelTransfer();
    return queueAuthState();
  }
  if (_hasPINFailure && uint32_t(millis() - _lastPINFailure) < PIN_RETRY_COOLDOWN)
    return queueErrorResponse(429, F("wait before trying the PIN again"));
  const char* pin = doc["pin"] | "";
  if (settingsPIN[0] && (strnlen(pin, 5) != 4 || strncmp(pin, settingsPIN, 5) != 0)) {
    _hasPINFailure = true;
    _lastPINFailure = millis();
    memset(_authorizedPIN, 0, sizeof(_authorizedPIN));
    return queueErrorResponse(401, F("incorrect settings PIN"));
  }
  strlcpy(_authorizedPIN, settingsPIN, sizeof(_authorizedPIN));
  return queueAuthState();
}

// Rename the stored object without applying it or replacing its effect/playlist.
bool BleApiBridgeUsermod::dispatchPresets(const String& body) {
  StaticJsonDocument<512> input;
  if (deserializeJson(input, body) || !input.is<JsonObject>()) return queueErrorResponse(400, F("invalid preset request"));
  const char* operation = input["op"] | "";
  unsigned id = input["id"] | 0U;
  const char* name = input["name"] | "";
  if (strcmp(operation, "rename") || id < 1 || id > 250 || !name[0] || strnlen(name, 33) > 32)
    return queueErrorResponse(400, F("invalid preset name or ID"));
  if (presetNeedsSaving()) return queueErrorResponse(409, F("preset save in progress"));
  JSONBufferGuard guard(JSON_LOCK_UNKNOWN);
  if (!guard) return queueErrorResponse(503, F("presets are busy"));
  pDoc->clear();
  if (!readObjectFromFileUsingId(getPresetsFileName(), id, pDoc) || !pDoc->is<JsonObject>()) return queueErrorResponse(404, F("preset not found"));
  (*pDoc)["n"] = name;
  bool saved = !pDoc->overflowed() && writeObjectToFileUsingId(getPresetsFileName(), id, pDoc);
  if (doCloseFile) closeFile();
  if (!saved) return queueErrorResponse(507, F("preset could not be saved"));
  presetsModifiedTime = toki.second();
  cacheInvalidate++;
  updateFSInfo();
  return queueResponse(200, "application/json", F("{\"success\":true,\"saved\":true}"));
}
} // namespace ble_api_bridge
// AI: end
