#include "ble_api_bridge.h"
namespace ble_api_bridge {
static BleApiBridgeUsermod ble_api_bridge;
REGISTER_USERMOD(ble_api_bridge);
}
// AI: below section was generated by an AI
// Only the physical serial command calls this hook; radio APIs never publish the code.
uint32_t wledBluetoothPairingCode() { return ble_api_bridge::ble_api_bridge.pairingCode(); }
// AI: end
