#pragma once
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// AI: below section was generated by an AI
namespace ble_api_bridge {
constexpr size_t MAX_TRANSFER_CHUNK = 1024;
constexpr size_t MAX_STAGED_REQUEST = 32768;
constexpr uint32_t TRANSFER_TIMEOUT = 60000;
constexpr char TRANSFER_FILE[] = "/.ble-transfer";

// Restrict file operations to canonical absolute paths and keep secrets/internal
// staging files out of both the file browser and direct read/write operations.
inline bool validFilePath(const char* path) {
  if (!path || path[0] != '/') return false;
  const size_t length = strnlen(path, 256);
  if (length < 2 || length > 254 || path[length - 1] == '/') return false;
  if (!strcmp(path, "/cfg.json.tmp") || !strcmp(path, "/presets.json.tmp") || !strcmp(path, "/tmp.json.tmp")) return false;
  if (strstr(path, "..") || strstr(path, "//") || strstr(path, "/.") || strchr(path, '%')) return false;
  for (size_t i = 0; i < length; ++i) {
    const uint8_t c = static_cast<uint8_t>(path[i]);
    if (c < 32 || c == 127 || c == '\\' || c == '?' || c == '#') return false;
  }
  // Case-insensitive secret exclusion also protects backup-like names.
  const char needle[] = "wsec";
  for (size_t i = 0; i + 4 <= length; ++i) {
    size_t j = 0;
    for (; j < 4; ++j) {
      char c = path[i + j];
      if (c >= 'A' && c <= 'Z') c += 'a' - 'A';
      if (c != needle[j]) break;
    }
    if (j == 4) return false;
  }
  return true;
}

inline bool validDigest(const char* text) {
  if (!text || strnlen(text, 65) != 64) return false;
  for (size_t i = 0; i < 64; ++i)
    if (!((text[i] >= '0' && text[i] <= '9') || (text[i] >= 'a' && text[i] <= 'f'))) return false;
  return true;
}

// All write chunks must be contiguous; subtraction prevents offset overflow.
inline bool validTransferRange(size_t offset, size_t count, size_t expectedOffset, size_t total) {
  return offset == expectedOffset && offset <= total && count <= total - offset && count <= MAX_TRANSFER_CHUNK;
}

inline int base64Value(char c) {
  if (c >= 'A' && c <= 'Z') return c - 'A';
  if (c >= 'a' && c <= 'z') return c - 'a' + 26;
  if (c >= '0' && c <= '9') return c - '0' + 52;
  if (c == '+') return 62;
  if (c == '/') return 63;
  return -1;
}

// RFC 4648 canonical base64: no whitespace, misplaced padding, or nonzero pad
// bits. Validate each quartet before writing, with an explicit destination cap.
inline bool decodeBase64(const char* text, uint8_t* output, size_t capacity, size_t& written) {
  written = 0;
  if (!text || !output) return false;
  const size_t limit = 4 * ((capacity + 2) / 3);
  const size_t length = strnlen(text, limit + 1);
  if (length > limit || length % 4) return false;
  for (size_t i = 0; i < length; i += 4) {
    int a = base64Value(text[i]), b = base64Value(text[i+1]);
    int c = base64Value(text[i+2]), d = base64Value(text[i+3]);
    bool pad2 = text[i+2] == '=', pad1 = text[i+3] == '=';
    if (a < 0 || b < 0 || (!pad2 && c < 0) || (!pad1 && d < 0)
        || (pad2 && !pad1) || ((pad1 || pad2) && i + 4 != length)
        || (pad2 && (b & 15)) || (!pad2 && pad1 && (c & 3))) return false;
    size_t count = pad2 ? 1 : (pad1 ? 2 : 3);
    if (count > capacity - written) return false;
    output[written++] = (a << 2) | (b >> 4);
    if (count > 1) output[written++] = (b << 4) | (c >> 2);
    if (count > 2) output[written++] = (c << 6) | d;
  }
  return true;
}
} // namespace ble_api_bridge
// AI: end
