#!/usr/bin/env python3
"""Reusable protocol-1 client and CLI; install requirements-client.txt first.

The byte contract is documented in README.md. Bleak owns platform pairing and
ATT operations: https://bleak.readthedocs.io/en/latest/api/client.html
"""
from __future__ import annotations

# AI: below section was generated by an AI
import argparse
import asyncio
from dataclasses import dataclass
import json
import math
import sys
from typing import Any

from bleak import BleakClient, BleakScanner

SERVICE_UUID = "7c2e0001-5d2b-4fd0-b1c2-0cc8f5470101"
RX_UUID = "7c2e0002-5d2b-4fd0-b1c2-0cc8f5470101"
TX_UUID = "7c2e0003-5d2b-4fd0-b1c2-0cc8f5470101"
LIVE_UUID = "7c2e0004-5d2b-4fd0-b1c2-0cc8f5470101"


@dataclass(frozen=True)
class BridgeResponse:
    status: int
    content_type: str
    body: str

    def json(self) -> Any:
        """Decode a complete response, preserving the original body for diagnostics."""
        return json.loads(self.body)


class BridgeHTTPError(RuntimeError):
    """A valid protocol response with a non-success status (not a broken stream)."""

    def __init__(self, response: BridgeResponse):
        self.response = response
        super().__init__(f"WLED returned status {response.status}")


class PairingProbeTimeout(TimeoutError):
    """The protected read did not finish; pairing is not established by a connection alone."""


class FrameAssembler:
    """Assemble one length-prefixed frame without decoding partial UTF-8 bytes."""

    def __init__(self, max_bytes: int = 65535):
        self.max_bytes = max_bytes
        self.reset()

    def reset(self) -> None:
        """Discard all bytes when starting a new frame or connection."""
        self.expected: int | None = None
        self.buffer = bytearray()

    def append(self, data: bytes | bytearray) -> bytes | None:
        """Return a complete payload; invalid or excess bytes fail closed."""
        if not data:
            raise ValueError("empty BLE frame packet")
        if self.expected is None:
            if len(data) < 2:
                raise ValueError("missing BLE frame length")
            self.expected = int.from_bytes(data[:2], "little")
            if not 1 <= self.expected <= self.max_bytes:
                raise ValueError("invalid BLE frame length")
            self.buffer.extend(data[2:])
        else:
            self.buffer.extend(data)
        if len(self.buffer) > self.expected:
            raise ValueError("BLE frame exceeds declared length")
        if len(self.buffer) == self.expected:
            payload = bytes(self.buffer)
            self.reset()
            return payload
        return None


class BleApiBridgeClient:
    """One authenticated WLED connection, with serialized commands and LIVE data.

    A command timeout includes queueing. Ambiguous command failures close the
    connection; callers explicitly reconnect before retrying. Complete LIVE
    updates use a bounded latest-state queue, dropping oldest updates if full.
    """

    def __init__(self, address: str, chunk_size: int = 244, timeout: float = 120,
                 *, connect_timeout: float = 90, disconnect_timeout: float = 5,
                 live_queue_size: int = 16, frame_timeout: float = 10,
                 commission: bool = False):
        if not isinstance(chunk_size, int) or not 3 <= chunk_size <= 244:
            raise ValueError("chunk size must be between 3 and 244")
        for name, value in (("timeout", timeout), ("connect_timeout", connect_timeout),
                            ("disconnect_timeout", disconnect_timeout), ("frame_timeout", frame_timeout)):
            if not math.isfinite(value) or value <= 0:
                raise ValueError(f"{name} must be positive and finite")
        if not isinstance(live_queue_size, int) or live_queue_size < 1:
            raise ValueError("live_queue_size must be positive")
        if commission and (sys.platform != "darwin" or connect_timeout > 110):
            raise ValueError("commissioning requires macOS and connect_timeout at most 110 seconds")
        self.address = address
        self.chunk_size = chunk_size
        self.timeout = timeout
        self.connect_timeout = connect_timeout
        self.disconnect_timeout = disconnect_timeout
        self.frame_timeout = frame_timeout
        self.commission = commission
        self.max_request_bytes = 4096
        self.live_dropped = 0
        self._generation = 0
        self._ready = False
        self._subscribed = False
        self._live_receiver_ready = False
        self._delivery_generation = 0
        self._rx = None
        self._response: asyncio.Future[BridgeResponse] | None = None
        self._tx_frame = FrameAssembler()
        self._live_frame = FrameAssembler()
        self._live_queue: asyncio.Queue[dict] = asyncio.Queue(live_queue_size)
        self._live_event = asyncio.Event()
        self._live_error: BaseException | None = None
        self._live_timer: asyncio.TimerHandle | None = None
        self._request_lock = asyncio.Lock()
        self._lifecycle_lock = asyncio.Lock()
        self._abort_task: asyncio.Task | None = None
        self.client = self._make_client()

    def _make_client(self):
        """Bind callbacks to a generation so an old link cannot satisfy a new request."""
        generation = self._generation
        options = {}
        if self.commission:
            from macos_commissioning import commissioning_backend
            options["backend"] = commissioning_backend()
        return BleakClient(self.address, services=[SERVICE_UUID], timeout=self.connect_timeout,
                           disconnected_callback=lambda client: self._disconnected(client, generation), **options)

    @property
    def is_connected(self) -> bool:
        return self._ready and self.client.is_connected

    @property
    def write_budget(self) -> int:
        """Current safe ATT chunk budget; Bleak may initially report a conservative 20."""
        if self._rx is None:
            raise ConnectionError("WLED is not ready")
        budget = min(244, self.chunk_size, self._rx.max_write_without_response_size)
        if budget < 3:
            raise ValueError("invalid ATT write budget")
        return budget

    async def __aenter__(self):
        await self.connect()
        return self

    async def __aexit__(self, exc_type, exc, traceback):
        # Do not replace a command failure with a secondary cleanup failure.
        async with self._lifecycle_lock:
            await self._close(suppress_errors=exc is not None)

    def _characteristic(self, uuid: str, required: set[str]):
        """Validate properties and service membership before treating a peer as WLED."""
        characteristic = self.client.services.get_characteristic(uuid)
        if characteristic is None or characteristic.service_uuid.lower() != SERVICE_UUID:
            raise ValueError(f"WLED characteristic missing: {uuid}")
        if not required.issubset(characteristic.properties):
            raise ValueError(f"WLED characteristic properties incompatible: {uuid}")
        return characteristic

    async def connect(self, pair: bool = False, *, live: bool = False) -> None:
        """Arm both streams before commands; optionally request the initial LIVE snapshot."""
        async with self._lifecycle_lock:
            await self._connect_setup(pair)
            generation = self._generation
            if live:
                self._subscribed = True
        # Requests can close a failed connection, which takes the lifecycle lock.
        # Keep this read-only readiness handshake outside that lock.
        if live:
            await self._live_handshake(generation)

    async def _connect_setup(self, pair: bool) -> None:
        """Install physical receivers under the caller's lifecycle lock, without writing RX."""
        if self.is_connected:
            return
        await self._close(suppress_errors=False)
        self._generation += 1
        generation = self._generation
        self.client = self._make_client()
        self._live_error = None
        self.max_request_bytes = 4096
        phase = "connection"
        try:
            async with asyncio.timeout(self.connect_timeout):
                await self.client.connect()
                if pair and sys.platform != "darwin":
                    await self.client.pair()
                self._rx = self._characteristic(RX_UUID, {"write"})
                self._characteristic(TX_UUID, {"read", "indicate"})
                self._characteristic(LIVE_UUID, {"read", "indicate"})
                # macOS owns pairing; reading this protected value presents its prompt.
                phase = "pairing probe"
                if await self.client.read_gatt_char(TX_UUID) != b"ready":
                    raise ValueError("not a compatible WLED Bluetooth bridge")
                phase = "TX subscription"
                await self.client.start_notify(TX_UUID, lambda char, data: self._on_tx(char, data, generation))
                phase = "LIVE subscription"
                if await self.client.read_gatt_char(LIVE_UUID) != b"live":
                    raise ValueError("invalid WLED LIVE probe")
                # Firmware gates LIVE until the first complete authenticated RX request.
                # A later local subscribe must never attach halfway through a wire frame.
                self._live_receiver_ready = True
                await self.client.start_notify(LIVE_UUID, lambda char, data: self._on_live(char, data, generation))
                if generation != self._generation or not self.client.is_connected or self._live_error is not None:
                    raise self._live_error or ConnectionError("WLED disconnected during setup")
                self._ready = True
        except TimeoutError as error:
            await self._close(suppress_errors=True)
            if phase == "pairing probe" and sys.platform == "darwin":
                detail = ("The commissioning probe allows up to 90 seconds within the total connection deadline."
                          if self.commission else
                          "Stock Bleak 3.0.2 limits this macOS read to 20 seconds, even with a longer connect_timeout. "
                          "Use --commission for a manual pairing window of up to 90 seconds.")
                raise PairingProbeTimeout("Protected WLED pairing probe timed out. Complete the macOS pairing prompt "
                                          "using the device code, then retry explicitly. " + detail) from error
            raise
        except BaseException:
            await self._close(suppress_errors=True)
            raise

    def _invalidate(self, error: BaseException) -> None:
        """Wake command/live consumers immediately, independently of platform cleanup."""
        self._ready = False
        self._subscribed = False
        self._live_receiver_ready = False
        self._delivery_generation += 1
        self._rx = None
        self._tx_frame.reset()
        self._live_frame.reset()
        if self._live_timer is not None:
            self._live_timer.cancel()
            self._live_timer = None
        self._live_error = error
        while not self._live_queue.empty():
            self._live_queue.get_nowait()
        self._live_event.set()
        if self._response is not None and not self._response.done():
            self._response.set_exception(error)

    async def _close(self, *, suppress_errors: bool) -> None:
        """Invalidate first and put a separate bound on a stuck OS disconnect."""
        self._generation += 1
        self._invalidate(self._live_error or ConnectionError("WLED disconnected"))
        try:
            async with asyncio.timeout(self.disconnect_timeout):
                if self.client.is_connected:
                    await self.client.disconnect()
        except Exception:
            if not suppress_errors:
                raise

    async def disconnect(self) -> None:
        """Close the link; timeout is an explicit cleanup failure, not a successful recovery."""
        async with self._lifecycle_lock:
            await self._close(suppress_errors=False)

    def _disconnected(self, _client, generation: int | None = None) -> None:
        if generation is None or generation == self._generation:
            self._invalidate(ConnectionError("WLED disconnected"))

    def _on_tx(self, _characteristic, data: bytearray, generation: int | None = None) -> None:
        if generation is not None and generation != self._generation:
            return
        if self._response is None or self._response.done():
            if self.is_connected:
                self._fail_stream(ValueError("unsolicited TX data"))
            return
        try:
            payload = self._tx_frame.append(data)
            if payload is not None:
                self._response.set_result(self._parse_response(payload))
        except ValueError as error:
            self._response.set_exception(error)

    def _fail_stream(self, error: BaseException) -> None:
        """Schedule bounded cleanup for an invalid asynchronous LIVE/TX stream."""
        generation = self._generation
        self._invalidate(error)

        async def abort():
            async with self._lifecycle_lock:
                if generation == self._generation:
                    await self._close(suppress_errors=True)

        self._abort_task = asyncio.create_task(abort())

    async def _live_handshake(self, generation: int) -> None:
        """Open firmware's readiness gate after receivers exist, without lock inversion."""
        try:
            if generation != self._generation or not self.is_connected:
                raise ConnectionError("WLED disconnected before LIVE readiness handshake")
            await self.refresh_capabilities(_expected_generation=generation)
            if generation != self._generation or not self.is_connected:
                raise ConnectionError("WLED disconnected during LIVE readiness handshake")
        except (ValueError, BridgeHTTPError):
            # request() already quarantines failures after taking its command slot.
            # Do not close another caller's active command if this handshake timed
            # out or was cancelled while queued. Capability validation is ours.
            async with self._lifecycle_lock:
                if generation == self._generation:
                    await self._close(suppress_errors=True)
            raise

    async def subscribe_live(self) -> None:
        """Enable delivery; re-enabling waits for a future update, not a synthetic snapshot."""
        async with self._lifecycle_lock:
            if not self.is_connected or not self._live_receiver_ready:
                raise ConnectionError("WLED is not ready")
            self._subscribed = True
            generation = self._generation
        await self._live_handshake(generation)

    async def unsubscribe_live(self) -> None:
        """Stop local delivery while retaining wire framing and its stall watchdog."""
        async with self._lifecycle_lock:
            self._subscribed = False
            self._delivery_generation += 1
            while not self._live_queue.empty():
                self._live_queue.get_nowait()
            self._live_event.set()

    def _on_live(self, _characteristic, data: bytearray, generation: int | None = None) -> None:
        if generation is not None and generation != self._generation:
            return
        if not self._live_receiver_ready:
            return
        try:
            payload = self._live_frame.append(data)
            if self._live_timer is not None:
                self._live_timer.cancel()
                self._live_timer = None
            if payload is None:
                self._live_timer = asyncio.get_running_loop().call_later(
                    self.frame_timeout, self._fail_stream, TimeoutError("partial LIVE frame stalled"))
                return
            update = json.loads(payload.decode("utf-8"))
            if not isinstance(update, dict) or not isinstance(update.get("state"), dict) or not isinstance(update.get("info"), dict):
                raise ValueError("LIVE update must contain state and info objects")
            if not self._subscribed:
                return
            if self._live_queue.full():
                self._live_queue.get_nowait()
                self.live_dropped += 1
            self._live_queue.put_nowait(update)
            self._live_event.set()
        except ValueError as error:
            self._fail_stream(error)

    async def next_live(self, timeout: float | None = None) -> dict:
        """Wait for the next complete update; disconnect and unsubscribe wake waiters."""
        delivery_generation = self._delivery_generation
        async with asyncio.timeout(self.timeout if timeout is None else timeout):
            while True:
                if self._live_error is not None:
                    raise self._live_error
                if not self._subscribed or delivery_generation != self._delivery_generation:
                    raise ConnectionError("LIVE is not subscribed")
                if not self._live_queue.empty():
                    return self._live_queue.get_nowait()
                self._live_event.clear()
                await self._live_event.wait()

    async def request(self, method: str, path: str, body: str = "", *,
                      _expected_generation: int | None = None) -> BridgeResponse:
        """Send one command; never automatically repeat a possibly applied state write."""
        if not method or any(char.isspace() for char in method) or not path or any(char in path for char in "\r\n\0"):
            raise ValueError("invalid request method or path")
        payload = f"{method.upper()} {path}\n\n{body}".encode("utf-8")
        if len(payload) > self.max_request_bytes:
            raise ValueError(f"request exceeds bridge limit ({self.max_request_bytes} bytes)")
        # Waiting callers can time out without disconnecting the caller holding the lock.
        async with asyncio.timeout(self.timeout):
            async with self._request_lock:
                if _expected_generation is not None and _expected_generation != self._generation:
                    raise ConnectionError("WLED disconnected before LIVE readiness handshake")
                if not self.is_connected:
                    raise ConnectionError("WLED is not ready; connect before requesting")
                # A preceding capabilities request can lower this limit while we wait.
                if len(payload) > self.max_request_bytes:
                    raise ValueError(f"request exceeds bridge limit ({self.max_request_bytes} bytes)")
                budget = self.write_budget
                characteristic = self._rx
                generation = self._generation
                self._tx_frame.reset()
                response = asyncio.get_running_loop().create_future()
                self._response = response
                framed = len(payload).to_bytes(2, "little") + payload
                try:
                    for offset in range(0, len(framed), budget):
                        await self.client.write_gatt_char(characteristic, framed[offset:offset + budget], response=True)
                        if response.done() and (response.cancelled() or response.exception() is not None):
                            return await response
                    result = await response
                    if generation != self._generation or not self.is_connected:
                        raise ConnectionError("WLED disconnected before response delivery")
                    return result
                except BaseException:
                    # Protocol 1 has no request IDs. Quarantine any unfinished response before reuse.
                    if not response.done():
                        response.cancel()
                    elif not response.cancelled():
                        response.exception()
                    async with self._lifecycle_lock:
                        if generation == self._generation:
                            await self._close(suppress_errors=True)
                    raise
                finally:
                    if not response.done():
                        response.cancel()
                    self._response = None

    async def get_json(self, path: str = "/json") -> Any:
        """Read a supported JSON route, raising BridgeHTTPError for error statuses."""
        response = await self.request("GET", path)
        if not 200 <= response.status < 300:
            raise BridgeHTTPError(response)
        return response.json()

    async def post_json(self, path: str, body: dict) -> Any:
        """Write compact UTF-8 JSON without automatically retrying mutations."""
        response = await self.request("POST", path, json.dumps(body, ensure_ascii=False, separators=(",", ":"), allow_nan=False))
        if not 200 <= response.status < 300:
            raise BridgeHTTPError(response)
        return response.json()

    async def refresh_capabilities(self, *, _expected_generation: int | None = None) -> dict:
        """Check protocol/version information and adopt the device's configured request limit."""
        response = await self.request("GET", "/json/info", _expected_generation=_expected_generation)
        if not 200 <= response.status < 300:
            raise BridgeHTTPError(response)
        info = response.json()
        capabilities = info.get("ble") if isinstance(info, dict) else None
        if not isinstance(capabilities, dict) or capabilities.get("protocol") != 1:
            raise ValueError("unsupported WLED BLE protocol")
        limit = capabilities.get("maxRequest")
        if isinstance(limit, bool) or not isinstance(limit, int) or not 256 <= limit <= 4096:
            raise ValueError("invalid WLED request limit")
        if _expected_generation is not None and _expected_generation != self._generation:
            raise ConnectionError("WLED disconnected during LIVE readiness handshake")
        self.max_request_bytes = limit
        return info

    @staticmethod
    def _parse_response(raw: bytes) -> BridgeResponse:
        """Parse the status envelope only after the complete byte frame arrives."""
        header, body = raw.decode("utf-8").split("\n\n", 1)
        status_text, content_type = header.split(" ", 1)
        if len(status_text) != 3 or not status_text.isascii() or not status_text.isdecimal():
            raise ValueError("invalid response status")
        status = int(status_text)
        if not 100 <= status <= 599 or not content_type or any(char in content_type for char in "\r\n\0"):
            raise ValueError("invalid response status or content type")
        return BridgeResponse(status, content_type, body)


async def main() -> None:
    """Keep the original scan/single-request CLI while the class supports longer sessions."""
    parser = argparse.ArgumentParser(description="Control WLED using its encrypted Bluetooth JSON bridge.")
    parser.add_argument("--scan", action="store_true", help="list nearby bridge devices")
    parser.add_argument("--address", help="BLE address, or macOS peripheral UUID from --scan")
    parser.add_argument("--pair", action="store_true", help="explicit pairing on Linux/Windows; macOS pairs automatically")
    parser.add_argument("--chunk-size", type=int, default=244)
    parser.add_argument("--timeout", type=float, default=120)
    parser.add_argument("--connect-timeout", type=float, help="total connection deadline; default 90s, or 110s with --commission")
    parser.add_argument("--commission", action="store_true", help="macOS only: allow up to 90s for manual initial pairing (pinned Bleak adapter)")
    parser.add_argument("method", nargs="?", choices=["get", "post"], default="get")
    parser.add_argument("path", nargs="?", default="/json/info")
    parser.add_argument("body", nargs="?", default="")
    args = parser.parse_args()
    if args.scan:
        for device in await BleakScanner.discover(service_uuids=[SERVICE_UUID]):
            print(f"{device.address}\t{device.name or 'WLED'}")
        return
    if not args.address:
        parser.error("use --scan or provide --address")
    connect_timeout = args.connect_timeout if args.connect_timeout is not None else (110 if args.commission else 90)
    bridge = BleApiBridgeClient(args.address, args.chunk_size, args.timeout,
                               connect_timeout=connect_timeout, commission=args.commission)
    try:
        await bridge.connect(args.pair)
        response = await bridge.request(args.method, args.path, args.body)
        print(f"{response.status} {response.content_type}\n\n{response.body}")
    finally:
        await bridge.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
# AI: end
