#!/usr/bin/env python3
"""Opt-in temporary BLE configuration tests; never changes Bluetooth pairing codes.

--provision-test-pin explicitly provisions a temporary settings PIN only when the
fixture has none. The HTTP security form preserves its original checkbox values
and never submits OTA passwords or factory-reset fields. A mode-0600 recovery
file is saved before writing; cleanup restores BLE configuration, then clears
the test PIN and verifies both transports. The security form persists current
configuration, so provisioning precedes temporary BLE configuration changes.
Removal is refused if the original BLE baseline cannot be restored first.
Readback verifies live state; a separate reboot check must verify persistence.
An existing PIN is never replaced; provide it via --settings-pin-env instead.
"""
# AI: below section was generated by an AI
import argparse
import asyncio
import copy
import json
import os
import re
import secrets
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import client_example as bridge
from hil_runner import CoverageMissing, HilRunner, HttpOracle, check, mac_identity, padded_request_body
from hil_runner import parse_args as base_parse_args

PIN_SETTLE_SECONDS = 3.1  # WLED's PIN_RETRY_COOLDOWN is 3000 ms.


class ConfigHttp(HttpOracle):
    """Redirect-free I/O with socket timeouts and a checked body-read time budget.

    urllib's timeout limits socket inactivity, including header parsing. The body
    budget is checked between read1 calls; one socket read can overrun that budget
    by a socket timeout. Header trickling is not bounded by an overall deadline.
    Cancellation drains the worker before an opposing restoration write.
    """

    async def request(self, method, path, body=None):
        return await self._finish_http(self._request, method, path, body)

    async def settings(self, method, path, fields=None):
        """Access only the public security fixture routes, without logging their bodies."""
        if method == "GET":
            check(path in ("/settings/lock", "/settings/s.js?p=6") and fields is None,
                  "Unexpected security fixture read")
            data = None
        else:
            check(method == "POST" and path == "/settings/sec" and isinstance(fields, dict),
                  "Unexpected security fixture write")
            check("PIN" in fields and set(fields) <= {"PIN", "NO", "OW", "AO", "SU"},
                  "Refusing unrelated security form fields")
            data = urllib.parse.urlencode(fields).encode("ascii")
        status, payload = await self._finish_http(self._exchange, method, path, data,
                                                  "application/x-www-form-urlencoded")
        return status, payload.decode("utf-8")

    async def _finish_http(self, operation, *args):
        """Drain socket I/O before cancellation can begin conflicting restoration."""
        task = asyncio.create_task(asyncio.to_thread(operation, *args))
        try:
            return await asyncio.shield(task)
        except asyncio.CancelledError:
            # Cancelling to_thread does not stop its write. Wait for its socket
            # operations before allowing cleanup to submit an opposite mutation.
            while not task.done():
                try:
                    await asyncio.shield(task)
                except asyncio.CancelledError:
                    continue
                except Exception:
                    break
            if not task.cancelled():
                task.exception()
            raise

    def _request(self, method, path, body):
        check(path in ("/json/cfg", "/json/state"), "Unexpected configuration HTTP route")
        data = None if body is None else json.dumps(body, ensure_ascii=False, allow_nan=False).encode()
        status, payload = self._exchange(method, path, data, "application/json")
        return status, json.loads(payload)

    def _exchange(self, method, path, data, content_type):
        """Use the same redirect-free transport for JSON and form endpoints."""
        class NoRedirect(urllib.request.HTTPRedirectHandler):
            def redirect_request(self, *args, **kwargs):
                return None

        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
        request = urllib.request.Request(self.url + path, data=data, method=method,
                                         headers={"Content-Type": content_type})
        try:
            response = opener.open(request, timeout=self.timeout)
        except urllib.error.HTTPError as error:
            response = error
        with response:
            status = response.code
            deadline = time.monotonic() + self.timeout
            payload = bytearray()
            while len(payload) <= 262144:
                if time.monotonic() >= deadline:
                    raise TimeoutError("Configuration HTTP body read deadline exceeded")
                chunk = response.read1(min(16384, 262145 - len(payload)))
                if not chunk:
                    break
                payload.extend(chunk)
        check(len(payload) <= 262144, "Configuration HTTP response exceeds 256 KiB")
        return status, bytes(payload)


def private_backup(output, value):
    """Create an ignored, owner-only backup without following or replacing existing files."""
    directory = Path(output) / "private-config"
    directory.mkdir(mode=0o700, exist_ok=False)
    os.chmod(directory, 0o700)
    for filename, payload in ((".gitignore", "*\n"),
                              ("configuration.json", json.dumps(value, indent=2, ensure_ascii=False) + "\n")):
        descriptor = os.open(directory / filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w") as stream:
            stream.write(payload)
    return directory / "configuration.json"


def private_pin_recovery(output, value):
    """Persist recovery credentials before mutation, never replacing an earlier recovery file."""
    path = Path(output) / "private-config" / "pin-recovery.json"
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    os.fchmod(descriptor, 0o600)
    with os.fdopen(descriptor, "w") as stream:
        json.dump(value, stream, indent=2)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    return path


class ConfigHilRunner(HilRunner):
    """Restore only touched BLE fields; preserve the core's omitted-linked-remote side effect."""
    fields = ("enabled", "device-name", "max-request-bytes")

    def __init__(self, args, client_factory=None, oracle=None, scanner=None):
        super().__init__(args, client_factory, oracle or ConfigHttp(args.http_url, args.timeout))
        self.scanner = scanner or bridge.BleakScanner.discover
        self.cfg = None
        self.original = None
        self.linked_remotes = None
        self.pin = os.environ.get(args.settings_pin_env, "") if args.settings_pin_env else ""
        self.protected = False
        self.mutated = False
        self.config_identity_verified = False
        self.pin_write_attempted = False
        self.pin_restored = False
        self.original_ota = None
        self.security_checkboxes = None

    async def verified_identities(self, require_ble=True):
        """BLE identity is established before any mutation; recovery rechecks the independent path."""
        await self.oracle_snapshot()
        if require_ble:
            check(mac_identity(await self.request("GET", "/json/info")) == self.identity,
                  "Configuration BLE identity changed")
        else:
            check(self.config_identity_verified, "No prior BLE identity proof for HTTP recovery")

    async def setup_config(self):
        check(self.args.allow_config_tests, "Configuration tests require --allow-config-tests")
        await self.setup()
        await self.verified_identities()
        self.config_identity_verified = True
        response = await self.client.request("GET", "/json/cfg")
        check(response.status in (200, 401), "Unexpected BLE configuration read status")
        self.protected = response.status == 401
        if self.protected:
            if not self.pin:
                raise CoverageMissing("Existing settings PIN requires the configured credential environment variable")
            check(len(self.pin) == 4, "Fixture settings PIN must contain exactly four characters")
            # This authenticates HTTP only. It does not change the PIN, settings, or BLE authorization.
            await self.unlock_http()
            placeholder, _ = await self.security_script()
            check(placeholder == "0000", "Existing settings PIN baseline changed during authentication")
        status, cfg = await self.oracle.request("GET", "/json/cfg")
        check(status == 200 and isinstance(cfg, dict), "Cannot safely back up fixture configuration")
        top = cfg.get("um", {}).get("BleApiBridge", {})
        check(all(field in top for field in self.fields), "Fixture lacks restorable BLE configuration")
        check(type(top["enabled"]) is bool and top["enabled"], "Fixture must initially have BLE enabled")
        check(isinstance(top["device-name"], str), "Fixture name is not restorable")
        check(type(top["max-request-bytes"]) is int and 256 <= top["max-request-bytes"] <= 4096,
              "Fixture request limit is not restorable")
        linked = cfg.get("nw", {}).get("linked_remote")
        check(linked is None or isinstance(linked, (str, list)), "Unknown linked-remote configuration shape")
        private_backup(self.output, cfg)
        self.cfg = copy.deepcopy(cfg)
        self.original = {key: copy.deepcopy(top[key]) for key in self.fields}
        self.linked_remotes = copy.deepcopy(linked if linked is not None else [])
        if self.args.provision_test_pin and not self.protected:
            await self.provision_test_pin()
        return "Both transport identities verified; owner-only full configuration backup created"

    async def security_script(self):
        """Read fixed form assignments without executing device-provided JavaScript."""
        status, script = await self.oracle.settings("GET", "/settings/s.js?p=6")
        check(status == 200, "Security settings readback requires HTTP authentication")
        values = re.findall(r'd\.Sf\.PIN\.value="([^"]*)";', script)
        check(len(values) == 1 and values[0] in ("", "0000"), "Unexpected settings PIN placeholder")
        checkboxes = {}
        for field in ("NO", "OW", "AO", "SU"):
            matches = re.findall(r'd\.Sf\.' + field + r'\.checked=([01]);', script)
            check(len(matches) == 1, "Unknown security checkbox shape")
            checkboxes[field] = matches[0] == "1"
        return values[0], checkboxes

    def security_form(self, pin):
        """Preserve checkbox presence; omission of OP leaves the OTA password untouched."""
        check(self.security_checkboxes is not None, "Missing original security form baseline")
        return {"PIN": pin, **{key: "on" for key, enabled in self.security_checkboxes.items() if enabled}}

    async def unlock_http(self):
        """Prove unlock through settings JS; HTTP GET /json/cfg is public."""
        await self.verified_identities(require_ble=False)
        await asyncio.sleep(PIN_SETTLE_SECONDS)
        status, _ = await self.oracle.request("POST", "/json/state", {"pin": self.pin, "v": True})
        check(status == 200, "HTTP PIN authentication request failed")
        await self.security_script()  # This route, unlike GET /json/cfg, requires the PIN.
        status, cfg = await self.oracle.request("GET", "/json/cfg")
        check(status == 200 and isinstance(cfg, dict), "HTTP configuration readback failed")
        return cfg

    async def provision_test_pin(self):
        """Provision only a verified blank PIN and save a private recovery recipe first."""
        check(self.args.provision_test_pin and not self.protected, "Refusing to replace an existing settings PIN")
        await self.verified_identities()
        check((await self.client.request("GET", "/json/cfg")).status == 200,
              "Fixture is no longer a blank-PIN baseline")
        placeholder, checkboxes = await self.security_script()
        check(placeholder == "", "Refusing to replace a settings PIN")
        ota = self.cfg.get("ota")
        mapping = {"NO": "lock", "OW": "lock-wifi", "SU": "same-subnet"}
        check(isinstance(ota, dict) and all(type(ota.get(key)) is bool for key in mapping.values()),
              "Original OTA security configuration has an unknown shape")
        check("aota" not in ota or type(ota["aota"]) is bool, "Original ArduinoOTA setting has an unknown shape")
        if "aota" in ota:
            mapping["AO"] = "aota"
        check(all(checkboxes[field] == ota[key] for field, key in mapping.items()),
              "Security settings changed while establishing the fixture baseline")
        self.original_ota = copy.deepcopy(ota)
        self.security_checkboxes = checkboxes
        self.pin = str(secrets.randbelow(9000) + 1000)
        private_pin_recovery(self.output, {"device_mac": self.identity, "temporary_pin": self.pin,
                             "original_pin": "", "original_checkboxes": checkboxes,
                             "restore_route": "/settings/sec", "restore_form": self.security_form("")})
        self.pin_write_attempted = True  # Lost reply or cancellation may still leave the PIN installed.
        self.protected = True
        status, _ = await self.oracle.settings("POST", "/settings/sec", self.security_form(self.pin))
        check(status == 200, "Temporary settings PIN form was rejected")
        await asyncio.sleep(PIN_SETTLE_SECONDS)
        check((await self.client.request("GET", "/json/cfg")).status == 401,
              "Temporary settings PIN did not protect BLE configuration reads")
        status, _ = await self.oracle.settings("GET", "/settings/lock")
        check(status == 200, "Could not lock the temporary PIN fixture")
        status, _ = await self.oracle.settings("GET", "/settings/s.js?p=6")
        check(status == 401, "Temporary settings PIN did not protect HTTP settings JavaScript")
        cfg = await self.unlock_http()
        check(cfg.get("ota") == self.original_ota, "Security flags changed while provisioning the test PIN")
        placeholder, actual = await self.security_script()
        check(placeholder == "0000" and actual == self.security_checkboxes,
              "Temporary security fixture readback did not match")

    async def restore_test_pin(self):
        """Clear only this run's temporary PIN, including after a lost provisioning reply."""
        if not self.pin_write_attempted:
            return "No test PIN was provisioned; existing credentials were untouched"
        cfg = await self.unlock_http()
        check(cfg.get("ota") == self.original_ota, "Security flags changed before test PIN restoration")
        # The security form persists the entire current configuration. Its save
        # must never capture temporary BLE fields after a failed restoration case.
        if not self.original_config_matches(cfg):
            try:
                await self.http_config(self.original)
                status, cfg = await self.oracle.request("GET", "/json/cfg")
            except Exception:
                raise AssertionError("Original BLE baseline unavailable; retaining test PIN and private recovery credentials") from None
            check(status == 200 and self.original_config_matches(cfg),
                  "Original BLE baseline unavailable; retaining test PIN and private recovery credentials")
            check(cfg.get("ota") == self.original_ota, "Security flags changed during fallback configuration restoration")
        status, _ = await self.oracle.settings("POST", "/settings/sec", self.security_form(""))
        check(status == 200, "Test settings PIN removal was rejected")
        await asyncio.sleep(PIN_SETTLE_SECONDS)
        status, _ = await self.oracle.settings("GET", "/settings/lock")
        check(status == 200, "Could not verify the restored settings lock state")
        status, cfg = await self.oracle.request("GET", "/json/cfg")
        check(status == 200 and cfg.get("ota") == self.original_ota,
              "Blank-PIN restoration changed HTTP access or security flags")
        placeholder, actual = await self.security_script()
        check(placeholder == "" and actual == self.security_checkboxes,
              "Settings PIN or checkbox baseline was not restored")
        self.protected = False
        await self.reconnect_verified()
        check((await self.client.request("GET", "/json/cfg")).status == 200,
              "BLE configuration remains protected after test PIN removal")
        self.pin_restored = True
        return "Original blank PIN and security checkboxes restored in live HTTP/BLE state; reboot persistence unverified"

    def original_config_matches(self, cfg):
        """Compare only the fields this harness touches before a full-config save."""
        actual = cfg.get("um", {}).get("BleApiBridge", {})
        return (all(actual.get(key) == value for key, value in self.original.items()) and
                cfg.get("nw", {}).get("linked_remote", []) == self.linked_remotes)

    def payload(self, fields, *, pin=True):
        check(set(fields) <= set(self.fields), "Refusing unrelated configuration mutation")
        result = {"sv": False, "um": {"BleApiBridge": fields},
                  "nw": {"linked_remote": copy.deepcopy(self.linked_remotes)}}
        if pin and self.protected:
            result["pin"] = self.pin
        return result

    async def http_config(self, fields):
        await self.verified_identities(require_ble=False)
        self.mutated = True  # A lost acknowledgement cannot establish that no write occurred.
        status, value = await self.oracle.request("POST", "/json/cfg", self.payload(fields))
        check(status == 200 and value.get("success") is True, "HTTP configuration write failed")

    async def config_readback(self, expected):
        status, value = await self.oracle.request("GET", "/json/cfg")
        check(status == 200, "Configuration readback failed")
        actual = value.get("um", {}).get("BleApiBridge", {})
        check(all(actual.get(key) == expected_value for key, expected_value in expected.items()),
              "Temporary BLE configuration did not match readback")
        check(value.get("nw", {}).get("linked_remote", []) == self.linked_remotes,
              "Linked remotes changed during configuration tests")

    async def wait_disconnected(self, client):
        deadline = time.monotonic() + 10
        while client.client.is_connected and time.monotonic() < deadline:
            await asyncio.sleep(0.1)
        check(not client.client.is_connected, "Runtime configuration did not disconnect the old BLE link")

    async def ble_config_restart(self, fields):
        await self.verified_identities()
        payload = json.dumps(self.payload(fields), ensure_ascii=False, separators=(",", ":"))
        if len(("POST /json/cfg\n\n" + payload).encode()) > self.max_request:
            raise CoverageMissing("Preserving the fixture's linked remotes exceeds its current BLE request limit")
        old_client = self.client
        self.mutated = True
        value = await self.request("POST", "/json/cfg", payload)
        check(value.get("success") is True, "Configuration response did not complete before restart")
        await self.wait_disconnected(old_client)

    async def reconnect_verified(self):
        await self.connect()
        info = await self.request("GET", "/json/info")
        check(mac_identity(info) == self.identity, "Reconnect found a different BLE device")
        self.max_request = info["ble"]["maxRequest"]
        self.client.max_request_bytes = self.max_request
        await self.verified_identities()
        await self.sample()

    async def advertised_name(self, expected):
        found = await self.scanner(timeout=6, return_adv=True, service_uuids=[bridge.SERVICE_UUID])
        names = [advertisement.local_name for device, advertisement in found.values()
                 if device.address.lower() == self.args.address.lower()]
        check(expected in names, "Fresh advertising scan did not contain the expected UTF-8 device name")

    async def names(self):
        first = "HIL-a-" + self.identity[-6:]
        if first == self.original["device-name"]:
            first = "HIL-b-" + self.identity[-6:]
        for supplied, expected in ((first, first),
                                   ("x" * 27 + "é", "x" * 27 + "é"),
                                   ("x" * 28 + "é", "x" * 28),
                                   ("x" * 26 + "😀", "x" * 26)):
            await self.ble_config_restart({"device-name": supplied})
            await self.advertised_name(expected)
            await self.reconnect_verified()
            await self.config_readback({"device-name": expected})
        return "Four fresh advertising scans and reconnects, including UTF-8 truncation boundaries"

    async def request_limits(self):
        # Restore 4096 through HTTP if the fixture already starts at the lower boundary.
        if self.max_request == 256:
            await self.http_config({"max-request-bytes": 4096})
            await self.wait_disconnected(self.client)
            await self.reconnect_verified()
        await self.ble_config_restart({"max-request-bytes": 256})
        await self.reconnect_verified()
        check(self.max_request == 256, "Firmware did not advertise the new request limit")
        await self.config_readback({"max-request-bytes": 256})
        await self.request("POST", "/json/state", padded_request_body(256))
        await self.framing_fault([(257).to_bytes(2, "little")])
        await self.http_config({"max-request-bytes": 4096})
        await self.wait_disconnected(self.client)
        await self.reconnect_verified()
        check(self.max_request == 4096, "Runtime request limit did not return to 4096")
        return "256-byte request accepted; 257-byte frame rejected by firmware; runtime restore verified"

    async def enable_disable(self):
        await self.ble_config_restart({"enabled": False})
        snapshot = await self.oracle_snapshot()
        check(snapshot["state"].get("BleApiBridge", {}).get("enabled") is False,
              "Disabled BLE still reports accepting connections")
        await self.config_readback({"enabled": False})
        await self.http_config({"enabled": True})
        deadline = time.monotonic() + 10
        while True:
            snapshot = await self.oracle_snapshot()
            if snapshot["state"].get("BleApiBridge", {}).get("enabled") is True:
                break
            check(time.monotonic() < deadline, "HTTP re-enable did not start the BLE service")
            await asyncio.sleep(0.1)
        await self.reconnect_verified()
        await self.config_readback({"enabled": True})
        return "BLE acknowledged disable before disconnect; HTTP re-enabled BLE without reboot"

    async def settings_pin(self):
        if not self.protected:
            raise CoverageMissing("Fixture has no settings PIN; use --provision-test-pin to enable reversible PIN coverage")
        await self.verified_identities()
        await self.request("GET", "/json/cfg", expected=401)
        current = (await self.oracle.request("GET", "/json/cfg"))[1]["um"]["BleApiBridge"]
        fields = {key: current[key] for key in self.fields}
        base = self.payload(fields, pin=False)
        wrong = "1111" if self.pin != "1111" else "2222"
        # Numeric input must carry the correct digits: wrong digits would also
        # be rejected by a broken implementation that silently coerces numbers.
        numeric_pin = int(self.pin) if self.pin.isascii() and self.pin.isdigit() else None
        numeric_type_test = numeric_pin is not None and str(numeric_pin) == self.pin
        attempts = [None, wrong] + ([numeric_pin] if numeric_type_test else [])
        for value in attempts:
            payload = copy.deepcopy(base)
            if value is not None:
                payload["pin"] = value
            self.mutated = True
            await self.request("POST", "/json/cfg", json.dumps(payload), expected=401)
        value = await self.request("POST", "/json/cfg", json.dumps(self.payload(fields)))
        check(value.get("success") is True, "Correct per-request PIN was rejected")
        await self.config_readback(fields)
        if not numeric_type_test:
            raise CoverageMissing("Missing/wrong PIN rejected and correct string accepted; numeric coercion test requires a canonical four-digit PIN")
        return "HTTP-unlocked fixture rejects missing/wrong PIN and correct digits as a number; correct string PIN succeeds"

    async def restore_config(self):
        if self.original is None or not self.mutated:
            return "No temporary configuration requires restoration"
        if self.pin_write_attempted:
            await self.unlock_http()
        await self.http_config(self.original)
        # A restore may restart the radio; wait for the current link to close before reconnecting.
        if self.client is not None and self.client.client.is_connected:
            try:
                await self.wait_disconnected(self.client)
            except AssertionError:
                pass  # Restoring already-original values need not restart BLE.
        await self.reconnect_verified()
        await self.config_readback(self.original)
        check(self.max_request == self.original["max-request-bytes"], "Restored request capability differs")
        return "Original BLE fields and linked remotes restored through verified HTTP"

    def write_reports(self):
        super().write_reports()
        path = self.output / "results.json"
        result = json.loads(path.read_text())
        result["coverage_limits"] = ["No pairing-code changes or bond removal",
                                     "No network, LED-pin, preset, or physical LED-output tests",
                                     "Settings PIN restoration verifies live state; persisted storage requires a separate reboot check",
                                     "HTTP socket timeout and body budget do not impose a hard deadline on trickling response headers",
                                     "Temporary sv:false changes can still be saved by an unrelated concurrent config save"]
        if not self.args.provision_test_pin:
            result["coverage_limits"].append("No settings PIN provisioning without --provision-test-pin")
        if self.pin_write_attempted and not self.pin_restored:
            result["coverage_limits"].append("Test PIN restoration unverified; retain private recovery credentials before fixture reuse")
        result["settings_pin_fixture"] = {"requested": self.args.provision_test_pin,
                                          "write_attempted": self.pin_write_attempted,
                                          "blank_pin_restoration_verified": self.pin_restored,
                                          "persistence_verified": False,
                                          "private_recovery_file": "private-config/pin-recovery.json" if self.pin_write_attempted else None}
        result["configuration_backup"] = "private-config/configuration.json" if self.cfg else None
        path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        report = self.output / "report.md"
        text = report.read_text().split("## Coverage limits", 1)[0]
        report.write_text(text + "## Coverage limits\n\n" + "\n".join("- " + x for x in result["coverage_limits"]) + "\n")

    async def cleanup(self):
        """Attempt every restoration step independently before closing either transport."""
        await self.case("restore_configuration", self.restore_config,
                        timeout=self.args.connect_timeout + self.args.timeout * 5 + 40, recover=False)
        await self.case("restore_test_pin", self.restore_test_pin,
                        timeout=self.args.connect_timeout + self.args.timeout * 8 + 40, recover=False)
        await self.case("disconnect", self.disconnect, timeout=12, recover=False)
        await self.case("close_oracle", self.oracle.close, timeout=self.args.timeout + 3, recover=False)
        self.finish_reports()

    async def run(self):
        interrupted = False
        try:
            self.write_reports()
            if await self.case("config_setup", self.setup_config,
                               timeout=self.args.connect_timeout + self.args.timeout * 12 + 30, recover=False):
                for name, operation in (("runtime_names_utf8", self.names),
                                        ("runtime_request_limits", self.request_limits),
                                        ("runtime_disable_enable", self.enable_disable),
                                        ("independent_settings_pin", self.settings_pin)):
                    if not await self.case(name, operation, recover=False):
                        if self.records[-1]["status"] == "fail":
                            break  # Restore immediately instead of stacking mutations on an unknown baseline.
        except asyncio.CancelledError:
            self.records.append({"name": "interruption", "status": "fail",
                                 "detail": "Configuration run interrupted", "duration_s": 0})
            interrupted = True
        finally:
            cleanup = asyncio.create_task(self.cleanup())
            while not cleanup.done():
                try:
                    await asyncio.shield(cleanup)
                except asyncio.CancelledError:
                    if not interrupted:
                        self.records.append({"name": "interruption", "status": "fail",
                                             "detail": "Configuration run interrupted during cleanup", "duration_s": 0})
                    interrupted = True
            cleanup.result()
        if interrupted:
            raise asyncio.CancelledError()
        return self.exit_code()


def parse_args(argv=None):
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--allow-config-tests", action="store_true")
    parser.add_argument("--settings-pin-env", default="WLED_HIL_SETTINGS_PIN")
    parser.add_argument("--provision-test-pin", action="store_true",
                        help="explicitly provision and restore a temporary PIN only on a blank-PIN fixture")
    special, remaining = parser.parse_known_args(argv)
    args = base_parse_args(remaining)
    if not special.allow_config_tests:
        parser.error("--allow-config-tests is required before configuration tests can touch hardware")
    if not args.http_url or args.serial_port:
        parser.error("Configuration recovery requires --http-url and no --serial-port")
    vars(args).update(vars(special))
    args.suite = "configuration"
    return args


async def main(argv=None):
    return await ConfigHilRunner(parse_args(argv)).run()


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(130)
# AI: end
