#!/usr/bin/env python3
"""Bounded real-device BLE acceptance tests; see README_PHASE1.md for the fixture contract."""
# AI: below section was generated by an AI
import argparse
import asyncio
import hashlib
import json
import platform
import random
import re
import statistics
import subprocess
import sys
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from collections import deque
from datetime import datetime, timezone
from pathlib import Path

import client_example as bridge


SAFE_CLIENT_CONNECTION_ERRORS = frozenset({
    "WLED is not ready", "WLED disconnected", "LIVE is not subscribed",
    "WLED is not ready; connect before requesting",
})
HEAP_FIELDS = ("freeheap", "minfreeheap", "minheap", "largestfreeblock", "largest_free_block", "maxallocheap")


class CoverageMissing(Exception):
    """An unmet fixture prerequisite is incomplete coverage, never a passing test."""


def check(condition, message):
    """Use explicit checks so Python's optimization flag cannot disable acceptance criteria."""
    if not condition:
        raise AssertionError(message)


def mac_identity(info):
    """Normalize WLED's hardware identity, rejecting missing or malformed identifiers."""
    value = str(info.get("mac", "")).replace(":", "").replace("-", "").lower()
    check(re.fullmatch(r"[0-9a-f]{12}", value) is not None, "Missing valid WLED MAC identity")
    return value


def restorable_state(state):
    """Back up only fields this runner changes; replaying all of /state has side effects."""
    check(type(state.get("on")) is bool, "State lacks boolean power value")
    check(type(state.get("bri")) is int, "State lacks brightness value")
    return {
        "on": state["on"], "bri": state["bri"], "tt": 0,
        "seg": [{"id": segment["id"], "col": segment["col"]}
                for segment in state.get("seg", []) if "id" in segment and "col" in segment],
    }


def padded_request_body(size):
    """Create exact UTF-8 request sizes using JSON whitespace, without persistent changes."""
    prefix = 'POST /json/state\n\n'
    body = '{"v":true,"_hil":"é🌈"}'
    padding = size - len((prefix + body).encode("utf-8"))
    if padding < 0:
        raise ValueError("Requested size is smaller than the test request")
    return body + " " * padding


def safe_error(error):
    """Unexpected library errors can contain payloads; never copy those into public reports."""
    if isinstance(error, (AssertionError, CoverageMissing)):
        return str(error)
    if isinstance(error, ConnectionError) and str(error) in SAFE_CLIENT_CONNECTION_ERRORS:
        return f"{type(error).__name__}: {error}"
    if isinstance(error, TimeoutError):
        return "Operation exceeded its deadline"
    return f"{type(error).__name__}; payload/error text suppressed to avoid logging secrets"


def health_summary(samples):
    """Describe observed heap ranges and final-quarter trends without declaring a leak threshold."""
    summary = {"sample_count": len(samples), "heap_metrics": {}}
    if samples:
        summary["observed_duration_s"] = round(max(0, samples[-1]["at"] - samples[0]["at"]), 3)
        summary["uptime_first_s"] = samples[0]["uptime"]
        summary["uptime_last_s"] = samples[-1]["uptime"]
    for field in HEAP_FIELDS:
        measured = [(sample["at"], sample[field]) for sample in samples if type(sample.get(field)) is int]
        if not measured:
            continue
        values = [value for _, value in measured]
        # Four equal-size windows make warm-up drops and a later plateau visible.
        # A short run may have empty windows; do not manufacture additional observations.
        windows = []
        for index in range(4):
            window = measured[index * len(measured) // 4:(index + 1) * len(measured) // 4]
            if not window:
                continue
            window_values = [value for _, value in window]
            windows.append({"quarter": index + 1, "sample_count": len(window),
                            "median_bytes": statistics.median(window_values),
                            "min_bytes": min(window_values), "max_bytes": max(window_values)})
        tail = measured[3 * len(measured) // 4:]
        tail_values = [value for _, value in tail]
        times = [timestamp - tail[0][0] for timestamp, _ in tail]
        time_mean = statistics.mean(times)
        value_mean = statistics.mean(tail_values)
        denominator = sum((timestamp - time_mean) ** 2 for timestamp in times)
        slope = (60 * sum((timestamp - time_mean) * (value - value_mean)
                          for timestamp, value in zip(times, tail_values)) / denominator
                 if denominator else None)
        summary["heap_metrics"][field] = {
            "sample_count": len(values), "first_bytes": values[0], "last_bytes": values[-1],
            "min_observed_bytes": min(values), "max_observed_bytes": max(values),
            "net_change_bytes": values[-1] - values[0], "quarter_windows": windows,
            "final_quarter": {"sample_count": len(tail), "median_bytes": statistics.median(tail_values),
                              "range_bytes": max(tail_values) - min(tail_values),
                              "net_change_bytes": tail_values[-1] - tail_values[0],
                              "trend_bytes_per_minute": round(slope, 3) if slope is not None else None},
        }
    return summary


class HttpOracle:
    """An independent HTTP path with socket timeouts, response bounds and no redirects."""

    def __init__(self, url, timeout):
        parsed = urllib.parse.urlsplit(url)
        if parsed.scheme not in ("http", "https") or not parsed.hostname:
            raise ValueError("--http-url requires an HTTP(S) origin")
        if parsed.username or parsed.password or parsed.query or parsed.fragment or parsed.path not in ("", "/"):
            raise ValueError("--http-url must be an origin without credentials, path or query")
        self.url = url.rstrip("/")
        self.timeout = timeout

    async def open(self):
        """HTTP has no persistent device state to initialize."""

    async def close(self):
        """Each HTTP response owns its connection."""

    async def snapshot(self, update=None):
        """Return state/info through HTTP, optionally applying a state-only update."""
        return await asyncio.to_thread(self._snapshot, update)

    def _snapshot(self, update):
        """Bound HTTP I/O independently of the surrounding async case deadline."""
        class NoRedirect(urllib.request.HTTPRedirectHandler):
            def redirect_request(self, *args, **kwargs):
                return None
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
        data = None if update is None else json.dumps({**update, "v": True}).encode()
        request = urllib.request.Request(self.url + "/json", data=data,
                                         headers={"Content-Type": "application/json"})
        with opener.open(request, timeout=self.timeout) as response:
            check(response.status == 200, "Independent HTTP request failed")
            payload = response.read(262145)
        check(len(payload) <= 262144, "Independent HTTP response exceeds 256 KiB")
        value = json.loads(payload)
        check(isinstance(value, dict) and "state" in value and "info" in value,
              "Independent HTTP response lacks state/info")
        return value


class SerialOracle:
    """WLED serial JSON oracle; one port owner, no raw serial/config text written to disk."""

    def __init__(self, port, timeout):
        self.port = port
        self.timeout = timeout
        self.serial = None
        self.lock = asyncio.Lock()
        self.events = []

    async def open(self):
        """Deassert DTR/RTS before opening; OS drivers may still pulse them on some boards."""
        import serial
        self.serial = serial.Serial(port=None, baudrate=115200, timeout=0.2,
                                    write_timeout=self.timeout)
        self.serial.dtr = False
        self.serial.rts = False
        self.serial.port = self.port
        await asyncio.to_thread(self.serial.open)

    async def close(self):
        """Close the single serial connection after all operations finish."""
        if self.serial is not None:
            await asyncio.to_thread(self.serial.close)

    async def snapshot(self, update=None):
        """Serialize full request/read cycles so replies cannot cross between callers."""
        async with self.lock:
            return await asyncio.to_thread(self._snapshot, update)

    def _snapshot(self, update):
        """Read one bounded JSON line, retaining only recognized crash event categories."""
        self._record_markers(self.serial.read(min(self.serial.in_waiting, 262144)))
        self.serial.reset_input_buffer()
        self.serial.write((json.dumps({**(update or {}), "v": True}) + "\n").encode())
        deadline = time.monotonic() + self.timeout
        pending = bytearray()
        while time.monotonic() < deadline:
            pending.extend(self.serial.read_until(b"\n", 16384))
            check(len(pending) <= 262144, "Serial response exceeds 256 KiB")
            while b"\n" in pending:
                line, _, remaining = pending.partition(b"\n")
                pending = bytearray(remaining)
                self._record_markers(line)
                try:
                    value = json.loads(line)
                except (ValueError, UnicodeDecodeError):
                    continue
                if isinstance(value, dict) and "state" in value and "info" in value:
                    check(not self.events, "Serial crash/watchdog/brownout marker observed")
                    return value
        raise TimeoutError("No WLED serial JSON reply")

    def _record_markers(self, data):
        """Classify sampled buffered output; this is not continuous crash-log capture."""
        for marker, category in ((b"Guru Meditation", "panic"),
                                 (b"Task watchdog", "watchdog"),
                                 (b"Brownout detector", "brownout")):
            if marker in data:
                self.events.append({"at": time.time(), "event": category})


class HilRunner:
    """Run bounded cases against one BLE peripheral and preserve the original failures."""

    def __init__(self, args, client_factory=None, oracle=None):
        self.args = args
        self.client_factory = client_factory or bridge.BleApiBridgeClient
        self.client = None
        self.oracle = oracle
        self.baseline = None
        self.identity = None
        self.max_request = 4096
        self.records = []
        self.samples = []
        self.actions = deque(maxlen=50)
        self.started = time.time()
        self.previous_uptime = None
        self.aborted = False
        self.rng = random.Random(args.seed)
        self.output = Path(args.output)
        self.output.mkdir(parents=True, exist_ok=True)
        self.last_report_at = 0

    async def connect(self, chunk_size=None):
        """Always allocate a fresh client after disconnect to avoid stale protocol streams."""
        await self.disconnect()
        self.client = self.client_factory(self.args.address, timeout=self.args.timeout,
                                          chunk_size=chunk_size or self.args.chunk_size,
                                          connect_timeout=self.args.connect_timeout)
        await asyncio.wait_for(self.client.connect(), self.args.connect_timeout + 10)
        self.client.max_request_bytes = self.max_request

    async def disconnect(self):
        """Teardown itself has a deadline and cannot prevent report generation forever."""
        if self.client is not None:
            await asyncio.wait_for(self.client.disconnect(), 10)

    async def request(self, method, path, body="", expected=200):
        """Record metadata only; configuration and state response bodies stay in memory."""
        started = time.monotonic()
        action = {"method": method.upper(), "path": path, "at": time.time()}
        self.actions.append(action)
        response = await asyncio.wait_for(self.client.request(method, path, body), self.args.timeout + 5)
        action.update(status=response.status, latency_ms=round((time.monotonic() - started) * 1000, 2),
                      response_bytes=len(response.body.encode("utf-8")))
        check(response.status == expected, f"{method} {path}: expected status {expected}, got {response.status}")
        check(response.content_type == "application/json", f"{method} {path}: wrong content type")
        return json.loads(response.body)

    async def post(self, update):
        """Apply only explicit state changes; temporary zero transition avoids timing ambiguity."""
        return await self.request("POST", "/json/state", json.dumps({"tt": 0, **update}))

    async def sample(self):
        """Record health telemetry; an unexplained uptime decrease fails its case."""
        started = time.monotonic()
        info = await self.request("GET", "/json/info")
        check(mac_identity(info) == self.identity, "BLE identity changed")
        uptime = info.get("uptime")
        check(type(uptime) is int, "Firmware uptime missing")
        sample = {"at": time.time(), "uptime": uptime,
                  "latency_ms": round((time.monotonic() - started) * 1000, 2)}
        sample.update({field: info[field] for field in HEAP_FIELDS if type(info.get(field)) is int})
        self.samples.append(sample)
        if self.previous_uptime is not None:
            check(uptime >= self.previous_uptime, "Firmware uptime decreased: unexpected restart")
        self.previous_uptime = uptime

    async def oracle_snapshot(self, update=None):
        """Recheck independent identity on every observation before trusting its state."""
        snapshot = await self.oracle.snapshot(update)
        check(mac_identity(snapshot["info"]) == self.identity, "Independent oracle identity changed")
        return snapshot

    async def setup(self):
        """Establish independent identity before state writes and save a minimal baseline."""
        if self.oracle is not None:
            await asyncio.wait_for(self.oracle.open(), self.args.timeout + 2)
        await self.connect()
        info = await self.request("GET", "/json/info")
        self.identity = mac_identity(info)
        check(info.get("ble", {}).get("protocol") == 1, "Firmware does not advertise BLE protocol 1")
        self.max_request = info.get("ble", {}).get("maxRequest", 0)
        check(type(self.max_request) is int and 256 <= self.max_request <= 4096,
              "Invalid advertised maximum request size")
        if self.oracle is not None:
            snapshot = await self.oracle.snapshot()
            check(mac_identity(snapshot["info"]) == self.identity, "Independent oracle points to a different WLED device")
        state = await self.request("GET", "/json/state")
        self.baseline = restorable_state(state)
        (self.output / "baseline-state.json").write_text(json.dumps(self.baseline, indent=2) + "\n")
        await self.sample()

    async def recover(self):
        """Reconnect at most twice, preserving the failed case instead of rewriting it."""
        attempts = []
        for attempt in range(2):
            try:
                await self.connect()
                info = await self.request("GET", "/json/info")
                check(mac_identity(info) == self.identity, "Recovery connected to a different device")
                attempts.append({"attempt": attempt + 1, "status": "pass"})
                return attempts, True
            except Exception as error:
                attempts.append({"attempt": attempt + 1, "status": "fail", "detail": safe_error(error)})
        return attempts, False

    async def case(self, name, operation, timeout=None, recover=True):
        """Persist each result immediately so interruption still leaves useful evidence."""
        started = time.monotonic()
        record = {"name": name, "status": "pass", "detail": ""}
        try:
            detail = await asyncio.wait_for(operation(), timeout or self.args.case_timeout)
            if detail:
                record["detail"] = detail
        except CoverageMissing as error:
            record.update(status="skip", detail=safe_error(error))
        except Exception as error:
            record.update(status="fail", detail=safe_error(error), last_actions=list(self.actions))
            if recover and self.identity is not None:
                record["recovery"], recovered = await self.recover()
                if not recovered:
                    self.aborted = True
        record["duration_s"] = round(time.monotonic() - started, 3)
        self.records.append(record)
        with (self.output / "cases.jsonl").open("a") as journal:
            journal.write(json.dumps(record, ensure_ascii=False) + "\n")
        print(f"{record['status'].upper():4} {name}: {record['detail']}", flush=True)
        if not name.startswith("soak_") or time.monotonic() - self.last_report_at >= 30:
            self.write_reports()
        return record["status"] == "pass"

    async def reads(self):
        """Validate every supported read's envelope without retaining configuration contents."""
        for path in ("/json", "/json/si", "/json/state", "/json/info", "/json/effects", "/json/fxdata", "/json/pins"):
            value = await self.request("GET", path)
            expected = list if path in ("/json/effects", "/json/fxdata") else dict
            check(isinstance(value, expected), f"{path}: wrong JSON shape")
            if path in ("/json", "/json/si"):
                check("state" in value and "info" in value, f"{path}: missing state/info")
        response = await asyncio.wait_for(self.client.request("GET", "/json/cfg"), self.args.timeout + 5)
        check(response.status in (200, 401), "Configuration read must succeed or require settings PIN")
        check(isinstance(json.loads(response.body), dict), "Configuration read has wrong JSON shape")

    async def semantic_errors(self):
        """Semantic errors must return statuses and leave the same connection usable."""
        for method, path, body, expected in (
                ("GET", "/unsupported", "", 404), ("POST", "/unsupported", "{}", 404),
                ("DELETE", "/json", "", 405), ("POST", "/json/state", "{", 400),
                ("POST", "/json/state", "[]", 400), ("POST", "/json/state", "null", 400),
                ("POST", "/json/state", "17", 400), ("POST", "/json/state", "", 400)):
            await self.request(method, path, body, expected)
            await self.request("GET", "/json/info")
        await self.request("get", "/json/state/?hil=1")

    async def state_controls(self):
        """Exercise power, positive brightness boundaries and segment colors with readback."""
        for update in ({"on": False}, {"on": True, "bri": 1}, {"bri": 128}, {"bri": 255}):
            await self.post(update)
            actual = await self.request("GET", "/json/state")
            for key, value in update.items():
                check(actual.get(key) == value, f"BLE state readback mismatch for {key}")
            if self.oracle is not None:
                independent = (await self.oracle_snapshot())["state"]
                for key, value in update.items():
                    check(independent.get(key) == value, f"Independent readback mismatch for {key}")
        await self.post({"bri": 0})
        check((await self.request("GET", "/json/state"))["on"] is False, "Brightness zero must turn power off")
        if self.oracle is not None:
            check((await self.oracle_snapshot())["state"]["on"] is False, "Independent oracle did not observe power off")
        await self.post({"on": True, "bri": 128})
        if not self.baseline["seg"]:
            raise CoverageMissing("No segment available for color tests")
        segment = self.baseline["seg"][0]
        color = list(segment["col"][0])
        color[:3] = [17, 83, 149]
        await self.post({"seg": [{"id": segment["id"], "col": [color]}]})
        actual = await self.request("GET", "/json/state")
        found = next((s for s in actual["seg"] if s["id"] == segment["id"]), None)
        check(found is not None and found["col"][0] == color, "RGB update or white-channel preservation failed")
        if self.oracle is not None:
            independent = (await self.oracle_snapshot())["state"]
            found = next((s for s in independent["seg"] if s["id"] == segment["id"]), None)
            check(found is not None and found["col"][0] == color, "Independent RGB/white readback failed")

    async def independent_control(self):
        """Check BLE writes independently and independent writes through BLE readback."""
        if self.oracle is None:
            raise CoverageMissing("Supply --http-url or --serial-port for an independent state oracle")
        await self.post({"on": True, "bri": 37})
        snapshot = await self.oracle_snapshot()
        check(snapshot["state"]["on"] is True and snapshot["state"]["bri"] == 37,
              "Independent oracle did not observe BLE state change")
        await self.oracle_snapshot({"on": True, "bri": 193, "tt": 0})
        state = await self.request("GET", "/json/state")
        check(state["on"] is True and state["bri"] == 193, "BLE did not observe independent state change")

    async def live_updates(self):
        """Exercise LIVE and TX concurrently; require convergence, not every intermediate value."""
        await self.client.subscribe_live()
        try:
            updates = 0
            for brightness in (71, 73, 79, 83, 89):
                await self.post({"on": True, "bri": brightness})
            deadline = time.monotonic() + self.args.timeout
            while time.monotonic() < deadline:
                value = await self.client.next_live(timeout=max(0.1, deadline - time.monotonic()))
                updates += 1
                check(isinstance(value, dict) and "state" in value and "info" in value, "LIVE shape invalid")
                check(mac_identity(value["info"]) == self.identity, "LIVE identity mismatch")
                if value["state"]["on"] is True and value["state"]["bri"] == 89:
                    break
            else:
                raise AssertionError("LIVE never converged to the last commanded brightness")
            await self.request("GET", "/json/info")
            return f"5 state writes; {updates} LIVE frames consumed before final convergence"
        finally:
            await self.client.unsubscribe_live()

    async def chunk_boundaries(self):
        """Vary application chunk caps and encoded lengths; this does not force negotiated MTU."""
        tested = []
        for cap in (3, 20, 65, 182, 244):
            await self.connect(cap)
            # Prefix bytes count toward ATT writes, not the request's length field.
            sizes = sorted({max(64, cap - 2), max(65, cap - 1), max(66, cap),
                            max(67, cap + 1), 255, 256, self.max_request})
            actual_budget = self.client.write_budget
            for size in sizes:
                if size > self.max_request:
                    continue
                body = padded_request_body(size)
                check(len(("POST /json/state\n\n" + body).encode()) == size, "Harness byte-count error")
                # Three-byte writes can take over a minute at ordinary connection intervals.
                original_timeout = self.args.timeout
                self.args.timeout = max(original_timeout, size / actual_budget * 0.1 + 15)
                self.client.timeout = self.args.timeout
                try:
                    result = await self.request("POST", "/json/state", body)
                finally:
                    self.args.timeout = original_timeout
                    self.client.timeout = original_timeout
                check("state" in result and "info" in result, "Boundary response lacks state/info")
                tested.append({"chunk_cap": cap, "actual_write_budget": actual_budget, "request_bytes": size})
        await self.connect()
        return tested

    async def concurrent_requests(self):
        """Public API callers may overlap; protocol requests must remain serialized."""
        values = await asyncio.gather(*(self.request("GET", "/json/info") for _ in range(12)))
        check(all(mac_identity(value) == self.identity for value in values), "Concurrent responses mismatched")

    async def reconnect_cycles(self):
        """Repeat normal disconnect/reconnect and prove identity/state remain readable."""
        for _ in range(5):
            await self.connect()
            await self.sample()
            await self.request("GET", "/json/state")

    async def framing_fault(self, chunks, wait_seconds=5):
        """Exclusive raw writes require disconnect on invalid framing, then a clean recovery."""
        await self.connect()
        raw = self.client.client
        received = []
        # Observe raw TX without letting the reference client's unsolicited-TX guard
        # create the disconnection this test is meant to require from the firmware.
        await raw.stop_notify(bridge.TX_UUID)
        await raw.start_notify(bridge.TX_UUID, lambda _characteristic, data: received.append(len(data)))
        for chunk in chunks:
            try:
                await asyncio.wait_for(raw.write_gatt_char(bridge.RX_UUID, chunk, response=True), self.args.timeout)
            except Exception:
                # A firmware disconnect can race the write acknowledgement; disconnection is still required.
                break
        deadline = time.monotonic() + wait_seconds
        while raw.is_connected and time.monotonic() < deadline:
            await asyncio.sleep(0.1)
        check(not raw.is_connected, "Firmware kept invalid or stalled frame connection open")
        check(not received, "Firmware returned TX data for invalid framing instead of closing the link")
        await self.connect()
        await self.sample()

    async def partial_reconnect(self):
        """A partially assembled request must not survive an intentional disconnect."""
        await self.connect()
        await self.client.client.write_gatt_char(bridge.RX_UUID, b"\x08\x00GE", response=True)
        await self.connect()
        await self.sample()

    async def restore(self):
        """Restore only touched state, after rechecking the identity on the current stream."""
        if self.baseline is None:
            return "No state mutations occurred before setup completed"
        if self.client is None or not self.client.client.is_connected:
            await self.connect()
        check(mac_identity(await self.request("GET", "/json/info")) == self.identity,
              "Refusing to restore baseline onto an unexpected device")
        await self.post(self.baseline)
        current = await self.request("GET", "/json/state")
        self.verify_baseline(current, "BLE")
        if self.oracle is not None:
            self.verify_baseline((await self.oracle_snapshot())["state"], "Independent oracle")
            return "BLE and independent oracle match baseline"
        return "BLE matches baseline; no independent oracle configured"

    def verify_baseline(self, current, source):
        """Compare every touched field against the saved baseline through either transport."""
        check(current["on"] == self.baseline["on"] and current["bri"] == self.baseline["bri"],
              f"{source}: baseline power/brightness restoration failed")
        for segment in self.baseline["seg"]:
            found = next((s for s in current["seg"] if s["id"] == segment["id"]), None)
            check(found is not None and found["col"] == segment["col"], f"{source}: baseline color restoration failed")

    async def soak(self):
        """Seeded operations run until a fixed deadline, with periodic heap/uptime samples."""
        deadline = time.monotonic() + self.args.duration
        index = 0
        while time.monotonic() < deadline and not self.aborted:
            choice = self.rng.randrange(5 if self.oracle is not None else 4)

            async def operation():
                if choice == 0:
                    brightness = self.rng.randint(1, 255)
                    await self.post({"on": True, "bri": brightness})
                    state = await self.request("GET", "/json/state")
                    check(state["on"] is True and state["bri"] == brightness, "Soak state mismatch")
                elif choice == 1:
                    await self.request("GET", "/json/effects")
                elif choice == 2:
                    await self.live_updates()
                elif choice == 3:
                    await self.connect()
                else:
                    await self.independent_control()
                await self.sample()

            # Finish the final bounded operation normally; reaching the soak deadline
            # must not manufacture a timeout failure in otherwise healthy traffic.
            await self.case(f"soak_{index:05d}_operation_{choice}", operation)
            index += 1
            await asyncio.sleep(min(0.2, max(0, deadline - time.monotonic())))

    async def run(self):
        """Write artifacts for setup failures, test failures, restoration failures and clean runs."""
        try:
            setup_ok = await self.case("setup_identity_baseline", self.setup,
                                       timeout=self.args.connect_timeout + self.args.timeout * 5 + 10,
                                       recover=False)
            if setup_ok:
                cases = [("supported_reads", self.reads), ("state_controls", self.state_controls),
                         ("independent_oracle", self.independent_control), ("live_convergence", self.live_updates)]
                if self.args.suite != "smoke":
                    cases += [("semantic_errors", self.semantic_errors),
                              ("chunk_boundaries", self.chunk_boundaries),
                              ("concurrent_callers", self.concurrent_requests),
                              ("reconnect_cycles", self.reconnect_cycles),
                              ("partial_disconnect", self.partial_reconnect)]
                    faults = [("split_length", [b"\x01"]), ("zero_length", [b"\x00\x00"]),
                              ("oversized_length", [(self.max_request + 1).to_bytes(2, "little")]),
                              ("initial_overrun", [b"\x01\x00ab"]),
                              ("continuation_overrun", [b"\x03\x00a", b"bcd"])]
                    for name, chunks in faults:
                        cases.append(("framing_" + name, lambda chunks=chunks: self.framing_fault(chunks)))
                    cases.append(("partial_stall", lambda: self.framing_fault([b"\x04\x00"], 15)))
                for name, operation in cases:
                    if self.aborted:
                        self.records.append({"name": name, "status": "skip", "detail": "Recovery exhausted", "duration_s": 0})
                    else:
                        await self.case(name, operation,
                                        timeout=max(self.args.case_timeout, 900) if name == "chunk_boundaries" else None)
                if self.args.suite == "soak" and not self.aborted:
                    await self.soak()
            else:
                self.records.append({"name": "suite", "status": "skip", "detail": "Setup failed", "duration_s": 0})
        except asyncio.CancelledError:
            self.records.append({"name": "interruption", "status": "fail", "detail": "Run interrupted", "duration_s": 0})
            raise
        except Exception as error:
            self.records.append({"name": "runner", "status": "fail", "detail": safe_error(error), "duration_s": 0})
        finally:
            await self.case("restore_baseline", self.restore,
                            timeout=self.args.connect_timeout + self.args.timeout * 3 + 10, recover=False)
            if self.baseline is not None and self.previous_uptime is not None:
                await self.case("final_health", self.sample, recover=False)
            await self.case("disconnect", self.disconnect, timeout=12, recover=False)
            if self.oracle is not None:
                await self.case("close_oracle", self.oracle.close, timeout=self.args.timeout + 3, recover=False)
            self.write_reports()
        return self.exit_code()

    def exit_code(self):
        """Exit 2 distinguishes incomplete selected coverage from a fully passing selected suite."""
        if any(record["status"] == "fail" for record in self.records):
            return 1
        return 2 if any(record["status"] == "skip" for record in self.records) else 0

    def write_reports(self):
        """Create machine-readable and human-readable artifacts without raw request/response data."""
        self.last_report_at = time.monotonic()
        counts = {status: sum(record["status"] == status for record in self.records) for status in ("pass", "fail", "skip")}
        result = {"schema": 1, "suite": self.args.suite, "seed": self.args.seed,
                  "started_utc": datetime.fromtimestamp(self.started, timezone.utc).isoformat(),
                  "elapsed_s": round(time.time() - self.started, 3), "counts": counts,
                  "outcome": "failed" if counts["fail"] else "incomplete" if counts["skip"] else "passed_selected_coverage",
                  "identity_mac": self.identity, "max_request_bytes": self.max_request,
                  "oracle": type(self.oracle).__name__ if self.oracle is not None else None,
                  "host": {"python": platform.python_version(), "platform": platform.platform()},
                  "records": self.records, "health_samples": self.samples,
                  "health_summary": health_summary(self.samples),
                  "coverage_limits": ["No physical iOS behavior", "No bond deletion or wrong-passkey automation",
                                      "No settings PIN or configuration mutation", "No forced RF loss or negotiated MTU",
                                      "No physical power-cut or reset fixture", "No LED light-output verification",
                                      "Serial oracle does not establish Wi-Fi coexistence coverage",
                                      "Serial crash markers are sampled during oracle queries, not captured continuously"]}
        if isinstance(self.oracle, SerialOracle):
            result["serial_crash_markers"] = self.oracle.events
        directory = Path(__file__).resolve().parent
        result["source_sha256"] = {path.name: hashlib.sha256(path.read_bytes()).hexdigest()
                                  for pattern in ("*.py", "*.cpp", "*.h") for path in directory.glob(pattern)}
        try:
            result["git_revision"] = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=directory,
                                                              timeout=2, stderr=subprocess.DEVNULL, text=True).strip()
        except (OSError, subprocess.SubprocessError):
            result["git_revision"] = None
        text = json.dumps(result, indent=2, ensure_ascii=False) + "\n"
        temporary = self.output / "results.json.tmp"
        temporary.write_text(text)
        temporary.replace(self.output / "results.json")
        suite = ET.Element("testsuite", name="WLED BLE Phase 1", tests=str(len(self.records)),
                           failures=str(counts["fail"]), skipped=str(counts["skip"]))
        for record in self.records:
            case = ET.SubElement(suite, "testcase", name=record["name"], time=str(record["duration_s"]))
            if record["status"] in ("fail", "skip"):
                child = ET.SubElement(case, "failure" if record["status"] == "fail" else "skipped")
                child.text = str(record["detail"])
        ET.ElementTree(suite).write(self.output / "junit.xml", encoding="utf-8", xml_declaration=True)
        lines = [f"# Phase 1 BLE {self.args.suite}: {result['outcome']}", "",
                 f"{counts['pass']} passed, {counts['fail']} failed, {counts['skip']} skipped. Seed: {self.args.seed}.", "",
                 "A passing selected suite is not complete BLE/platform certification. See coverage limits below.", "",
                 "| Case | Result | Seconds | Detail |", "| --- | --- | ---: | --- |"]
        for record in self.records:
            detail = str(record["detail"]).replace("|", "\\|").replace("\n", " ")
            if len(detail) > 250:
                detail = detail[:247] + "... (full metadata in results.json)"
            lines.append(f"| {record['name']} | {record['status']} | {record['duration_s']} | {detail} |")
        health = result["health_summary"]
        lines += ["", "## Health observations", "",
                  f"{health['sample_count']} health samples. Heap summaries describe observations; no leak threshold is applied."]
        for field, metric in health["heap_metrics"].items():
            tail = metric["final_quarter"]
            trend = (f"{tail['trend_bytes_per_minute']} bytes/minute" if tail["trend_bytes_per_minute"] is not None
                     else "unavailable from this sample count")
            lines.append(f"- `{field}`: {metric['first_bytes']} → {metric['last_bytes']} bytes; "
                         f"observed range {metric['min_observed_bytes']}–{metric['max_observed_bytes']}. "
                         f"Final quarter ({tail['sample_count']} samples): median {tail['median_bytes']}, "
                         f"range {tail['range_bytes']}, trend {trend}.")
        lines += ["", "## Coverage limits", ""] + ["- " + limitation for limitation in result["coverage_limits"]]
        (self.output / "report.md").write_text("\n".join(lines) + "\n")


def parse_args(argv=None):
    """Reject unbounded deadlines and unsupported ATT chunk caps before touching a device."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--address", required=True, help="BLE peripheral UUID on macOS; address on other hosts")
    parser.add_argument("--http-url", help="Independent HTTP origin, for example http://192.168.1.50")
    parser.add_argument("--serial-port", help="Independent WLED serial JSON port at 115200; must have one owner")
    parser.add_argument("--output", required=True, help="Dedicated artifact directory for this run")
    parser.add_argument("--suite", choices=("smoke", "regression", "soak"), default="smoke")
    parser.add_argument("--duration", type=float, default=3600, help="Soak workload seconds, after regression")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--chunk-size", type=int, default=244, help="Application cap; actual ATT writes may be smaller")
    parser.add_argument("--timeout", type=float, default=30, help="Per-request deadline in seconds")
    parser.add_argument("--connect-timeout", type=float, default=90)
    parser.add_argument("--case-timeout", type=float, default=180)
    args = parser.parse_args(argv)
    if args.http_url and args.serial_port:
        parser.error("Choose one independent oracle: --http-url or --serial-port")
    if not 3 <= args.chunk_size <= 244:
        parser.error("--chunk-size must be between 3 and 244")
    for name in ("duration", "timeout", "connect_timeout", "case_timeout"):
        value = getattr(args, name)
        if not 0 < value <= 172800:
            parser.error(f"--{name.replace('_', '-')} must be positive and at most 172800 seconds")
    return args


async def main(argv=None):
    """Construct an oracle before hardware setup; initialization failures still produce reports."""
    args = parse_args(argv)
    runner = HilRunner(args)
    try:
        if args.http_url:
            runner.oracle = HttpOracle(args.http_url, args.timeout)
        elif args.serial_port:
            runner.oracle = SerialOracle(args.serial_port, args.timeout)
    except Exception as error:
        runner.records.append({"name": "oracle_configuration", "status": "fail", "detail": safe_error(error), "duration_s": 0})
        runner.write_reports()
        return 1
    return await runner.run()


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(130)
# AI: end
