"""Opt-in macOS pairing adapter for the exact Bleak version pinned by this client.

Bleak 3.0.2's CoreBluetooth read wrapper ignores timeout kwargs, while its
PeripheralDelegate uses a 20-second default. Select this backend only for manual
commissioning; it extends the protected TX read without patching global classes.
Source: bleak/backends/corebluetooth/{client,PeripheralDelegate}.py in Bleak 3.0.2.
"""

# AI: below section was generated by an AI
from importlib.metadata import version

TX_UUID = "7c2e0003-5d2b-4fd0-b1c2-0cc8f5470101"
SUPPORTED_BLEAK_VERSION = "3.0.2"


class ProtectedProbeTimeoutMixin:
    """Extend only WLED's protected TX read; retain the backend's other behavior."""

    async def read_gatt_char(self, characteristic, *, use_cached=False, **kwargs):
        if characteristic.uuid.lower() != TX_UUID:
            return await super().read_gatt_char(characteristic, use_cached=use_cached, **kwargs)
        if self._delegate is None:
            raise ConnectionError("CoreBluetooth is not connected")
        output = await self._delegate.read_characteristic(
            characteristic.obj, use_cached=use_cached, timeout=90)
        return bytearray(output)


def commissioning_backend():
    """Load the platform backend lazily and fail explicitly after dependency changes.

    Bleak documents custom backends, but this narrow read override touches a
    private delegate. Revalidate that call before changing the dependency pin.
    """
    installed = version("bleak")
    if installed != SUPPORTED_BLEAK_VERSION:
        raise RuntimeError(f"macOS commissioning requires Bleak {SUPPORTED_BLEAK_VERSION}; found {installed}")
    from bleak.backends.corebluetooth.client import BleakClientCoreBluetooth

    class WledCommissioningBackend(ProtectedProbeTimeoutMixin, BleakClientCoreBluetooth):
        """Instance-local adapter selected using BleakClient's backend argument."""

    return WledCommissioningBackend
# AI: end
