#!/usr/bin/env python3
"""Reversible BLE-only persistence checks for an exclusively controlled WLED fixture.

Root/operator supplies the independently verified device MAC and runs this tool.
It never accesses HTTP, USB, serial, pairing codes, or firmware flashing. Reboot
and temporary blank-PIN-fixture tests require their explicit command-line flags.
Reports omit response bodies and credentials. Recovery backups are owner-only.
"""
# AI: below section was generated by an AI
import argparse
import asyncio
import base64
import copy
import hashlib
import json
import math
import os
from pathlib import Path
import re
import secrets
import sys
import time
import urllib.parse
import uuid

from client_example import BleApiBridgeClient


class HarnessError(Exception):
    """Only fixed, non-sensitive diagnostic text may be attached to this error."""


class Incomplete(HarnessError):
    pass


def check(condition, message):
    if not condition:
        raise HarnessError(message)


def normalize_mac(value):
    normalized = re.sub(r"[:-]", "", value or "").lower()
    check(re.fullmatch(r"[0-9a-f]{12}", normalized) is not None, "Invalid expected/device MAC")
    return normalized


def error_label(error):
    # Backend exceptions can contain payloads. Never serialize their text.
    return str(error) if isinstance(error, HarnessError) else type(error).__name__


def json_bytes(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), allow_nan=False).encode("utf-8")


def private_write(path, data, *, replace=False):
    if not isinstance(data, bytes):
        data = (json.dumps(data, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    temporary = path.with_name(path.name + ".pending") if replace else path
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(temporary, flags, 0o600)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        if replace:
            os.replace(temporary, path)
    except BaseException:
        if replace:
            temporary.unlink(missing_ok=True)
        raise


def lighting_projection(state):
    # Exclude transient errors, preset identity and other read-only telemetry.
    top = ("on", "bri", "transition", "bs", "mainseg", "lor")
    segment = ("id", "start", "stop", "startY", "stopY", "grp", "spc", "of", "on", "frz", "bri", "cct",
               "col", "fx", "sx", "ix", "pal", "sel", "rev", "mi", "rY", "mY", "tp", "m12", "si",
               "n", "set", "c1", "c2", "c3", "o1", "o2", "o3", "bm")
    result = {**{key: copy.deepcopy(state[key]) for key in top if key in state},
              "seg": [{key: copy.deepcopy(item[key]) for key in segment if key in item} for item in state["seg"]]}
    if isinstance(state.get("udpn"), dict):
        result["udpn"] = {key: copy.deepcopy(state["udpn"][key]) for key in ("send", "recv", "sgrp", "rgrp") if key in state["udpn"]}
    return result


class PersistenceHil:
    def __init__(self, args):
        self.args = args
        self.expected_mac = normalize_mac(args.expected_mac)
        self.output = args.output.resolve()
        self.output.mkdir(mode=0o700, parents=True, exist_ok=False)
        os.chmod(self.output, 0o700)
        private_write(self.output / ".gitignore", b"*\n")
        self.private = self.output / "private-recovery"
        self.private.mkdir(mode=0o700)
        self.client = BleApiBridgeClient(args.address, chunk_size=args.chunk_size, timeout=args.timeout,
                                        connect_timeout=args.connect_timeout, commission=args.commission)
        self.pin = os.environ.get(args.settings_pin_env, "") if args.settings_pin_env else ""
        self.initial_pin_required = False
        self.test_pin = None
        self.cfg = self.state = None
        self.ui_form = self.security_flags = None
        self.presets = None
        self.presets_existed = False
        self.max_chunk = 0
        self.transfer = None
        self.library_dirty = self.ui_dirty = self.pin_dirty = self.runtime_dirty = False
        self.temporary_file_dirty = False
        self.temporary_ids = []
        self.temporary_path = "/ble-persist-" + uuid.uuid4().hex + ".bin"
        self.report = {"suite": "ble-api2-persistence", "device_mac": self.expected_mac,
                       "outcome": "running", "hardware_validated": False, "cases": [], "skipped": [],
                       "backup_directory": str(self.private), "cleanup": "pending"}
        self.journal = {"device_mac": self.expected_mac, "phase": "setup", "temporary_file": self.temporary_path,
                        "restore_policy": "Restore only to this MAC, with exclusive control of the fixture."}
        self.write_journal()
        self.write_report()

    def write_journal(self):
        self.journal.update(library_may_have_changed=self.library_dirty, ui_may_have_changed=self.ui_dirty,
                            pin_may_have_changed=self.pin_dirty, runtime_may_have_changed=self.runtime_dirty,
                            temporary_file_may_exist=self.temporary_file_dirty,
                            active_transfer=self.transfer, temporary_ids=self.temporary_ids)
        private_write(self.private / "recovery.json", self.journal, replace=True)

    def write_report(self):
        private_write(self.output / "results.json", self.report, replace=True)

    async def request(self, method, path, body=b"", expected=(200,)):
        if isinstance(body, bytes):
            body = body.decode("utf-8")
        response = await self.client.request(method, path, body)
        check(response.status in expected, f"{method} {path} returned unexpected status {response.status}")
        return response

    async def get(self, path):
        return (await self.request("GET", path)).json()

    async def post(self, path, value, expected=(200,)):
        return (await self.request("POST", path, json_bytes(value), expected)).json()

    async def verify_identity(self):
        info = await self.client.refresh_capabilities()
        check(normalize_mac(info.get("mac")) == self.expected_mac, "Device identity differs from independent expected MAC")
        check(info.get("ble", {}).get("api", 0) >= 2, "Firmware lacks Bluetooth API 2")
        capabilities = await self.get("/ble/capabilities")
        chunk = capabilities.get("maxChunk")
        check(type(chunk) is int and 0 < chunk <= 1024, "Invalid transfer chunk capability")
        self.max_chunk = chunk
        return info

    async def connect(self):
        await self.client.connect(pair=self.args.pair)
        return await self.verify_identity()

    async def authenticate(self):
        status = await self.get("/ble/auth")
        if status.get("authorized") is True:
            return
        credential = self.test_pin if self.pin_dirty else self.pin
        if not credential:
            raise Incomplete("Settings PIN is required but unknown; no credential will be replaced")
        await asyncio.sleep(3.2)  # also permits recovery after a deliberate failed attempt
        result = await self.post("/ble/auth", {"pin": credential})
        check(result.get("authorized") is True, "Settings authorization failed")

    async def reconnect(self):
        await self.client.disconnect()
        await asyncio.sleep(1)
        # Reconnect a known device at most twice; never repeat a failed mutation.
        for attempt in range(2):
            try:
                return await self.connect()
            except (ConnectionError, TimeoutError):
                if attempt:
                    raise
                await asyncio.sleep(2)

    async def read_file(self, path, allow_missing=False):
        result = bytearray()
        revision = total = None
        while True:
            payload = {"op": "read", "path": path, "offset": len(result), "length": self.max_chunk}
            if revision is not None:
                payload["revision"] = revision
            response = await self.request("POST", "/ble/fs", json_bytes(payload), (200, 404) if allow_missing else (200,))
            if response.status == 404:
                check(not result, "File disappeared during read")
                return None
            reply = response.json()
            part = base64.b64decode(reply["data"], validate=True)
            size = reply.get("size")
            check(type(size) is int and 0 <= size <= 16 * 1024 * 1024, "Invalid file length")
            check(total is None or total == size, "File changed length during read")
            check(reply.get("offset") == len(result) and reply.get("next") == len(result) + len(part), "Invalid file offset acknowledgement")
            check(revision is None or revision == reply.get("revision"), "File revision changed during read")
            revision, total = reply.get("revision"), size
            result.extend(part)
            check(len(result) <= total and (part or len(result) == total), "File read made invalid progress")
            check(reply.get("eof") is (len(result) == total), "Invalid end-of-file acknowledgement")
            if len(result) == total:
                break
        check(hashlib.sha256(result).hexdigest() == revision, "Complete file checksum mismatch")
        return bytes(result)

    async def begin_transfer(self, endpoint, payload):
        reply = await self.post(endpoint, {"op": "begin", **payload})
        check(isinstance(reply.get("id"), str) and len(reply["id"]) == 8, "Invalid transfer identifier")
        check(type(reply.get("maxChunk")) is int and 0 < reply["maxChunk"] <= self.max_chunk, "Invalid transfer write budget")
        self.transfer = {"endpoint": endpoint, "id": reply["id"]}
        self.write_journal()
        return reply["id"], reply["maxChunk"]

    async def transfer_bytes(self, endpoint, metadata, data):
        digest = hashlib.sha256(data).hexdigest()
        identifier, budget = await self.begin_transfer(endpoint, {**metadata, "size": len(data), "sha256": digest})
        for offset in range(0, len(data), budget):
            part = data[offset:offset + budget]
            receipt = await self.post(endpoint, {"op": "write", "id": identifier, "offset": offset,
                                                 "data": base64.b64encode(part).decode("ascii")})
            check(receipt.get("id") == identifier and receipt.get("next") == offset + len(part), "Invalid file write acknowledgement")
        result = await self.post(endpoint, {"op": "commit", "id": identifier})
        self.transfer = None
        self.write_journal()
        if endpoint == "/ble/fs":
            self.require_saved(result)
            check(result.get("size") == len(data) and result.get("sha256") == digest, "File commit receipt differs from uploaded content")
        return result

    async def file_write(self, path, data):
        return await self.transfer_bytes("/ble/fs", {"path": path}, data)

    async def state_write(self, value, require_saved=False):
        data = json_bytes(value)
        if len(data) + len("POST /json/state\n\n") > self.client.max_request_bytes:
            result = await self.transfer_bytes("/ble/request", {"method": "POST", "path": "/json/state", "contentType": "application/json"}, data)
        else:
            result = await self.post("/json/state", value)
        check(result.get("success") is True, "State mutation lacks successful acknowledgement")
        if require_saved:
            self.require_saved(result)
        return result

    @staticmethod
    def require_saved(result):
        check(result.get("success") is True and result.get("saved") is True, "Mutation lacks confirmed persistence receipt")

    async def form_write(self, route, fields):
        body = urllib.parse.urlencode(fields).encode("utf-8")
        if len(body) + len(("POST " + route + "\n\n").encode()) > self.client.max_request_bytes:
            result = await self.transfer_bytes("/ble/request", {"method": "POST", "path": route,
                "contentType": "application/x-www-form-urlencoded"}, body)
        else:
            result = (await self.request("POST", route, body)).json()
        self.require_saved(result)
        return result

    async def setup(self):
        info = await self.connect()
        status = await self.get("/ble/auth")
        self.initial_pin_required = status.get("pinRequired") is True
        self.journal["original_pin_present"] = self.initial_pin_required
        await self.authenticate()
        cfg_response = await self.request("GET", "/json/cfg")
        state_response = await self.request("GET", "/json/state")
        self.cfg, self.state = cfg_response.json(), state_response.json()
        check(isinstance(self.cfg, dict) and isinstance(self.state, dict) and isinstance(self.state.get("seg"), list), "Invalid baseline configuration/state")
        if self.state.get("pl", -1) >= 0 or self.state.get("nl", {}).get("on") or info.get("live"):
            raise Incomplete("Fixture has an active playlist, nightlight or realtime input; no mutations performed")
        identifier = self.cfg.get("id", {})
        check(isinstance(identifier.get("name"), str) and type(identifier.get("sui")) is bool, "UI settings baseline is not safely restorable")
        self.ui_form = [("DS", identifier["name"])] + ([("SU", "on")] if identifier["sui"] else [])
        security = (await self.request("GET", "/settings/s.js?p=6")).body
        self.security_flags = []
        for field in ("NO", "OW", "AO", "SU"):
            matches = re.findall(r"d\.Sf\." + field + r"\.checked=([01]);", security)
            check(len(matches) == 1, "Security checkbox baseline is not safely restorable")
            if matches[0] == "1":
                self.security_flags.append((field, "on"))
        self.presets = await self.read_file("/presets.json", allow_missing=True)
        self.presets_existed = self.presets is not None
        library = json.loads(self.presets) if self.presets_existed else {"0": {}}
        check(isinstance(library, dict), "Preset library baseline is not an object")
        self.temporary_ids = [identifier for identifier in range(250, 0, -1) if str(identifier) not in library][:2]
        if len(self.temporary_ids) != 2:
            raise Incomplete("Two unused preset IDs are required; existing presets will not be overwritten")
        private_write(self.private / "configuration.json", cfg_response.body.encode("utf-8"))
        private_write(self.private / "runtime-state.json", state_response.body.encode("utf-8"))
        if self.presets_existed:
            private_write(self.private / "presets.json", self.presets)
        self.journal.update(phase="backed_up", original_presets_existed=self.presets_existed,
                            original_presets_sha256=hashlib.sha256(self.presets).hexdigest() if self.presets_existed else None,
                            restore_ui_form=self.ui_form, original_security_checkboxes=self.security_flags)
        self.write_journal()
        self.report["baseline"] = {"presets_existed": self.presets_existed,
                                   "presets_bytes": len(self.presets or b""), "settings_pin_present": self.initial_pin_required}

    async def presets_case(self):
        scene_id, playlist_id = self.temporary_ids
        baseline = lighting_projection(await self.get("/json/state"))
        self.library_dirty = self.runtime_dirty = True
        self.journal["phase"] = "preset_mutations"
        self.write_journal()  # before the first potentially persistent command
        await self.state_write({"psave": scene_id, "n": "BLE persistence fixture", "ib": True, "sb": True,
                                "v": False, "udpn": {"nn": True}}, require_saved=True)
        library = json.loads(await self.read_file("/presets.json"))
        check(library.get(str(scene_id), {}).get("n") == "BLE persistence fixture", "Saved scene missing from persisted file")
        old_scene = copy.deepcopy(library[str(scene_id)])
        result = await self.post("/ble/presets", {"op": "rename", "id": scene_id, "name": "BLE renamed fixture"})
        self.require_saved(result)
        library = json.loads(await self.read_file("/presets.json"))
        expected_scene = {**old_scene, "n": "BLE renamed fixture"}
        check(library.get(str(scene_id)) == expected_scene, "Rename altered stored scene content")
        check(lighting_projection(await self.get("/json/state")) == baseline, "Saving/renaming unexpectedly changed lighting")

        # WLED's psave+playlist API loads a playlist as a side effect. Install the
        # definition atomically as a file instead, so this test never starts it.
        playlist = {"n": "BLE playlist fixture", "playlist": {"ps": [scene_id], "dur": [10], "transition": [0], "repeat": 1, "end": 0}}
        library[str(playlist_id)] = playlist
        await self.file_write("/presets.json", json_bytes(library))
        actual = json.loads(await self.read_file("/presets.json"))
        check(actual.get(str(playlist_id)) == playlist, "Stored playlist differs from requested definition")
        state = await self.get("/json/state")
        check(state.get("pl", -1) < 0 and lighting_projection(state) == baseline, "Playlist storage unexpectedly started playback")
        await self.state_write({"pdel": playlist_id, "v": False, "udpn": {"nn": True}}, require_saved=True)
        await self.state_write({"pdel": scene_id, "v": False, "udpn": {"nn": True}}, require_saved=True)
        actual = json.loads(await self.read_file("/presets.json"))
        check(str(scene_id) not in actual and str(playlist_id) not in actual, "Temporary preset deletion did not persist")
        await self.restore_library()

    async def restore_library(self):
        if not self.library_dirty:
            return
        try:
            current = await self.read_file("/presets.json", allow_missing=True)
        except (HarnessError, ValueError, ConnectionError, TimeoutError):
            # Corrupt or unreadable test output must not prevent replacing it
            # with the already verified private baseline. Recheck a lost link.
            current = object()
            if not self.client.is_connected:
                await self.reconnect()
                await self.authenticate()
        if self.presets_existed:
            if current != self.presets:
                await self.file_write("/presets.json", self.presets)
            check(await self.read_file("/presets.json") == self.presets, "Original preset file was not restored byte-for-byte")
        else:
            if current is not None:
                await self.post("/ble/fs", {"op": "delete", "path": "/presets.json"}, (200, 404))
            check(await self.read_file("/presets.json", allow_missing=True) is None, "Originally absent preset file still exists")
        self.library_dirty = False
        self.write_journal()

    async def reboot(self):
        check(self.args.allow_reboot, "Reboot was not explicitly enabled")
        self.runtime_dirty = True
        self.write_journal()
        # A link loss alone cannot prove a reset. /uptime is the uint32_t
        # millisecond counter; observe enough boot age to separate a reset
        # from ordinary reconnect/round-trip timing, including counter wrap.
        async def uptime():
            body = (await self.request("GET", "/uptime")).body
            check(re.fullmatch(r"[0-9]{1,10}", body) is not None, "Invalid reboot uptime evidence")
            value = int(body)
            check(value < 2 ** 32, "Invalid reboot uptime range")
            return value
        before = await uptime()
        if before < 10000:
            await asyncio.sleep((10000 - before) / 1000 + 0.1)
            before = await uptime()
        check(before >= 10000, "Insufficient boot age for reset verification")
        started = time.monotonic()
        result = (await self.request("GET", "/reset")).json()
        check(result.get("success") is True and result.get("reboot") is True, "Missing reboot acknowledgement")
        deadline = time.monotonic() + 15
        while self.client.is_connected and time.monotonic() < deadline:
            await asyncio.sleep(0.1)
        check(not self.client.is_connected, "Reboot did not release the Bluetooth connection")
        await asyncio.sleep(3)
        await self.reconnect()
        after = await uptime()
        elapsed = round((time.monotonic() - started) * 1000)
        missing_uptime = (before + elapsed - after) % (2 ** 32)
        check(after <= elapsed + 3000 and 7000 <= missing_uptime <= before + 3000,
              "Connection recovered without verified device uptime reset")
        self.report.setdefault("reboots", []).append({"before_ms": before, "after_ms": after, "elapsed_ms": elapsed})
        self.write_report()

    async def ui_case(self):
        self.ui_dirty = True
        self.journal["phase"] = "ui_settings"
        self.write_journal()
        name = "BLE test " + uuid.uuid4().hex[:8]
        form = [("DS", name)] + [item for item in self.ui_form if item[0] != "DS"]
        await self.form_write("/settings/ui", form)
        expected = copy.deepcopy(self.cfg)
        expected["id"]["name"] = name
        check(await self.get("/json/cfg") == expected, "UI form changed fields beyond the device description")
        if self.args.allow_reboot:
            await self.reboot()
            await self.authenticate()
            check(await self.get("/json/cfg") == expected, "Saved UI description did not survive reboot unchanged")
        else:
            self.report["skipped"].append("UI reboot durability: --allow-reboot was not supplied")
        await self.form_write("/settings/ui", self.ui_form)
        check(await self.get("/json/cfg") == self.cfg, "Configuration baseline differs after UI restoration")
        self.ui_dirty = False
        self.write_journal()

    async def disconnect_case(self):
        check(await self.read_file(self.temporary_path, allow_missing=True) is None, "Temporary transfer path unexpectedly exists")
        self.temporary_file_dirty = True
        self.write_journal()
        data = b"uncommitted transfer fixture" * 8
        identifier, budget = await self.begin_transfer("/ble/fs", {"path": self.temporary_path, "size": len(data), "sha256": hashlib.sha256(data).hexdigest()})
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 1, "data": "MTIz"}, (400,))
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 0, "data": "AA==="}, (400,))
        part = data[:min(budget, len(data) - 1)]
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 0, "data": base64.b64encode(part).decode("ascii")})
        await self.reconnect()
        await self.authenticate()
        await self.post("/ble/fs", {"op": "commit", "id": identifier}, (409,))
        self.transfer = None
        self.write_journal()
        check(await self.read_file(self.temporary_path, allow_missing=True) is None, "Disconnected transfer unexpectedly installed a file")
        self.temporary_file_dirty = False
        self.write_journal()

    async def pin_case(self):
        if not self.args.exercise_pin:
            self.report["skipped"].append("Temporary PIN: --exercise-pin was not supplied")
            return
        if self.initial_pin_required:
            self.report["skipped"].append("Temporary PIN: existing PIN preserved; only blank-PIN fixtures are changed")
            return
        self.test_pin = str(secrets.randbelow(9000) + 1000)
        self.pin_dirty = True
        self.journal.update(phase="temporary_pin", temporary_pin=self.test_pin, original_pin="",
                            restore_security_form=[("PIN", "")] + self.security_flags)
        self.write_journal()  # fsync recovery credential before changing protection
        await self.form_write("/settings/sec", [("PIN", self.test_pin)] + self.security_flags)
        await self.request("GET", "/json/cfg", expected=(401,))
        await self.request("GET", "/settings/s.js?p=6", expected=(401,))
        check((await self.get("/ble/auth")).get("pinRequired") is True, "Temporary settings PIN was not installed")
        wrong = str((int(self.test_pin) % 9000) + 1000)
        check(wrong != self.test_pin, "Unable to construct distinct test credential")
        await self.post("/ble/auth", {"pin": wrong}, (401,))
        await self.post("/ble/auth", {"pin": self.test_pin}, (429,))
        await self.authenticate()
        await self.post("/ble/auth", {"lock": True})
        await self.request("GET", "/json/cfg", expected=(401,))
        await self.authenticate()
        await self.reconnect()
        await self.request("GET", "/json/cfg", expected=(401,))
        await self.authenticate()
        if self.args.allow_reboot:
            await self.reboot()
            await self.request("GET", "/json/cfg", expected=(401,))
            await self.authenticate()
        else:
            self.report["skipped"].append("PIN reboot durability: --allow-reboot was not supplied")
        # Restore the temporary PIN last during shielded cleanup, after files/UI.

    async def run_case(self, name, operation):
        started = time.monotonic()
        record = {"name": name, "outcome": "running"}
        self.report["cases"].append(record)
        self.write_report()
        try:
            async with asyncio.timeout(self.args.case_timeout):
                await operation()
            record["outcome"] = "passed"
        except BaseException as error:
            record.update(outcome="incomplete" if isinstance(error, Incomplete) else "failed", error=error_label(error))
            raise
        finally:
            record["seconds"] = round(time.monotonic() - started, 3)
            self.write_report()

    async def cleanup(self):
        needs_recovery = self.library_dirty or self.ui_dirty or self.pin_dirty or self.runtime_dirty or self.transfer or self.temporary_file_dirty
        if not needs_recovery:
            self.report["cleanup"] = "not_needed"
            return
        if not self.client.is_connected:
            await self.reconnect()
        else:
            await self.verify_identity()
        await self.authenticate()
        if self.transfer:
            await self.post(self.transfer["endpoint"], {"op": "abort", "id": self.transfer["id"]}, (200, 409))
            self.transfer = None
            self.write_journal()
        if self.temporary_file_dirty:
            await self.post("/ble/fs", {"op": "delete", "path": self.temporary_path}, (200, 404))
            check(await self.read_file(self.temporary_path, allow_missing=True) is None, "Temporary transfer file could not be removed")
            self.temporary_file_dirty = False
            self.write_journal()
        await self.restore_library()
        if self.ui_dirty:
            await self.form_write("/settings/ui", self.ui_form)
            self.ui_dirty = False
            self.write_journal()
        if self.pin_dirty:
            # All other persistent mutations are restored before the PIN.
            await self.form_write("/settings/sec", [("PIN", "")] + self.security_flags)
            auth = await self.get("/ble/auth")
            check(auth.get("pinRequired") is False and auth.get("authorized") is True, "Original blank PIN was not restored")
        if self.args.allow_reboot:
            await self.reboot()
            # If temporary-PIN removal failed to persist, the journal still has
            # its credential and pin_dirty remains true for manual recovery.
            status = await self.get("/ble/auth")
            if self.pin_dirty:
                check(status.get("pinRequired") is False, "Blank PIN restoration did not survive reboot")
            await self.authenticate()
        check(await self.get("/json/cfg") == self.cfg, "Final configuration differs from the complete original baseline")
        security = (await self.request("GET", "/settings/s.js?p=6")).body
        for field in ("NO", "OW", "AO", "SU"):
            expected = "1" if (field, "on") in self.security_flags else "0"
            check(re.findall(r"d\.Sf\." + field + r"\.checked=([01]);", security) == [expected], "Security flags differ after restoration")
        self.pin_dirty = False
        self.write_journal()
        if self.runtime_dirty:
            payload = lighting_projection(self.state)
            # recv is derived from rgrp; preserve writable runtime UDP flags
            # without emitting a notification to other controllers.
            udp = {key: value for key, value in payload.pop("udpn", {}).items() if key != "recv"}
            payload.update(v=False, tt=0, udpn={**udp, "nn": True}, nl=copy.deepcopy(self.state.get("nl", {"on": False})))
            for segment in payload["seg"]:
                segment["fxdef"] = False
            await self.state_write(payload)
            check(lighting_projection(await self.get("/json/state")) == lighting_projection(self.state), "Runtime lighting baseline was not restored")
            self.runtime_dirty = False
        check(await self.read_file("/presets.json", allow_missing=True) == self.presets, "Final preset file differs from the exact original bytes")
        self.journal["phase"] = "restored"
        self.write_journal()
        self.report["cleanup"] = "restored_and_verified"

    async def execute(self):
        exit_code = 0
        try:
            async with asyncio.timeout(self.args.run_timeout):
                for name, operation in (("private_baseline_and_identity", self.setup),
                                        ("scene_rename_playlist_delete_and_exact_restore", self.presets_case),
                                        ("saved_ui_form_and_durability", self.ui_case),
                                        ("invalid_chunks_and_disconnect_cleanup", self.disconnect_case),
                                        ("blank_fixture_pin_protection", self.pin_case)):
                    await self.run_case(name, operation)
        except BaseException as error:
            exit_code = 130 if isinstance(error, (asyncio.CancelledError, KeyboardInterrupt)) else (2 if isinstance(error, Incomplete) else 1)
            self.report["error"] = error_label(error)
        finally:
            # A fresh task is not cancelled with the test. Drain it even if a
            # second cancellation arrives, under its independent finite budget.
            async def restore_and_disconnect():
                try:
                    async with asyncio.timeout(self.args.cleanup_timeout):
                        await self.cleanup()
                except BaseException as error:
                    self.report.update(cleanup="failed", cleanup_error=error_label(error))
                finally:
                    try:
                        await self.client.disconnect()
                    except BaseException as error:
                        self.report["disconnect_error"] = error_label(error)
            cleanup = asyncio.create_task(restore_and_disconnect())
            while not cleanup.done():
                try:
                    await asyncio.shield(cleanup)
                except asyncio.CancelledError:
                    exit_code = exit_code or 130
            await cleanup
            if self.report["cleanup"] == "failed" or "disconnect_error" in self.report:
                exit_code = exit_code or 1
            self.report["outcome"] = "passed" if exit_code == 0 else ("incomplete" if exit_code == 2 else "failed")
            self.report["hardware_validated"] = exit_code == 0
            self.report["recovery_needed"] = bool(self.library_dirty or self.ui_dirty or self.pin_dirty or self.runtime_dirty or self.transfer or self.temporary_file_dirty)
            self.report["recovery_journal"] = str(self.private / "recovery.json")
            self.report["coverage"] = "Selected BLE-only cases; no independent state oracle, power-cut or low-space certification."
            self.write_report()
        print(json.dumps(self.report, indent=2))
        return exit_code


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--address", required=True, help="Previously identified Bluetooth peripheral UUID")
    parser.add_argument("--expected-mac", required=True, help="WLED MAC independently observed by the operator over USB")
    parser.add_argument("--output", type=Path, required=True, help="New private run directory; existing paths are rejected")
    parser.add_argument("--settings-pin-env", help="Environment variable containing an existing settings PIN; never replaced")
    parser.add_argument("--allow-reboot", action="store_true", help="Enable device reboots and restoration persistence verification")
    parser.add_argument("--exercise-pin", action="store_true", help="Temporarily protect only an initially blank-PIN fixture; journal recovery credential first")
    parser.add_argument("--pair", action="store_true", help="Request system pairing on Linux/Windows")
    parser.add_argument("--commission", action="store_true", help="Allow manual first-time macOS pairing (still bounded)")
    parser.add_argument("--chunk-size", type=int, default=244)
    parser.add_argument("--timeout", type=float, default=30)
    parser.add_argument("--connect-timeout", type=float, default=90)
    parser.add_argument("--case-timeout", type=float, default=300)
    parser.add_argument("--cleanup-timeout", type=float, default=600)
    parser.add_argument("--run-timeout", type=float, default=1800)
    args = parser.parse_args()
    for name in ("timeout", "connect_timeout", "case_timeout", "cleanup_timeout", "run_timeout"):
        if not math.isfinite(getattr(args, name)) or getattr(args, name) <= 0:
            parser.error(name + " must be positive and finite")
    if args.settings_pin_env and (len(os.environ.get(args.settings_pin_env, "")) != 4):
        parser.error("The selected settings PIN environment variable must contain exactly four characters")
    return args


async def main(args):
    # Construct Core Bluetooth clients only after the event loop is running.
    return await PersistenceHil(args).execute()


if __name__ == "__main__":
    try:
        arguments = parse_args()
        sys.exit(asyncio.run(main(arguments)))
    except (HarnessError, FileExistsError) as error:
        print("Persistence harness setup failed: " + error_label(error), file=sys.stderr)
        sys.exit(2)
# AI: end
