#!/usr/bin/env python3
"""BLE-only API 2 smoke test. Uses one unique temporary file and no Wi-Fi oracle."""
# AI: below section was generated by an AI
import argparse
import asyncio
import base64
import getpass
import hashlib
import json
import pathlib
import sys
import uuid

from client_example import BleApiBridgeClient


def check(condition, message):
    if not condition:
        raise AssertionError(message)


class ParitySmoke:
    def __init__(self, client):
        self.client = client
        self.path = "/ble-parity-" + uuid.uuid4().hex + ".bin"
        self.transfer = None
        self.file_created = False
        self.chunk = 0
        self.completed = []

    async def request(self, method, path, body=None, status=200):
        encoded = "" if body is None else json.dumps(body, separators=(",", ":"))
        response = await self.client.request(method, path, encoded)
        check(response.status == status, f"{method} {path} returned {response.status}, expected {status}")
        return response

    async def post(self, endpoint, body, status=200):
        return (await self.request("POST", endpoint, body, status)).json()

    async def read_file(self):
        result = bytearray()
        revision = None
        total = None
        while True:
            payload = {"op": "read", "path": self.path, "offset": len(result), "length": self.chunk}
            if revision is not None:
                payload["revision"] = revision
            reply = await self.post("/ble/fs", payload)
            part = base64.b64decode(reply["data"], validate=True)
            check(reply["offset"] == len(result), "Incorrect read offset")
            check(reply["next"] == len(result) + len(part), "Incorrect read acknowledgement")
            check(total is None or total == reply["size"], "File size changed")
            check(revision is None or revision == reply["revision"], "File revision changed")
            revision, total = reply["revision"], reply["size"]
            result.extend(part)
            check(len(result) <= total and (part or len(result) == total), "Invalid read progress")
            check(reply["eof"] == (len(result) == total), "Incorrect end-of-file flag")
            if len(result) == total:
                break
        check(hashlib.sha256(result).hexdigest() == revision, "Reconstructed file checksum mismatch")
        return bytes(result)

    async def begin(self, data, endpoint="/ble/fs", digest=None):
        payload = {"op": "begin", "path": self.path, "size": len(data),
                   "sha256": digest or hashlib.sha256(data).hexdigest()}
        if endpoint == "/ble/request":
            payload.update(path="/json/state", method="POST", contentType="application/json")
        reply = await self.post(endpoint, payload)
        check(isinstance(reply["id"], str) and reply["id"], "Missing transfer identifier")
        check(0 < reply["maxChunk"] <= self.chunk, "Unexpected transfer chunk budget")
        self.transfer = (endpoint, reply["id"])
        return reply["id"], reply["maxChunk"]

    async def write(self, data, endpoint="/ble/fs", digest=None, expected=200):
        identifier, budget = await self.begin(data, endpoint, digest)
        for offset in range(0, len(data), budget):
            part = data[offset:offset + budget]
            reply = await self.post(endpoint, {"op": "write", "id": identifier, "offset": offset,
                                               "data": base64.b64encode(part).decode("ascii")})
            check(reply["id"] == identifier and reply["next"] == offset + len(part), "Incorrect write acknowledgement")
        if endpoint == "/ble/fs":
            self.file_created = True  # a lost commit reply may still have installed this file
        receipt = await self.post(endpoint, {"op": "commit", "id": identifier}, expected)
        self.transfer = None
        if endpoint == "/ble/fs" and expected == 200:
            self.file_created = True
            check(receipt.get("saved") is True and receipt.get("success") is True, "Missing persistence receipt")
            check(receipt["size"] == len(data) and receipt["sha256"] == hashlib.sha256(data).hexdigest(),
                  "Incorrect commit checksum or size")
        return receipt

    async def abort(self):
        if self.transfer:
            endpoint, identifier = self.transfer
            await self.post(endpoint, {"op": "abort", "id": identifier})
            self.transfer = None

    async def run(self, pin=None):
        capabilities = (await self.request("GET", "/ble/capabilities")).json()
        check(capabilities.get("version") == 2, "Firmware does not provide API 2")
        self.chunk = capabilities["maxChunk"]
        check(isinstance(self.chunk, int) and 0 < self.chunk <= 1024, "Invalid chunk budget")
        if capabilities.get("pinRequired"):
            check(pin is not None, "Settings PIN required; rerun with --ask-pin")
            await self.post("/ble/auth", {"pin": pin})
        auth = (await self.request("GET", "/ble/auth")).json()
        check(auth.get("authorized") is True, "Settings authorization failed")
        self.completed.append("capabilities_and_authorization")

        for path in ("/json", "/json/si", "/json/palettes", "/json/palx?page=0", "/json/fxdata",
                     "/json/live", "/json/pins", "/json/cfg", "/json/nodes", "/ble/status"):
            response = await self.request("GET", path)
            check(isinstance(response.json(), (dict, list)), f"Invalid JSON at {path}")
        for page in (0, 1, 2, 3, 4, 5, 6, 8):
            response = await self.request("GET", f"/settings/s.js?p={page}")
            check("function GetV()" in response.body, f"Missing settings script for page {page}")
        self.completed.append("catalogs_live_configuration_and_settings_scripts")

        original = bytes(range(256)) * 9 + b"BLE-only parity fixture"
        await self.write(original)
        check(await self.read_file() == original, "Committed file readback differs")
        self.completed.append("chunked_file_commit_and_readback")

        await self.write(original + b"bad", digest="0" * 64, expected=422)
        check(await self.read_file() == original, "Bad checksum replaced original file")
        self.completed.append("checksum_failure_preserves_original")

        identifier, _ = await self.begin(b"123456")
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 1, "data": "MTIz"}, 400)
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 0, "data": "AA==="}, 400)
        await self.post("/ble/fs", {"op": "write", "id": identifier, "offset": 0, "data": "MTIz"})
        await self.abort()
        check(await self.read_file() == original, "Aborted transfer replaced original file")
        self.completed.append("invalid_chunks_and_abort_preserve_original")

        baseline = (await self.request("GET", "/json/state")).json()
        payload = json.dumps({"v": True, "_bleParityPadding": "x" * (self.client.max_request_bytes + 32)},
                             separators=(",", ":")).encode("utf-8")
        receipt = await self.write(payload, endpoint="/ble/request")
        state = receipt.get("state", receipt)
        check(all(state.get(key) == baseline.get(key) for key in ("on", "bri", "mainseg")),
              "Staged no-op request changed stable lighting state")
        self.completed.append("large_staged_state_request")

        await self.post("/ble/fs", {"op": "delete", "path": self.path})
        self.file_created = False
        await self.post("/ble/fs", {"op": "read", "path": self.path, "offset": 0, "length": 1}, 404)
        self.completed.append("temporary_file_deleted")

    async def cleanup(self):
        if not self.client.is_connected:
            return
        await self.abort()
        if self.file_created:
            response = await self.client.request("POST", "/ble/fs", json.dumps({"op": "delete", "path": self.path}, separators=(",", ":")))
            check(response.status in (200, 404), "Temporary file cleanup failed")
            self.file_created = False


async def main(args):
    # Do not pass a PIN as a command-line argument or record it in a report.
    pin = getpass.getpass("WLED settings PIN: ") if args.ask_pin else None
    client = BleApiBridgeClient(args.address, chunk_size=args.chunk_size, timeout=args.timeout,
                               commission=args.commission, connect_timeout=110 if args.commission else 90)
    smoke = ParitySmoke(client)
    report = {"suite": "ble-api2-parity", "passed": False, "checks": smoke.completed}
    try:
        await client.connect(pair=args.pair)
        await client.refresh_capabilities()
        await smoke.run(pin)
        report["passed"] = True
    except Exception as error:
        report["error"] = str(error)
    finally:
        try:
            await smoke.cleanup()
        except Exception as error:
            report["cleanupError"] = str(error)
            report["passed"] = False
        if smoke.file_created:
            report["temporaryFileToRemove"] = smoke.path
        try:
            await client.disconnect()
        except Exception as error:
            report["disconnectError"] = str(error)
            report["passed"] = False
        args.output.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--address", required=True)
    parser.add_argument("--ask-pin", action="store_true", help="Prompt privately for the separate four-digit settings PIN")
    parser.add_argument("--pair", action="store_true", help="Request system pairing (Linux/Windows)")
    parser.add_argument("--commission", action="store_true", help="Allow initial macOS system pairing up to 110 seconds")
    parser.add_argument("--chunk-size", type=int, default=244)
    parser.add_argument("--timeout", type=float, default=120)
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("/tmp/wled-ble-parity-report.json"))
    sys.exit(asyncio.run(main(parser.parse_args())))
# AI: end
