#!/usr/bin/env python3
"""Opt-in software reboot recovery tests over BLE plus independently verified HTTP."""
# AI: below section was generated by an AI
import argparse
import asyncio
import json
import sys
import time
import urllib.error
import urllib.request

import client_example as bridge
from hil_runner import CoverageMissing, HilRunner, HttpOracle, check, mac_identity, safe_error
from hil_runner import parse_args as base_parse_args


class TxProbe:
    """Observe packet lengths only; retain no response payload or configuration data."""
    def __init__(self):
        self.first_chunk = asyncio.Event()
        self.expected = None
        self.received = 0

    def observe(self, data):
        if self.expected is None:
            if len(data) < 2:
                return
            self.expected = int.from_bytes(data[:2], "little")
            self.received = len(data) - 2
            self.first_chunk.set()
        else:
            self.received += len(data)

    @property
    def incomplete(self):
        return self.expected is not None and self.received < self.expected


class ObservedClient(bridge.BleApiBridgeClient):
    """Keep the production client behavior while exposing a test-only first-TX signal."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.tx_probe = None

    def _on_tx(self, characteristic, data, generation=None):
        if generation is None or generation == self._generation:
            if self.tx_probe is not None:
                self.tx_probe.observe(data)
        super()._on_tx(characteristic, data, generation)


class RebootHttp(HttpOracle):
    """The sole mutation is WLED's existing /reset route, with no configuration writes."""
    async def reboot(self):
        return await asyncio.to_thread(self._reboot)

    def _reboot(self):
        class NoRedirect(urllib.request.HTTPRedirectHandler):
            def redirect_request(self, *args, **kwargs):
                return None
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
        with opener.open(self.url + "/reset", timeout=self.timeout) as response:
            check(response.status == 200, "HTTP reset returned an unexpected status")
            # The route returns HTML; neither its content nor a successful reply proves reboot.
            response.read(1)
        return 200


class RebootHilRunner(HilRunner):
    """Verify restart evidence before accepting an expected uptime rollback."""
    def __init__(self, args, client_factory=None, oracle=None):
        super().__init__(args, client_factory or ObservedClient,
                         oracle or RebootHttp(args.http_url, min(args.timeout, 3)))
        self.expected_reboots = []

    async def before_reset(self):
        """Authenticate both identities before arming an injection on the current connection."""
        info = await self.request("GET", "/json/info")
        check(mac_identity(info) == self.identity, "BLE identity changed before reboot")
        snapshot = await self.oracle_snapshot()
        uptime = snapshot["info"].get("uptime")
        check(type(uptime) is int, "Independent uptime missing before reboot")
        # Integer-second uptime cannot prove a second reboot immediately after boot.
        # Wait a bounded warm-up so even a fast reboot gives unambiguous boot-epoch evidence.
        if uptime < 5:
            await asyncio.sleep(6 - uptime)
            snapshot = await self.oracle_snapshot()
            uptime = snapshot["info"].get("uptime")
            check(type(uptime) is int and uptime >= 5, "Uptime did not advance before reboot")
            check(mac_identity(await self.request("GET", "/json/info")) == self.identity,
                  "BLE identity changed during reboot warm-up")
        check(self.client.client.is_connected, "BLE disconnected before reboot injection")
        return {"uptime": uptime, "observed_at": time.monotonic(), "client": self.client}

    async def reboot_and_recover(self, before):
        """Require link loss, a newer boot epoch, matching identity, and fresh BLE requests."""
        old = before["client"]
        check(old is self.client and old.client.is_connected, "Reboot target connection changed before injection")
        dispatched = time.monotonic()
        acknowledgement = "HTTP 200"
        try:
            await asyncio.wait_for(self.oracle.reboot(), 5)
        except (ConnectionError, TimeoutError, OSError) as error:
            if isinstance(error, urllib.error.HTTPError):
                raise
            # Reboot can close the HTTP response; actual restart evidence remains mandatory.
            acknowledgement = "Reply unavailable: " + safe_error(error)
        drop_deadline = time.monotonic() + self.args.disconnect_deadline
        while old.client.is_connected and time.monotonic() < drop_deadline:
            await asyncio.sleep(0.1)
        check(not old.client.is_connected, "HTTP reset did not disconnect the old BLE link")

        deadline = dispatched + self.args.reboot_timeout
        proof = None
        last_error = None
        while time.monotonic() < deadline:
            try:
                snapshot = await asyncio.wait_for(self.oracle_snapshot(), min(4, max(0.1, deadline - time.monotonic())))
                now = time.monotonic()
                uptime = snapshot["info"].get("uptime")
                check(type(uptime) is int, "Independent uptime missing after reboot")
                elapsed = now - before["observed_at"]
                epoch_shift = before["uptime"] + elapsed - uptime
                # One-second rounding gets two seconds of allowance. A plain BLE drop
                # or HTTP reply cannot excuse an unrelated uptime rollback.
                if uptime <= now - dispatched + 2 and epoch_shift >= 2:
                    proof = {"before_uptime_s": before["uptime"], "after_uptime_s": uptime,
                             "recovery_s": round(now - dispatched, 3),
                             "boot_epoch_shift_s": round(epoch_shift, 3),
                             "reset_acknowledgement": acknowledgement}
                    break
            except AssertionError:
                raise  # An identity mismatch must never be retried into a passing result.
            except Exception as error:
                last_error = safe_error(error)
            await asyncio.sleep(min(0.5, max(0, deadline - time.monotonic())))
        check(proof is not None, "No verified HTTP restart before recovery deadline" +
              (f" ({last_error})" if last_error else ""))

        await self.connect()
        info = await self.request("GET", "/json/info")
        check(mac_identity(info) == self.identity, "BLE recovered onto an unexpected device")
        check(type(info.get("uptime")) is int, "Recovered BLE uptime missing")
        check(info["uptime"] <= time.monotonic() - dispatched + 2, "Recovered BLE does not report the requested boot")
        proof["ble_recovery_s"] = round(time.monotonic() - dispatched, 3)
        self.expected_reboots.append(proof)
        # Clear the monotonic guard only after independently proving this requested reboot.
        self.previous_uptime = None
        await self.sample()
        await self.independent_control()
        return proof

    async def idle_reset(self):
        return await self.reboot_and_recover(await self.before_reset())

    async def partial_rx_reset(self):
        before = await self.before_reset()
        await asyncio.wait_for(self.client.client.write_gatt_char(
            bridge.RX_UUID, b"\x20\x00GET /json", response=True), self.args.timeout)
        # No complete request exists; the first GET after reboot must not inherit these bytes.
        return await self.reboot_and_recover(before)

    async def long_tx_reset(self):
        """Reset only after an incomplete TX frame; a missed injection remains a coverage gap."""
        misses = 0
        for _ in range(2):
            before = await self.before_reset()
            client = self.client
            probe = TxProbe()
            client.tx_probe = probe
            pending = asyncio.create_task(self.request("GET", "/json/fxdata"))
            try:
                await asyncio.wait_for(probe.first_chunk.wait(), self.args.timeout)
                if pending.done() or not probe.incomplete:
                    await pending  # Preserve a real request error instead of hiding it as a missed injection.
                    misses += 1
                    continue
                bytes_at_dispatch = probe.received
                proof = await self.reboot_and_recover(before)
                try:
                    await asyncio.wait_for(pending, self.args.timeout + 5)
                except ConnectionError:
                    proof["response_bytes_expected"] = probe.expected
                    proof["response_bytes_received_at_dispatch"] = bytes_at_dispatch
                    proof["missed_injections_before_success"] = misses
                    return proof
                misses += 1
            finally:
                client.tx_probe = None
                if not pending.done():
                    pending.cancel()
                await asyncio.gather(pending, return_exceptions=True)
        raise CoverageMissing("Long TX completed before reset in both bounded attempts; response interruption unproven")

    def write_reports(self):
        super().write_reports()
        path = self.output / "results.json"
        result = json.loads(path.read_text())
        result["expected_reboots"] = self.expected_reboots
        result["coverage_limits"] = [
            "Software reboot through HTTP only; no power cut, USB reset or recovery from a wedged MCU",
            "Existing system bond only; no bond deletion, re-pairing or pairing-code changes",
            "Long response interruption requires an incomplete first TX frame and disconnect failure",
            "Configuration persistence, LED output and iOS behavior are outside this suite",
        ]
        path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        report = self.output / "report.md"
        text = report.read_text().split("## Coverage limits", 1)[0]
        report.write_text(text + "## Coverage limits\n\n" + "\n".join("- " + item for item in result["coverage_limits"]) + "\n")

    async def run(self):
        try:
            if await self.case("reboot_setup", self.setup,
                               timeout=self.args.connect_timeout + self.args.timeout * 5 + 15, recover=False):
                for name, operation in (("idle_bonded_reboot", self.idle_reset),
                                        ("partial_rx_reboot", self.partial_rx_reset),
                                        ("in_flight_tx_reboot", self.long_tx_reset)):
                    timeout = self.args.reboot_timeout + self.args.connect_timeout + self.args.timeout * 8 + 20
                    if name == "in_flight_tx_reboot":
                        timeout *= 2
                    passed = await self.case(name, operation, timeout=timeout, recover=True)
                    if not passed and self.records[-1]["status"] == "fail":
                        break
        except asyncio.CancelledError:
            self.records.append({"name": "interruption", "status": "fail", "detail": "Run interrupted", "duration_s": 0})
            raise
        finally:
            await self.case("restore_baseline", self.restore,
                            timeout=self.args.connect_timeout + self.args.timeout * 3 + 10, recover=False)
            if self.baseline is not None and self.previous_uptime is not None:
                await self.case("final_health", self.sample, recover=False)
            await self.case("disconnect", self.disconnect, timeout=12, recover=False)
            await self.case("close_oracle", self.oracle.close, timeout=self.args.timeout + 3, recover=False)
            self.write_reports()
        return self.exit_code()


def parse_args(argv=None):
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--allow-reboot-tests", action="store_true")
    parser.add_argument("--reboot-timeout", type=float, default=45)
    parser.add_argument("--disconnect-deadline", type=float, default=10)
    special, remaining = parser.parse_known_args(argv)
    args = base_parse_args(remaining)
    if not special.allow_reboot_tests:
        parser.error("--allow-reboot-tests is required to execute software reboots")
    if not args.http_url or args.serial_port:
        parser.error("Reboot recovery requires --http-url and no --serial-port")
    for name in ("reboot_timeout", "disconnect_deadline"):
        if not 0 < getattr(special, name) <= 120:
            parser.error(f"--{name.replace('_', '-')} must be positive and at most 120 seconds")
    vars(args).update(vars(special))
    args.suite = "reboot"
    return args


async def main(argv=None):
    return await RebootHilRunner(parse_args(argv)).run()


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(130)
# AI: end
