// AI: below section was generated by an AI
#include "../wled00/file_transaction.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <map>
#include <memory>
#include <string>
#include <vector>

enum class Failure { None, Read, CopyWrite, CopyClose, MutationWrite, MutationClose, VerifyOpen, Rename };
struct FakeFS;
struct FakeFile {
  FakeFS* fs = nullptr;
  std::shared_ptr<std::vector<uint8_t>> bytes;
  std::string path;
  size_t position = 0;
  bool active = false;
  explicit operator bool() const { return active; }
  size_t size() const { return active ? bytes->size() : 0; }
  size_t read(uint8_t* buffer, size_t count);
  size_t write(const uint8_t* buffer, size_t count);
  void flush() {}
  void close();
};

struct FakeFS {
  std::map<std::string, std::shared_ptr<std::vector<uint8_t>>> files;
  Failure failure = Failure::None;
  bool mutation = false;
  int handles = 0;
  bool exists(const char* path) const { return files.count(path); }
  void put(const char* path, const std::string& value) {
    files[path] = std::make_shared<std::vector<uint8_t>>(value.begin(), value.end());
  }
  std::string get(const char* path) const {
    auto data = files.at(path);
    return std::string(data->begin(), data->end());
  }
  FakeFile open(const char* path, const char* mode) {
    if (mutation && failure == Failure::VerifyOpen && std::strcmp(mode, "r") == 0) return {};
    if (std::strcmp(mode, "w") == 0) put(path, "");
    if (!exists(path)) return {};
    handles++;
    return {this, files[path], path, 0, true};
  }
  bool remove(const char* path) { return files.erase(path); }
  bool rename(const char* source, const char* destination) {
    assert(handles == 0); // All buffers must have been flushed and closed.
    if (failure == Failure::Rename) return false;
    files[destination] = files.at(source);
    files.erase(source);
    return true;
  }
};

size_t FakeFile::read(uint8_t* buffer, size_t count) {
  if (fs->failure == Failure::Read && path == "/presets.json") return 0;
  count = std::min(count, bytes->size() - position);
  std::copy_n(bytes->data() + position, count, buffer);
  position += count;
  return count;
}

size_t FakeFile::write(const uint8_t* buffer, size_t count) {
  if ((!fs->mutation && fs->failure == Failure::CopyWrite) ||
      (fs->mutation && fs->failure == Failure::MutationWrite)) count /= 2;
  bytes->insert(bytes->end(), buffer, buffer + count);
  return count;
}

void FakeFile::close() {
  if (!active) return;
  if (path == "/presets.json.tmp" &&
      ((!fs->mutation && fs->failure == Failure::CopyClose) ||
       (fs->mutation && fs->failure == Failure::MutationClose))) bytes->clear();
  active = false;
  fs->handles--;
}

static bool perform(FakeFS& fs, const std::string& replacement) {
  return replaceFileTransactionally(fs, "/presets.json", "/presets.json.tmp",
      [&](const char* path, size_t& expected) {
        fs.mutation = true;
        auto output = fs.open(path, "w");
        const size_t written = output.write(reinterpret_cast<const uint8_t*>(replacement.data()), replacement.size());
        output.flush();
        expected = output.size();
        output.close();
        return written == replacement.size();
      });
}

int main() {
  const std::string original = "{\"0\":{},\"1\":{\"n\":\"Original scene\",\"data\":\"" + std::string(800, 'a') + "\"}}";
  const std::string replacement = "{\"0\":{},\"1\":{\"n\":\"Renamed scene\"}}";
  for (Failure failure : {Failure::Read, Failure::CopyWrite, Failure::CopyClose, Failure::MutationWrite,
                          Failure::MutationClose, Failure::VerifyOpen, Failure::Rename}) {
    FakeFS fs;
    fs.put("/presets.json", original);
    fs.failure = failure;
    assert(!perform(fs, replacement));
    assert(fs.get("/presets.json") == original);
    assert(!fs.exists("/presets.json.tmp"));
    assert(fs.handles == 0);
  }
  FakeFS fs;
  fs.put("/presets.json", original);
  assert(perform(fs, replacement));
  assert(fs.get("/presets.json") == replacement);
  assert(!fs.exists("/presets.json.tmp"));
  assert(fs.handles == 0);
  FakeFS empty;
  assert(perform(empty, replacement));
  assert(empty.get("/presets.json") == replacement);
}
// AI: end
