// AI: below section was generated by an AI
#include "../ble_bridge_protocol.h"
#include <algorithm>
#include <cassert>
#include <cstdio>
#include <random>
#include <vector>
using ble_api_bridge::FrameAssembly;

int main() {
  std::mt19937 random(1701);
  size_t cases = 0;
  // Every boundary around an ATT packet, including the maximum request accepted by firmware.
  for (size_t budget : {size_t(3), size_t(20), size_t(65), size_t(180), size_t(182), size_t(244)}) {
    for (size_t length = 1; length <= 4096; ++length) {
      std::vector<uint8_t> payload(length), framed;
      for (auto& byte : payload) byte = random() & 255;
      framed.push_back(length & 255);
      framed.push_back(length >> 8);
      framed.insert(framed.end(), payload.begin(), payload.end());
      // Canary bytes detect writes beyond the assembly's advertised capacity.
      std::vector<uint8_t> output(length + 2, 0xa5);
      FrameAssembly assembly;
      for (size_t offset = 0; offset < framed.size(); offset += budget) {
        const size_t count = std::min(budget, framed.size() - offset);
        assert(assembly.append(framed.data() + offset, count, output.data() + 1, length, uint32_t(offset)));
      }
      assert(assembly.ready && !assembly.active && assembly.received == length);
      assert(std::equal(payload.begin(), payload.end(), output.begin() + 1));
      assert(output.front() == 0xa5 && output.back() == 0xa5);
      assert(!assembly.append(framed.data(), 3, output.data(), length, 0));
      ++cases;
    }
  }
  uint8_t buffer[4096] = {};
  for (auto invalid : {std::vector<uint8_t>{}, {1}, {0, 0}, {1, 0, 1, 2}, {1, 16}, {255, 255}}) {
    FrameAssembly assembly;
    assert(!assembly.append(invalid.data(), invalid.size(), buffer, sizeof(buffer), 0));
  }
  FrameAssembly assembly;
  uint8_t first[] = {4, 0, 'G'};
  assert(assembly.append(first, sizeof(first), buffer, sizeof(buffer), UINT32_MAX - 100));
  assert(!assembly.expired(100, 1000));
  assert(assembly.expired(1000, 1000));
  uint8_t rest[] = {'E', 'T', ' '};
  assert(assembly.append(rest, sizeof(rest), buffer, sizeof(buffer), 2000));
  assert(!assembly.expired(30000, 1000));
  assert(memcmp(buffer, "GET ", 4) == 0);
  printf("Passed %zu framing round trips, malformed frames, bounds canaries, and timer wraparound.\n", cases);
}
// AI: end
