// AI: below section was generated by an AI
#include "../ble_bridge_storage_protocol.h"
#include <cassert>
#include <cstdio>
#include <limits>
#include <string>
#include <vector>

using namespace ble_api_bridge;
int main() {
  for (const char* valid : {"/presets.json", "/palette0.json", "/cfg.json", "/tools/my-tool.htm", "/été.json"}) assert(validFilePath(valid));
  for (const char* invalid : {"", "/", "cfg.json", "/../cfg.json", "/foo/../x", "/.ble-transfer", "/foo//x", "/wsec.json", "/backup.WSEC.json", "/x\\wsec.json", "/x%2fy", "/x?foo", "/x#foo", "/x\ny", "/x/"}) assert(!validFilePath(invalid));
  assert(validFilePath(("/" + std::string(253, 'x')).c_str()));
  assert(!validFilePath(("/" + std::string(254, 'x')).c_str()));
  assert(validDigest(std::string(64, 'a').c_str()));
  assert(!validDigest(std::string(65, 'a').c_str()));
  assert(!validDigest(std::string(64, 'g').c_str()));
  assert(validTransferRange(1024, 1024, 1024, 2048));
  assert(!validTransferRange(1024, 1025, 1024, 2048));
  assert(!validTransferRange(1024, 1, 0, 2048));
  assert(!validTransferRange(std::numeric_limits<size_t>::max(), 1, std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max()));
  for (const auto& sample : std::vector<std::pair<std::string, std::string>>{{"", ""}, {"Zg==", "f"}, {"Zm8=", "fo"}, {"Zm9v", "foo"}, {"Zm9vYmFy", "foobar"}}) {
    uint8_t bytes[10] = {};
    size_t count = 99;
    assert(decodeBase64(sample.first.c_str(), bytes, sizeof(bytes), count));
    assert(std::string(reinterpret_cast<char*>(bytes), count) == sample.second);
  }
  for (const char* invalid : {"Zg=", "Zg===", "Zh==", "Zm9=", "Zg==AAAA", "Zm\n9v", "Zm-v", "====", "AA=A", "=AAA"}) {
    uint8_t bytes[16] = {};
    size_t count;
    assert(!decodeBase64(invalid, bytes, sizeof(bytes), count));
  }
  uint8_t canary[] = {0xaa, 0xbb, 0xcc, 0xdd};
  size_t count;
  assert(!decodeBase64("Zm9v", canary+1, 2, count));
  assert(canary[0] == 0xaa && canary[3] == 0xdd);
  puts("Passed storage path, range, canonical base64 and overflow guards");
}
// AI: end
