"""Functional-harness restoration and assertion tests; no real device is accessed."""
# AI: below section was generated by an AI
import copy
import json
import pathlib
import sys
import tempfile
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import api_hil as api
import client_example as bridge
from test_hil_runner import FakeClient, FakeDevice, FakeOracle


class ApiDevice(FakeDevice):
    """Model the particular WLED side effects the functional harness must restore."""
    def __init__(self):
        super().__init__()
        self.state.update(ps=-1, pl=-1, nl={"on": False}, mainseg=0)
        template = {"on": False, "bri": 147, "sel": False, "frz": True,
                    "fx": 2, "sx": 65, "ix": 79, "pal": 2, "lc": 3,
                    "start": 0, "stop": 30, "len": 30, "grp": 1, "spc": 0, "of": 0,
                    "m12": 0, "si": 0, "rev": False, "mi": False, "cct": 127,
                    "set": 0, "c1": 10, "c2": 20, "c3": 3, "o1": False,
                    "o2": True, "o3": False, "bm": 0}
        self.state["seg"][0].update(template)
        other = copy.deepcopy(self.state["seg"][0])
        other.update(id=1, start=30, stop=60, sel=True, fx=0, sx=11)
        self.state["seg"].append(other)
        self.info.update(fxcount=4, palcount=200, live=False)
        self.effect_names = ["Solid", "Blink", "Breathe", "RSVD"]
        self.effect_data = ["", "!,Duty cycle;!,!;!;01", "!;!,!;!;01", ""]
        self.palette_names = ["Default", "Random", "Color 1", "Colors 1&2", "Colors 1&2&3", "Color Gradient", "Party"]
        self.fail_effect_ack = False

    def snapshot(self):
        return {**super().snapshot(), "palettes": list(self.palette_names)}

    def update(self, update):
        self.posts.append(copy.deepcopy(update))
        if "bri" in update:
            if update["bri"] == 0:
                self.state["on"] = False
            elif update["bri"] > 0:
                self.state["bri"] = update["bri"]
                self.state["on"] = True
        was_on = self.state["on"]
        if "on" in update:
            self.state["on"] = update["on"]
        if self.state["on"] and not was_on:
            for segment in self.state["seg"]:
                segment["frz"] = False
        for change in update.get("seg", []):
            segment = next(item for item in self.state["seg"] if item["id"] == change["id"])
            if "bri" in change:
                if change["bri"] > 0:
                    segment["bri"] = change["bri"]
                segment["on"] = change["bri"] > 0
            for key in ("on", "sel", "frz", "fx", "sx", "ix", "pal"):
                if key in change and not (key in ("sx", "ix") and change[key] < 0):
                    segment[key] = change[key]
            if "fx" in change:
                if change.get("fxdef", False):
                    segment.update(sx=128, ix=128, m12=1, c1=128)
            for index, color in enumerate(change.get("col", [])):
                old = segment["col"][index]
                if isinstance(color, dict):
                    segment["col"][index] = [color.get(key, old[channel]) for channel, key in enumerate(("r", "g", "b", "w")[:len(old)])]
                elif isinstance(color, str):
                    segment["col"][index] = [int(color[start:start + 2], 16) for start in (0, 2, 4)] + ([0] if len(old) == 4 else [])
                elif color:
                    segment["col"][index] = list(color)
        if self.subscribed:
            self.live.append(self.snapshot())


class ApiClient(FakeClient):
    async def request(self, method, path, body=""):
        if method.upper() == "GET" and path in ("/json/effects", "/json/fxdata"):
            value = self.device.effect_names if path == "/json/effects" else self.device.effect_data
            return bridge.BridgeResponse(200, "application/json", json.dumps(value))
        response = await super().request(method, path, body)
        if method.upper() == "POST" and self.device.fail_effect_ack:
            if any("fx" in segment for segment in json.loads(body).get("seg", [])):
                self.device.fail_effect_ack = False
                raise ConnectionError("WLED disconnected")
        return response


class ApiTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.args = api.parse_args(["--address", "test", "--http-url", "http://test", "--output", self.directory.name])
        self.device = ApiDevice()

    def runner(self, oracle=None):
        return api.ApiHilRunner(self.args, client_factory=lambda _address, **kwargs: ApiClient(self.device, **kwargs),
                                oracle=oracle or FakeOracle(self.device))

    async def test_all_named_scenarios_restore_every_touched_field_and_geometry(self):
        original = copy.deepcopy(self.device.state)
        runner = self.runner()
        self.assertEqual(await runner.run(), 0)
        self.assertEqual(self.device.state, original)
        for update in self.device.posts:
            self.assertEqual(update["udpn"], {"nn": True})
            self.assertNotIn("psave", update)
            self.assertNotIn("playlist", update)
            for segment in update.get("seg", []):
                self.assertIn("id", segment)
                self.assertFalse(set(segment) & {"start", "stop", "len", "grp", "spc", "m12"})
                if "fx" in segment:
                    self.assertFalse(segment["fxdef"])
        self.assertEqual([row["name"] for row in runner.records if row["name"] in dict(api.SCENARIOS)],
                         [name for name, _ in api.SCENARIOS])
        self.assertTrue(all(row["detail"] for row in runner.records if row["name"] in dict(api.SCENARIOS)))
        result = json.loads((pathlib.Path(self.directory.name) / "results.json").read_text())
        self.assertEqual(result["lifecycle"], "finished")
        self.assertEqual(result["outcome"], "passed_selected_coverage")

    async def test_lost_mutation_ack_preserves_failure_and_restores_state(self):
        original = copy.deepcopy(self.device.state)
        self.device.fail_effect_ack = True
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.state, original)
        failure = next(row for row in runner.records if row["name"] == "api_effect_selection")
        self.assertEqual(failure["status"], "fail")
        self.assertEqual(failure["recovery"][0]["status"], "pass")

    async def test_active_preset_is_skipped_without_state_mutation(self):
        self.device.state["ps"] = 7
        runner = self.runner()
        self.assertEqual(await runner.run(), 2)
        self.assertEqual(self.device.posts, [])

    async def test_wrong_http_identity_blocks_all_mutations(self):
        wrong = ApiDevice()
        wrong.info["mac"] = "112233445566"
        runner = self.runner(FakeOracle(wrong))
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.posts, [])
        self.assertEqual(wrong.posts, [])

    async def test_fx_defaults_cannot_change_mapping_unnoticed(self):
        runner = self.runner()
        await runner.setup_api()
        self.device.state["seg"][0]["m12"] = 1
        with self.assertRaisesRegex(AssertionError, "invariant m12"):
            await runner.verify_state({})
        await runner.disconnect()

    async def test_palette_selection_uses_fixed_names_not_total_palette_count(self):
        runner = self.runner()
        await runner.setup_api()
        self.assertEqual([index for index, _ in runner.palettes], [0, 2, 6])
        self.assertNotIn(self.device.info["palcount"] - 1, [index for index, _ in runner.palettes])
        await runner.disconnect()

    async def test_inconsistent_effect_arrays_fail_before_mutation(self):
        self.device.effect_names.pop()
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.posts, [])

    async def test_unexpected_http_state_cannot_pass_ble_readback(self):
        oracle = FakeOracle(self.device)
        runner = self.runner(oracle)
        await runner.setup_api()
        original = oracle.snapshot

        async def wrong_snapshot(update=None):
            result = await original(update)
            result["state"]["seg"][0]["sx"] = 200
            return result

        oracle.snapshot = wrong_snapshot
        with self.assertRaisesRegex(AssertionError, "HTTP: segment 0 field sx"):
            await runner.verify_segment({"sx": 65})
        await runner.disconnect()


if __name__ == "__main__":
    unittest.main()
# AI: end
