"""Run with python -m unittest discover -s usermods/ble_api_bridge/tests -p 'test_client.py'."""
# AI: below section was generated by an AI
import asyncio
import json
import pathlib
import re
import sys
from types import SimpleNamespace
import unittest
from unittest.mock import AsyncMock, patch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import client_example as bridge
import macos_commissioning


class FakeCharacteristic:
    """Expose the public Bleak properties needed for contract validation."""
    service_uuid = bridge.SERVICE_UUID
    max_write_without_response_size = 20

    def __init__(self, uuid, properties):
        self.uuid = uuid
        self.properties = properties


class FakePeripheral:
    """Model acknowledged writes, including a response before the last write returns."""

    def __init__(self, _address, *, disconnected_callback, **_kwargs):
        self.is_connected = False
        self.services = self
        self.disconnected_callback = disconnected_callback
        self.callbacks = {}
        self.events = []
        self.requests = []
        self.writes = []
        self.pending = bytearray()
        self.expected = None
        self.respond = True
        self.malformed = False
        self.probe = b"ready"
        self.disconnect_stalls = False
        self.disconnect_error = None
        self.response_body = b'200 application/json\n\n{"ble":{"protocol":1,"maxRequest":4096}}'
        self.characteristics = {
            bridge.RX_UUID: FakeCharacteristic(bridge.RX_UUID, ["write"]),
            bridge.TX_UUID: FakeCharacteristic(bridge.TX_UUID, ["read", "indicate"]),
            bridge.LIVE_UUID: FakeCharacteristic(bridge.LIVE_UUID, ["read", "indicate"]),
        }

    async def connect(self):
        self.is_connected = True

    async def disconnect(self):
        if self.disconnect_stalls:
            await asyncio.Event().wait()
        if self.disconnect_error:
            raise self.disconnect_error
        self.is_connected = False
        self.disconnected_callback(self)

    async def read_gatt_char(self, uuid):
        return self.probe if uuid == bridge.TX_UUID else b"live"

    async def start_notify(self, uuid, callback):
        self.events.append(("notify", uuid))
        self.callbacks[uuid] = callback

    async def stop_notify(self, uuid):
        self.events.append(("stop_notify", uuid))
        self.callbacks.pop(uuid, None)

    def get_characteristic(self, uuid):
        return self.characteristics.get(uuid)

    def emit(self, uuid, payload, budget=20):
        """Emit a framed payload in ATT-sized chunks, preserving raw UTF-8 boundaries."""
        framed = len(payload).to_bytes(2, "little") + payload
        for offset in range(0, len(framed), budget):
            self.callbacks[uuid](None, bytearray(framed[offset:offset + budget]))

    async def write_gatt_char(self, characteristic, data, *, response):
        assert self.is_connected and characteristic.uuid == bridge.RX_UUID and response and len(data) <= 20
        self.writes.append(data)
        self.events.append(("write", characteristic.uuid))
        if self.expected is None:
            self.expected = int.from_bytes(data[:2], "little")
            self.pending.extend(data[2:])
        else:
            self.pending.extend(data)
        if len(self.pending) == self.expected:
            self.requests.append(bytes(self.pending))
            self.pending.clear()
            self.expected = None
            if self.respond:
                if self.malformed:
                    self.callbacks[bridge.TX_UUID](None, bytearray([1, 0, 42, 43]))
                else:
                    self.emit(bridge.TX_UUID, self.response_body)
        await asyncio.sleep(0)


class ClientTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.patcher = patch.object(bridge, "BleakClient", FakePeripheral)
        self.patcher.start()
        self.client = bridge.BleApiBridgeClient("test", timeout=0.1, disconnect_timeout=0.02, frame_timeout=0.02)
        await self.client.connect()

    async def asyncTearDown(self):
        self.client.client.disconnect_stalls = False
        self.client.client.disconnect_error = None
        await self.client.disconnect()
        self.patcher.stop()

    async def test_chunks_follow_att_budget_and_preserve_utf8(self):
        self.client.client.response_body = '200 application/json\n\n{"name":"Lumière 🌈"}\n\n'.encode()
        response = await self.client.request("post", "/json/state", '{"on":true,"bri":128}')
        self.assertEqual(response.status, 200)
        self.assertEqual(response.body, '{"name":"Lumière 🌈"}\n\n')
        self.assertEqual(self.client.client.requests, [b'POST /json/state\n\n{"on":true,"bri":128}'])
        self.assertEqual(self.client.write_budget, 20)
        self.assertTrue(all(len(chunk) <= 20 for chunk in self.client.client.writes))

    async def test_concurrent_requests_are_serialized(self):
        await asyncio.gather(*(self.client.request("get", "/json/info") for _ in range(5)))
        self.assertEqual(self.client.client.requests, [b"GET /json/info\n\n"] * 5)

    async def test_timeout_disconnects_before_retry(self):
        self.client.client.respond = False
        with self.assertRaises(TimeoutError):
            await self.client.request("get", "/json")
        self.assertFalse(self.client.client.is_connected)
        self.assertIsNone(self.client._response)
        await self.client.connect()
        self.assertEqual((await self.client.request("get", "/json")).status, 200)

    async def test_queue_timeout_does_not_disconnect_owner(self):
        self.client.timeout = 0.02
        async with self.client._request_lock:
            with self.assertRaises(TimeoutError):
                await self.client.request("get", "/json")
        self.assertTrue(self.client.is_connected)
        self.assertFalse(self.client.client.writes)

    async def test_cancelled_queued_request_does_not_disconnect_owner(self):
        async with self.client._request_lock:
            task = asyncio.create_task(self.client.request("get", "/json"))
            await asyncio.sleep(0)
            task.cancel()
            with self.assertRaises(asyncio.CancelledError):
                await task
        self.assertTrue(self.client.is_connected)

    async def test_cancellation_closes_connection_and_future(self):
        self.client.client.respond = False
        task = asyncio.create_task(self.client.request("get", "/json"))
        while not self.client.client.writes:
            await asyncio.sleep(0)
        task.cancel()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertFalse(self.client.client.is_connected)
        self.assertIsNone(self.client._response)

    async def test_malformed_frame_disconnects(self):
        self.client.client.malformed = True
        with self.assertRaises(ValueError):
            await self.client.request("get", "/json")
        self.assertFalse(self.client.client.is_connected)

    async def test_request_bounds_and_readiness(self):
        for method, path, body in (("post", "/json", "x" * 4096), ("get\n", "/json", ""), ("get", "/json\n", "")):
            with self.assertRaises(ValueError):
                await self.client.request(method, path, body)
        self.assertFalse(self.client.client.writes)
        await self.client.disconnect()
        with self.assertRaises(ConnectionError):
            await self.client.request("get", "/json")

    async def test_pairing_probe_failure_cleans_up(self):
        await self.client.disconnect()
        async def incompatible(_peripheral, _uuid):
            return b"not WLED"
        with patch.object(FakePeripheral, "read_gatt_char", incompatible):
            with self.assertRaises(ValueError):
                await self.client.connect()
        self.assertFalse(self.client.client.is_connected)
        self.assertFalse(self.client.is_connected)

    async def test_missing_or_wrong_characteristic_properties_clean_up(self):
        await self.client.disconnect()
        original = FakePeripheral.get_characteristic
        for value in (None, FakeCharacteristic(bridge.RX_UUID, ["write-without-response"])):
            with patch.object(FakePeripheral, "get_characteristic", lambda peripheral, uuid: value if uuid == bridge.RX_UUID else original(peripheral, uuid)):
                with self.assertRaises(ValueError):
                    await self.client.connect()
            self.assertFalse(self.client.client.is_connected)

    async def test_connect_deadline_includes_probe_and_subscription(self):
        await self.client.disconnect()
        self.client.connect_timeout = 0.02
        async def stall(_peripheral, _uuid):
            await asyncio.Event().wait()
        with patch.object(FakePeripheral, "read_gatt_char", stall):
            with self.assertRaises(TimeoutError):
                await self.client.connect()
        self.assertFalse(self.client.client.is_connected)

    async def test_macos_probe_timeout_explains_inner_limit(self):
        await self.client.disconnect()
        async def timeout(_peripheral, _uuid):
            raise TimeoutError()
        with patch.object(FakePeripheral, "read_gatt_char", timeout), patch.object(bridge.sys, "platform", "darwin"):
            with self.assertRaisesRegex(bridge.PairingProbeTimeout, "20 seconds"):
                await self.client.connect()
        self.assertFalse(self.client.client.is_connected)

    async def test_commissioning_backend_is_explicit_and_bounded(self):
        with patch.object(bridge.sys, "platform", "darwin"), patch.object(macos_commissioning, "commissioning_backend", return_value=object) as backend:
            ordinary = bridge.BleApiBridgeClient("test")
            backend.assert_not_called()
            commissioning = bridge.BleApiBridgeClient("test", commission=True, connect_timeout=110)
            backend.assert_called_once()
            await commissioning.connect()
            await commissioning.disconnect()
            await ordinary.disconnect()
            with self.assertRaises(ValueError):
                bridge.BleApiBridgeClient("test", commission=True, connect_timeout=111)

    async def test_disconnect_failure_preserves_original_command_error(self):
        self.client.client.malformed = True
        self.client.client.disconnect_error = RuntimeError("OS cleanup failed")
        with self.assertRaisesRegex(ValueError, "declared length"):
            await self.client.request("get", "/json")
        self.assertFalse(self.client.is_connected)

    async def test_stalled_disconnect_is_bounded_and_reported(self):
        self.client.client.disconnect_stalls = True
        with self.assertRaises(TimeoutError):
            await self.client.disconnect()
        self.assertFalse(self.client.is_connected)

    async def test_old_callbacks_cannot_affect_reconnected_request(self):
        old_peripheral = self.client.client
        old_tx = old_peripheral.callbacks[bridge.TX_UUID]
        await self.client.disconnect()
        await self.client.connect()
        self.client.client.respond = False
        task = asyncio.create_task(self.client.request("get", "/json"))
        while not self.client.client.requests:
            await asyncio.sleep(0)
        old_peripheral.disconnected_callback(old_peripheral)
        old_tx(None, bytearray(b"\x01\x00x"))
        self.assertFalse(task.done())
        self.assertTrue(self.client.is_connected)
        self.client.client.emit(bridge.TX_UUID, b"200 application/json\n\n{}")
        self.assertEqual((await task).json(), {})

    async def test_unexpected_disconnect_fails_pending_request_immediately(self):
        self.client.client.respond = False
        task = asyncio.create_task(self.client.request("get", "/json"))
        while not self.client.client.requests:
            await asyncio.sleep(0)
        await self.client.client.disconnect()
        with self.assertRaises(ConnectionError):
            await task

    async def test_live_and_tx_frames_interleave_independently(self):
        await self.client.subscribe_live()
        self.client.client.requests.clear()
        self.client.client.respond = False
        task = asyncio.create_task(self.client.request("get", "/json"))
        while not self.client.client.requests:
            await asyncio.sleep(0)
        live = json.dumps({"state": {"name": "🌈"}, "info": {}}, ensure_ascii=False).encode()
        tx = b'200 application/json\n\n{"ok":true}'
        self.client.client.callbacks[bridge.LIVE_UUID](None, bytearray(len(live).to_bytes(2, "little") + live[:15]))
        self.client.client.callbacks[bridge.TX_UUID](None, bytearray(len(tx).to_bytes(2, "little") + tx[:10]))
        self.client.client.callbacks[bridge.LIVE_UUID](None, bytearray(live[15:]))
        self.client.client.callbacks[bridge.TX_UUID](None, bytearray(tx[10:]))
        self.assertEqual((await self.client.next_live())["state"]["name"], "🌈")
        self.assertEqual((await task).json(), {"ok": True})

    async def test_physical_live_receiver_precedes_every_first_command(self):
        for _ in range(2):
            peripheral = self.client.client
            self.assertIn(bridge.LIVE_UUID, peripheral.callbacks)
            self.assertFalse(self.client._subscribed)
            self.assertFalse(peripheral.writes)
            await self.client.request("GET", "/json/info")
            first_write = next(index for index, event in enumerate(peripheral.events) if event[0] == "write")
            self.assertLess(peripheral.events.index(("notify", bridge.TX_UUID)), first_write)
            self.assertLess(peripheral.events.index(("notify", bridge.LIVE_UUID)), first_write)
            await self.client.disconnect()
            await self.client.connect()

    async def test_live_only_connect_opens_gate_with_read_only_handshake(self):
        await self.client.disconnect()
        original = FakePeripheral.write_gatt_char
        snapshot = b'{"state":{"bri":81},"info":{}}'
        async def gated_write(peripheral, characteristic, data, *, response):
            self.assertIn(bridge.TX_UUID, peripheral.callbacks)
            self.assertIn(bridge.LIVE_UUID, peripheral.callbacks)
            await original(peripheral, characteristic, data, response=response)
            if peripheral.requests and not getattr(peripheral, "initial_live_sent", False):
                peripheral.initial_live_sent = True
                peripheral.emit(bridge.LIVE_UUID, snapshot)
        with patch.object(FakePeripheral, "write_gatt_char", gated_write):
            await asyncio.wait_for(self.client.connect(live=True), 0.3)
        self.assertEqual(self.client.client.requests, [b"GET /json/info\n\n"])
        self.assertEqual((await self.client.next_live())["state"]["bri"], 81)

    async def test_local_unsubscribe_and_reenable_preserve_partial_wire_frame(self):
        await self.client.subscribe_live()
        peripheral = self.client.client
        body = b'{"state":{"bri":42},"info":{}}'
        callback = peripheral.callbacks[bridge.LIVE_UUID]
        callback(None, bytearray(len(body).to_bytes(2, "little") + body[:8]))
        timer = self.client._live_timer
        await self.client.unsubscribe_live()
        self.assertIs(self.client._live_timer, timer)
        self.assertEqual(bytes(self.client._live_frame.buffer), body[:8])
        callback(None, bytearray(body[8:]))
        self.assertTrue(self.client._live_queue.empty())
        self.assertTrue(self.client.is_connected)
        callback(None, bytearray(len(body).to_bytes(2, "little") + body[:11]))
        await self.client.subscribe_live()
        callback(None, bytearray(body[11:]))
        self.assertEqual((await self.client.next_live())["state"]["bri"], 42)
        self.assertEqual(peripheral.events.count(("notify", bridge.LIVE_UUID)), 1)
        self.assertNotIn(("stop_notify", bridge.LIVE_UUID), peripheral.events)

    async def test_unsubscribe_epoch_retires_waiter_before_immediate_reenable(self):
        await self.client.subscribe_live()
        waiting = asyncio.create_task(self.client.next_live())
        await asyncio.sleep(0)
        # Make resubscription synchronous so the old waiter cannot run until after it.
        with patch.object(self.client, "refresh_capabilities", AsyncMock(return_value={})):
            await self.client.unsubscribe_live()
            await self.client.subscribe_live()
        self.client.client.emit(bridge.LIVE_UUID, b'{"state":{"bri":73},"info":{}}')
        with self.assertRaisesRegex(ConnectionError, "not subscribed"):
            await waiting
        self.assertEqual((await self.client.next_live())["state"]["bri"], 73)

    async def test_disabled_delivery_still_validates_and_times_out_wire_frames(self):
        self.client.client.emit(bridge.LIVE_UUID, b'{"state":true}')
        await self.client._abort_task
        self.assertFalse(self.client.is_connected)
        await self.client.connect()
        self.client.client.callbacks[bridge.LIVE_UUID](None, bytearray(b"\x20\x00{"))
        await asyncio.sleep(0.03)
        await self.client._abort_task
        self.assertFalse(self.client.is_connected)
        self.assertIsInstance(self.client._live_error, TimeoutError)

    async def test_failed_live_handshake_does_not_deadlock_lifecycle_cleanup(self):
        self.client.client.respond = False
        self.client.timeout = 0.01
        with self.assertRaises(TimeoutError):
            await asyncio.wait_for(self.client.subscribe_live(), 0.3)
        self.assertFalse(self.client.is_connected)
        await self.client.connect()
        self.client.client.response_body = b'200 application/json\n\n{"ble":{"protocol":9}}'
        with self.assertRaisesRegex(ValueError, "unsupported"):
            await asyncio.wait_for(self.client.connect(live=True), 0.3)
        self.assertFalse(self.client.is_connected)

    async def test_queued_handshake_cannot_run_on_replacement_connection(self):
        async with self.client._request_lock:
            task = asyncio.create_task(self.client.subscribe_live())
            await asyncio.sleep(0)
            await self.client.disconnect()
            await self.client.connect()
        with self.assertRaisesRegex(ConnectionError, "before LIVE"):
            await task
        self.assertTrue(self.client.is_connected)
        self.assertFalse(self.client.client.writes)

    async def test_cancelled_queued_live_handshake_does_not_close_command_owner(self):
        async with self.client._request_lock:
            task = asyncio.create_task(self.client.subscribe_live())
            await asyncio.sleep(0)
            task.cancel()
            with self.assertRaises(asyncio.CancelledError):
                await task
        self.assertTrue(self.client.is_connected)

    async def test_old_completed_handshake_cannot_change_replacement_capabilities(self):
        original = FakePeripheral.write_gatt_char
        old = self.client.client
        old.response_body = b'200 application/json\n\n{"ble":{"protocol":1,"maxRequest":256}}'
        async def reconnect_before_write_returns(peripheral, characteristic, data, *, response):
            await original(peripheral, characteristic, data, response=response)
            if peripheral is old and peripheral.requests:
                await self.client.disconnect()
                await self.client.connect()
        with patch.object(FakePeripheral, "write_gatt_char", reconnect_before_write_returns):
            with self.assertRaisesRegex(ConnectionError, "disconnected"):
                await self.client.subscribe_live()
        self.assertTrue(self.client.is_connected)
        self.assertIsNot(self.client.client, old)
        self.assertEqual(self.client.max_request_bytes, 4096)

    async def test_retired_completed_command_reply_is_rejected_without_retry(self):
        original = FakePeripheral.write_gatt_char
        old = self.client.client
        async def reconnect_before_write_returns(peripheral, characteristic, data, *, response):
            await original(peripheral, characteristic, data, response=response)
            if peripheral is old and peripheral.requests:
                await self.client.disconnect()
                await self.client.connect()
        with patch.object(FakePeripheral, "write_gatt_char", reconnect_before_write_returns):
            with self.assertRaisesRegex(ConnectionError, "before response delivery"):
                await self.client.request("POST", "/json/state", '{"bri":42}')
        self.assertEqual(old.requests, [b'POST /json/state\n\n{"bri":42}'])
        self.assertTrue(self.client.is_connected)
        self.assertFalse(self.client.client.requests)

    async def test_invalid_live_during_notify_install_cannot_mark_connection_ready(self):
        await self.client.disconnect()
        original = FakePeripheral.start_notify
        async def invalid_on_install(peripheral, uuid, callback):
            await original(peripheral, uuid, callback)
            if uuid == bridge.LIVE_UUID:
                peripheral.emit(uuid, b'{"state":true}')
        with patch.object(FakePeripheral, "start_notify", invalid_on_install):
            with self.assertRaises(ValueError):
                await asyncio.wait_for(self.client.connect(), 0.3)
        await self.client._abort_task
        self.assertFalse(self.client.is_connected)

    async def test_live_queue_is_bounded_and_keeps_latest(self):
        await self.client.subscribe_live()
        for index in range(20):
            self.client.client.emit(bridge.LIVE_UUID, json.dumps({"state": {"bri": index}, "info": {}}).encode())
        self.assertEqual(self.client.live_dropped, 4)
        self.assertEqual((await self.client.next_live())["state"]["bri"], 4)
        for _ in range(15):
            latest = await self.client.next_live()
        self.assertEqual(latest["state"]["bri"], 19)

    async def test_live_waiters_wake_on_disconnect_or_unsubscribe(self):
        for end in (self.client.unsubscribe_live, self.client.disconnect):
            await self.client.connect(live=True)
            pending = [asyncio.create_task(self.client.next_live()) for _ in range(2)]
            await asyncio.sleep(0)
            await end()
            for task in pending:
                with self.assertRaises(ConnectionError):
                    await task

    async def test_bad_live_json_closes_connection(self):
        await self.client.subscribe_live()
        self.client.client.emit(bridge.LIVE_UUID, b'{"state":true}')
        with self.assertRaises(ValueError):
            await self.client.next_live()
        await self.client._abort_task
        self.assertFalse(self.client.client.is_connected)

    async def test_partial_live_frame_stall_closes_connection(self):
        await self.client.subscribe_live()
        self.client.client.callbacks[bridge.LIVE_UUID](None, bytearray(b"\x20\x00{"))
        with self.assertRaisesRegex(TimeoutError, "partial LIVE"):
            await self.client.next_live()
        await self.client._abort_task
        self.assertFalse(self.client.client.is_connected)

    async def test_live_wait_timeout_does_not_close_healthy_link(self):
        await self.client.subscribe_live()
        with self.assertRaises(TimeoutError):
            await self.client.next_live(timeout=0.01)
        self.assertTrue(self.client.is_connected)

    async def test_json_helpers_capabilities_and_valid_error_status(self):
        self.client.client.response_body = b'200 application/json\n\n{"ble":{"protocol":1,"maxRequest":256}}'
        await self.client.refresh_capabilities()
        self.assertEqual(self.client.max_request_bytes, 256)
        with self.assertRaises(ValueError):
            await self.client.post_json("/json/state", {"name": "x" * 300})
        self.client.client.response_body = b'401 application/json\n\n{"success":false}'
        with self.assertRaises(bridge.BridgeHTTPError) as result:
            await self.client.get_json("/json/cfg")
        self.assertEqual(result.exception.response.status, 401)
        self.assertTrue(self.client.is_connected)

    async def test_queued_command_rechecks_newly_learned_request_limit_before_writing(self):
        peripheral = self.client.client
        peripheral.respond = False
        peripheral.response_body = b'200 application/json\n\n{"ble":{"protocol":1,"maxRequest":256}}'
        handshake = asyncio.create_task(self.client.subscribe_live())
        while not peripheral.requests:
            await asyncio.sleep(0)
        self.assertEqual(self.client.max_request_bytes, 4096)
        queued = asyncio.create_task(self.client.post_json("/json/state", {"name": "x" * 300}))
        await asyncio.sleep(0)  # Queue while the capabilities request still owns the command slot.
        writes_before_reply = len(peripheral.writes)
        self.assertFalse(queued.done())
        peripheral.respond = True
        peripheral.emit(bridge.TX_UUID, peripheral.response_body)
        await handshake
        self.assertEqual(self.client.max_request_bytes, 256)
        with self.assertRaisesRegex(ValueError, "bridge limit \\(256 bytes\\)"):
            await queued
        self.assertEqual(peripheral.requests, [b"GET /json/info\n\n"])
        self.assertEqual(len(peripheral.writes), writes_before_reply)
        self.assertIsNone(self.client._response)
        self.assertTrue(self.client.is_connected)
        self.assertEqual((await self.client.request("GET", "/json/info")).status, 200)

    async def test_context_manager_closes_link(self):
        other = bridge.BleApiBridgeClient("test")
        async with other:
            self.assertTrue(other.is_connected)
        self.assertFalse(other.client.is_connected)


class FramingTests(unittest.TestCase):
    def test_all_fragment_boundaries_preserve_payload(self):
        payload = '200 application/json\n\n{"name":"Lumière 🌈"}'.encode()
        wire = len(payload).to_bytes(2, "little") + payload
        for first_size in range(2, len(wire)):
            frame = bridge.FrameAssembler()
            self.assertIsNone(frame.append(wire[:first_size]))
            self.assertEqual(frame.append(wire[first_size:]), payload)

    def test_rejects_zero_short_empty_and_overflow_packets(self):
        for packet in (b"", b"\x01", b"\0\0", b"\x01\0ab"):
            with self.assertRaises(ValueError):
                bridge.FrameAssembler().append(packet)
        frame = bridge.FrameAssembler()
        self.assertIsNone(frame.append(b"\x03\0a"))
        with self.assertRaises(ValueError):
            frame.append(b"bcd")

    def test_response_envelope_rejects_invalid_status_utf8_and_headers(self):
        for payload in (b"200", b"200 \n\n{}", b"99 application/json\n\n{}", b"+200 application/json\n\n{}",
                        b"600 application/json\n\n{}", b"200 app\njson\n\n{}", b"200 application/json\n\n\xff"):
            with self.assertRaises(ValueError):
                bridge.BleApiBridgeClient._parse_response(payload)

    def test_uuid_contract_matches_firmware(self):
        header = pathlib.Path(__file__).resolve().parents[1] / "ble_api_bridge.h"
        values = dict(re.findall(r'constexpr char (\w+_UUID)\[\] = "([^"]+)";', header.read_text()))
        for name in ("SERVICE_UUID", "RX_UUID", "TX_UUID", "LIVE_UUID"):
            self.assertEqual(values[name], getattr(bridge, name))
        self.assertEqual(bridge.TX_UUID, macos_commissioning.TX_UUID)


class CommissioningTests(unittest.IsolatedAsyncioTestCase):
    async def test_adapter_extends_only_tx_probe_and_preserves_other_reads(self):
        class Base:
            async def read_gatt_char(self, characteristic, **kwargs):
                return b"base-read"
        class Adapter(macos_commissioning.ProtectedProbeTimeoutMixin, Base):
            pass
        adapter = Adapter()
        read = AsyncMock(return_value=b"ready")
        adapter._delegate = SimpleNamespace(read_characteristic=read)
        tx = SimpleNamespace(uuid=bridge.TX_UUID, obj=object())
        self.assertEqual(await adapter.read_gatt_char(tx), b"ready")
        read.assert_awaited_once_with(tx.obj, use_cached=False, timeout=90)
        live = SimpleNamespace(uuid=bridge.LIVE_UUID, obj=object())
        self.assertEqual(await adapter.read_gatt_char(live), b"base-read")
        self.assertEqual(read.await_count, 1)

    def test_changed_bleak_version_is_rejected_before_loading_backend(self):
        with patch.object(macos_commissioning, "version", return_value="99.0.0"):
            with self.assertRaisesRegex(RuntimeError, "requires Bleak 3.0.2"):
                macos_commissioning.commissioning_backend()


if __name__ == "__main__":
    unittest.main()
# AI: end
