"""Safety/restoration tests for optional configuration HIL; no radio or hardware involved."""
# AI: below section was generated by an AI
import asyncio
import copy
import json
import os
from pathlib import Path
import stat
import sys
import tempfile
import threading
from types import SimpleNamespace
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import client_example as bridge
import config_hil as config
from test_hil_runner import FakeClient, FakeDevice, FakeOracle


class ConfigDevice(FakeDevice):
    def __init__(self, pin=""):
        super().__init__()
        self.pin = pin
        self.http_unlocked = not pin
        self.cfg = {"um": {"BleApiBridge": {"enabled": True, "device-name": "original",
                    "max-request-bytes": 4096, "pairing-code": 874619}},
                    "nw": {"linked_remote": ["102030405060"]}, "id": {"name": "Fixture"},
                    "ota": {"lock": False, "lock-wifi": True, "same-subnet": True, "aota": False, "pskl": 8}}
        self.cfg_posts = []
        self.security_posts = []
        self.ble_pin_attempts = []
        self.clients = []
        self.fail_after_apply = False
        self.fail_pin_after_apply = False
        self.cancel_pin_after_apply = False

    def apply(self, update):
        self.cfg_posts.append(copy.deepcopy(update))
        top = self.cfg["um"]["BleApiBridge"]
        before = copy.deepcopy(top)
        top.update(update.get("um", {}).get("BleApiBridge", {}))
        top["device-name"] = top["device-name"].encode()[:29].decode(errors="ignore")
        self.cfg["nw"]["linked_remote"] = copy.deepcopy(update.get("nw", {}).get("linked_remote", []))
        self.info["ble"]["maxRequest"] = top["max-request-bytes"]
        self.state["BleApiBridge"] = {"enabled": top["enabled"]}
        if top != before:
            for client in self.clients:
                client.is_connected = False


class ConfigClient(FakeClient):
    def __init__(self, device, **kwargs):
        super().__init__(device, **kwargs)
        device.clients.append(self)

    async def connect(self):
        if not self.device.cfg["um"]["BleApiBridge"]["enabled"]:
            raise ConnectionError("Disabled")
        await super().connect()

    async def request(self, method, path, body=""):
        if not self.is_connected:
            raise ConnectionError("Disconnected")
        if path != "/json/cfg":
            return await super().request(method, path, body)
        if method == "GET":
            status, value = (401, {}) if self.device.pin else (200, self.device.cfg)
        else:
            update = json.loads(body)
            self.device.ble_pin_attempts.append(update.get("pin"))
            if self.device.pin and update.get("pin") != self.device.pin:
                status, value = 401, {"success": False}
            else:
                self.device.apply(update)
                if self.device.fail_after_apply:
                    self.device.fail_after_apply = False
                    raise ConnectionError("Write applied but reply lost; SECRET")
                status, value = 200, {"success": True}
        return bridge.BridgeResponse(status, "application/json", json.dumps(value))

    async def stop_notify(self, characteristic):
        pass

    async def start_notify(self, characteristic, callback):
        pass

    async def write_gatt_char(self, characteristic, payload, response):
        if int.from_bytes(payload[:2], "little") > self.device.info["ble"]["maxRequest"]:
            self.is_connected = False


class ConfigOracle(FakeOracle):
    async def request(self, method, path, body=None):
        if path == "/json/state":
            self.device.http_unlocked = not self.device.pin or body.get("pin") == self.device.pin
            return 200, self.device.snapshot()
        if method == "GET":
            # Core HTTP GET /json/cfg is public even when settings are locked.
            return 200, copy.deepcopy(self.device.cfg)
        if "pin" in body:
            self.device.http_unlocked = not self.device.pin or body["pin"] == self.device.pin
        if not self.device.http_unlocked and self.device.pin:
            return 401, {}
        self.device.apply(body)
        return 200, {"success": True}

    async def settings(self, method, path, fields=None):
        if path == "/settings/lock":
            self.device.http_unlocked = not self.device.pin
            return 200, "lock state updated"
        if not self.device.http_unlocked:
            return 401, "PIN required"
        mapping = {"NO": "lock", "OW": "lock-wifi", "AO": "aota", "SU": "same-subnet"}
        ota = self.device.cfg["ota"]
        if method == "GET":
            script = 'd.Sf.PIN.value="' + ("0000" if self.device.pin else "") + '";'
            script += "".join(f"d.Sf.{key}.checked={int(bool(ota.get(value)))};" for key, value in mapping.items())
            return 200, script
        self.device.security_posts.append(copy.deepcopy(fields))
        if not ota["lock"]:
            for field, name in mapping.items():
                if name in ota:
                    ota[name] = field in fields
        self.device.pin = fields["PIN"]
        if self.device.fail_pin_after_apply:
            self.device.fail_pin_after_apply = False
            raise ConnectionError("PIN applied but response lost; SECRET")
        if self.device.cancel_pin_after_apply:
            self.device.cancel_pin_after_apply = False
            raise asyncio.CancelledError()
        return 200, "Security settings saved"


class ConfigTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.args = config.parse_args(["--address", "test", "--http-url", "http://127.0.0.1",
                                      "--output", self.temp.name, "--allow-config-tests"])
        self.device = ConfigDevice()
        self.cooldown = patch.object(config, "PIN_SETTLE_SECONDS", 0)
        self.cooldown.start()
        self.addCleanup(self.cooldown.stop)

    def runner(self, oracle=None):
        async def scanner(**kwargs):
            return {"test": (SimpleNamespace(address="test"),
                              SimpleNamespace(local_name=self.device.cfg["um"]["BleApiBridge"]["device-name"]))}

        result = config.ConfigHilRunner(self.args,
                client_factory=lambda _address, **kwargs: ConfigClient(self.device, **kwargs),
                oracle=oracle or ConfigOracle(self.device), scanner=scanner)
        # Real restart observation waits up to ten seconds when restoration is a no-op.
        async def disconnected(client):
            config.check(not client.client.is_connected, "Runtime configuration did not disconnect the old BLE link")
        result.wait_disconnected = disconnected
        return result

    def assert_safe_payloads(self):
        for value in self.device.cfg_posts:
            self.assertIs(value["sv"], False)
            self.assertEqual(value["nw"], {"linked_remote": ["102030405060"]})
            self.assertLessEqual(set(value["um"]["BleApiBridge"]), set(config.ConfigHilRunner.fields))
            self.assertNotIn("pairing-code", value["um"]["BleApiBridge"])
            self.assertLessEqual(set(value), {"sv", "um", "nw", "pin"})

    async def test_full_run_restores_exact_touched_fields_and_marks_missing_pin_coverage(self):
        initial = copy.deepcopy(self.device.cfg)
        runner = self.runner()
        self.assertEqual(await runner.run(), 2)
        self.assertEqual(self.device.cfg, initial)
        self.assert_safe_payloads()
        statuses = {record["name"]: record["status"] for record in runner.records}
        self.assertEqual(statuses["runtime_names_utf8"], "pass")
        self.assertEqual(statuses["runtime_request_limits"], "pass")
        self.assertEqual(statuses["runtime_disable_enable"], "pass")
        self.assertEqual(statuses["independent_settings_pin"], "skip")
        self.assertEqual(statuses["restore_configuration"], "pass")

    async def test_backup_is_private_ignored_and_secrets_absent_from_reports(self):
        runner = self.runner()
        await runner.setup_config()
        runner.write_reports()
        backup = Path(self.temp.name) / "private-config" / "configuration.json"
        self.assertEqual(stat.S_IMODE(backup.stat().st_mode), 0o600)
        self.assertEqual(stat.S_IMODE(backup.parent.stat().st_mode), 0o700)
        self.assertEqual((backup.parent / ".gitignore").read_text(), "*\n")
        self.assertEqual(json.loads(backup.read_text()), self.device.cfg)
        for path in Path(self.temp.name).iterdir():
            if path.is_file():
                self.assertNotIn("874619", path.read_text())

    async def test_wrong_http_identity_prevents_all_writes_and_backup(self):
        other = ConfigDevice()
        other.info["mac"] = "112233445566"
        runner = self.runner(ConfigOracle(other))
        self.assertEqual(await runner.run(), 1)
        self.assertFalse(self.device.cfg_posts)
        self.assertFalse(other.cfg_posts)
        self.assertFalse((Path(self.temp.name) / "private-config").exists())

    async def test_lost_reply_after_mutation_is_restored_and_failure_preserved(self):
        initial = copy.deepcopy(self.device.cfg)
        self.device.fail_after_apply = True
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.cfg, initial)
        self.assertEqual(next(r for r in runner.records if r["name"] == "runtime_names_utf8")["status"], "fail")
        self.assertEqual(next(r for r in runner.records if r["name"] == "restore_configuration")["status"], "pass")
        self.assertNotIn("SECRET", (Path(self.temp.name) / "results.json").read_text())

    async def test_changed_identity_blocks_http_restoration(self):
        runner = self.runner()
        await runner.setup_config()
        await runner.ble_config_restart({"enabled": False})
        self.device.info["mac"] = "112233445566"
        before = len(self.device.cfg_posts)
        with self.assertRaisesRegex(AssertionError, "identity changed"):
            await runner.restore_config()
        self.assertEqual(len(self.device.cfg_posts), before)

    async def test_cancellation_restores_disabled_radio_and_marks_interruption(self):
        initial = copy.deepcopy(self.device.cfg)
        runner = self.runner()

        async def interrupted():
            await runner.ble_config_restart({"enabled": False})
            raise asyncio.CancelledError()

        runner.names = interrupted
        with self.assertRaises(asyncio.CancelledError):
            await runner.run()
        self.assertEqual(self.device.cfg, initial)
        result = json.loads((Path(self.temp.name) / "results.json").read_text())
        self.assertEqual(result["outcome"], "failed")
        self.assertEqual(next(row for row in runner.records if row["name"] == "interruption")["status"], "fail")

    async def test_existing_pin_is_tested_without_modifying_it(self):
        self.device = ConfigDevice("6493")
        self.args.provision_test_pin = True
        with patch.dict(os.environ, {"WLED_HIL_SETTINGS_PIN": "6493"}):
            runner = self.runner()
        await runner.setup_config()
        self.assertTrue(self.device.http_unlocked)
        await runner.settings_pin()
        self.assertEqual(self.device.ble_pin_attempts, [None, "1111", 6493, "6493"])
        await runner.restore_config()
        self.assertEqual(self.device.pin, "6493")
        self.assertFalse(self.device.security_posts)
        self.assertFalse((Path(self.temp.name) / "private-config" / "pin-recovery.json").exists())
        self.assert_safe_payloads()
        runner.write_reports()
        self.assertNotIn("6493", (Path(self.temp.name) / "results.json").read_text())

    async def test_existing_unknown_pin_skips_before_config_writes(self):
        self.device = ConfigDevice("6493")
        with patch.dict(os.environ, {"WLED_HIL_SETTINGS_PIN": ""}):
            runner = self.runner()
        self.assertEqual(await runner.run(), 2)
        self.assertFalse(self.device.cfg_posts)

    async def test_wrong_existing_pin_cannot_use_public_cfg_as_unlock_proof(self):
        self.device = ConfigDevice("6493")
        oracle = ConfigOracle(self.device)
        self.assertEqual((await oracle.request("GET", "/json/cfg"))[0], 200)
        self.assertEqual((await oracle.settings("GET", "/settings/s.js?p=6"))[0], 401)
        with patch.dict(os.environ, {"WLED_HIL_SETTINGS_PIN": "1111"}):
            runner = self.runner(oracle)
        self.assertEqual(await runner.run(), 1)
        self.assertFalse(self.device.http_unlocked)
        self.assertFalse(self.device.cfg_posts)
        self.assertFalse(self.device.security_posts)
        self.assertFalse((Path(self.temp.name) / "private-config").exists())
        self.assertIn("HTTP authentication", runner.records[0]["detail"])

    async def test_unlock_http_rejects_wrong_pin_despite_public_configuration_read(self):
        self.args.provision_test_pin = True
        runner = self.runner()
        await runner.setup_config()
        await runner.oracle.settings("GET", "/settings/lock")
        runner.pin = "1111" if runner.pin != "1111" else "2222"
        with self.assertRaisesRegex(AssertionError, "HTTP authentication"):
            await runner.unlock_http()
        self.assertEqual((await runner.oracle.request("GET", "/json/cfg"))[0], 200)
        self.assertFalse(self.device.http_unlocked)

    async def test_existing_noncanonical_pin_marks_numeric_coercion_coverage_missing(self):
        self.device = ConfigDevice("0123")
        with patch.dict(os.environ, {"WLED_HIL_SETTINGS_PIN": "0123"}):
            runner = self.runner()
        await runner.setup_config()
        with self.assertRaisesRegex(config.CoverageMissing, "numeric coercion"):
            await runner.settings_pin()
        self.assertEqual(self.device.ble_pin_attempts, [None, "1111", "0123"])

    async def test_refuses_unrelated_mutation_fields(self):
        runner = self.runner()
        await runner.setup_config()
        with self.assertRaisesRegex(AssertionError, "unrelated"):
            runner.payload({"pairing-code": 123123})
        self.assertFalse(self.device.cfg_posts)

    def test_cli_requires_opt_in_and_http_recovery(self):
        for arguments in (["--address", "test", "--output", self.temp.name, "--http-url", "http://127.0.0.1"],
                          ["--address", "test", "--output", self.temp.name, "--allow-config-tests"]):
            with self.assertRaises(SystemExit):
                config.parse_args(arguments)

    def test_backup_never_overwrites_prior_backup(self):
        path = config.private_backup(self.temp.name, {"original": True})
        with self.assertRaises(FileExistsError):
            config.private_backup(self.temp.name, {"original": False})
        self.assertEqual(json.loads(path.read_text()), {"original": True})

    async def test_provisioned_pin_is_tested_then_cleared_with_all_flags_preserved(self):
        self.args.provision_test_pin = True
        initial = copy.deepcopy(self.device.cfg)
        with patch.object(config.secrets, "randbelow", return_value=5493):
            runner = self.runner()
            self.assertEqual(await runner.run(), 0)
        self.assertEqual(self.device.pin, "")
        self.assertEqual(self.device.cfg, initial)
        self.assertTrue(self.device.http_unlocked)
        self.assertEqual(self.device.security_posts, [{"PIN": "6493", "OW": "on", "SU": "on"},
                                                      {"PIN": "", "OW": "on", "SU": "on"}])
        statuses = {record["name"]: record["status"] for record in runner.records}
        self.assertEqual(statuses["independent_settings_pin"], "pass")
        self.assertEqual(self.device.ble_pin_attempts[-4:], [None, "1111", 6493, "6493"])
        self.assertEqual(statuses["restore_test_pin"], "pass")
        recovery = Path(self.temp.name) / "private-config" / "pin-recovery.json"
        self.assertEqual(stat.S_IMODE(recovery.stat().st_mode), 0o600)
        self.assertEqual(json.loads(recovery.read_text())["temporary_pin"], "6493")
        self.assertTrue(runner.pin_restored)
        report = json.loads((Path(self.temp.name) / "results.json").read_text())
        self.assertFalse(report["settings_pin_fixture"]["persistence_verified"])
        for path in Path(self.temp.name).iterdir():
            if path.is_file():
                self.assertNotIn("6493", path.read_text())

    async def test_lost_provisioning_reply_still_clears_pin_and_preserves_failure(self):
        self.args.provision_test_pin = True
        self.device.fail_pin_after_apply = True
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.pin, "")
        self.assertTrue(runner.pin_restored)
        self.assertEqual(runner.records[0]["status"], "fail")
        self.assertEqual(next(r for r in runner.records if r["name"] == "restore_test_pin")["status"], "pass")

    async def test_cancelled_provisioning_still_clears_pin(self):
        self.args.provision_test_pin = True
        self.device.cancel_pin_after_apply = True
        runner = self.runner()
        with self.assertRaises(asyncio.CancelledError):
            await runner.run()
        self.assertEqual(self.device.pin, "")
        self.assertTrue(runner.pin_restored)

    async def test_pin_clears_even_if_ble_config_restore_case_fails(self):
        self.args.provision_test_pin = True
        initial = copy.deepcopy(self.device.cfg)
        runner = self.runner()
        async def fail_restore():
            raise ConnectionError("Unable to verify unrelated configuration restoration")
        runner.restore_config = fail_restore
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.pin, "")
        self.assertEqual(self.device.cfg, initial)
        self.assertTrue(runner.pin_restored)

    async def test_pin_clear_refused_if_baseline_cannot_be_restored_before_security_save(self):
        self.args.provision_test_pin = True
        runner = self.runner()
        async def fail_restore():
            async def blocked_restore(fields):
                raise ConnectionError("Fixture unavailable")
            runner.http_config = blocked_restore
            raise ConnectionError("Fixture unavailable")
        runner.restore_config = fail_restore
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.pin, runner.pin)
        self.assertFalse(runner.pin_restored)
        self.assertEqual(len(self.device.security_posts), 1)
        self.assertEqual(self.device.security_posts[0]["PIN"], runner.pin)
        result = next(row for row in runner.records if row["name"] == "restore_test_pin")
        self.assertEqual(result["status"], "fail")
        self.assertIn("retaining test PIN", result["detail"])
        self.assertTrue((Path(self.temp.name) / "private-config" / "pin-recovery.json").exists())

    async def test_unknown_ota_shape_prevents_pin_provisioning(self):
        self.args.provision_test_pin = True
        self.device.cfg["ota"]["lock-wifi"] = "true"
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        self.assertFalse(self.device.security_posts)
        self.assertEqual(self.device.pin, "")

    async def test_repeated_cancellation_during_cleanup_does_not_interrupt_pin_removal(self):
        self.args.provision_test_pin = True
        runner = self.runner()
        entered_cleanup = asyncio.Event()
        allow_cleanup = asyncio.Event()
        original = runner.restore_test_pin
        async def blocked_restore():
            entered_cleanup.set()
            await allow_cleanup.wait()
            return await original()
        runner.restore_test_pin = blocked_restore
        task = asyncio.create_task(runner.run())
        await entered_cleanup.wait()
        task.cancel()
        await asyncio.sleep(0)
        task.cancel()
        allow_cleanup.set()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertEqual(self.device.pin, "")
        self.assertTrue(runner.pin_restored)

    async def test_security_http_rejects_password_or_reset_fields(self):
        oracle = config.ConfigHttp("http://127.0.0.1", 0.1)
        for field in ("OP", "RS"):
            with self.assertRaisesRegex(AssertionError, "unrelated"):
                await oracle.settings("POST", "/settings/sec", {"PIN": "1111", field: "on"})

    async def test_security_http_posts_empty_pin_as_form_field(self):
        oracle = config.ConfigHttp("http://127.0.0.1", 0.1)
        with patch.object(oracle, "_exchange", return_value=(200, b"saved")) as exchange:
            self.assertEqual(await oracle.settings("POST", "/settings/sec", {"PIN": "", "SU": "on"}), (200, "saved"))
        exchange.assert_called_once_with("POST", "/settings/sec", b"PIN=&SU=on", "application/x-www-form-urlencoded")

    def test_http_body_trickle_cannot_reset_body_budget(self):
        oracle = config.ConfigHttp("http://127.0.0.1", 1)
        class Trickle:
            code = 200
            calls = 0
            def __enter__(self):
                return self
            def __exit__(self, *_args):
                pass
            def read1(self, size):
                self.calls += 1
                return b"x"
        response = Trickle()
        opener = SimpleNamespace(open=lambda *_args, **_kwargs: response)
        with patch.object(config.urllib.request, "build_opener", return_value=opener), \
             patch.object(config.time, "monotonic", side_effect=[1, 1.1, 1.5, 2.1]):
            with self.assertRaisesRegex(TimeoutError, "body read deadline"):
                oracle._exchange("GET", "/json/cfg", None, "application/json")
        self.assertEqual(response.calls, 2)

    async def test_locked_ota_and_absent_aota_field_are_preserved(self):
        self.args.provision_test_pin = True
        self.device.cfg["ota"]["lock"] = True
        del self.device.cfg["ota"]["aota"]
        original = copy.deepcopy(self.device.cfg["ota"])
        runner = self.runner()
        await runner.setup_config()
        await runner.restore_test_pin()
        self.assertEqual(self.device.cfg["ota"], original)
        self.assertTrue(all(value.get("NO") == "on" and "AO" not in value for value in self.device.security_posts))

    async def test_cancelled_http_write_finishes_before_caller_cleanup(self):
        oracle = config.ConfigHttp("http://127.0.0.1", 0.1)
        entered = threading.Event()
        release = threading.Event()
        finished = threading.Event()
        def operation():
            entered.set()
            release.wait(1)
            finished.set()
            return "done"
        task = asyncio.create_task(oracle._finish_http(operation))
        while not entered.is_set():
            await asyncio.sleep(0)
        task.cancel()
        await asyncio.sleep(0)
        self.assertFalse(task.done())
        release.set()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertTrue(finished.is_set())


if __name__ == "__main__":
    unittest.main()
# AI: end
