"""Run with python -m unittest discover -s usermods/ble_api_bridge/tests -p 'test_*.py'."""
# AI: below section was generated by an AI
import asyncio
import pathlib
import re
import sys
import unittest
from unittest.mock import patch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import client_example as bridge


class FakePeripheral:
    """Models acknowledged ATT writes, including a response before the last write returns."""
    max_write_without_response_size = 20

    def __init__(self, _address, *, disconnected_callback, **_kwargs):
        self.is_connected = False
        self.services = self
        self.disconnected_callback = disconnected_callback
        self.callback = None
        self.requests = []
        self.writes = []
        self.pending = bytearray()
        self.expected = None
        self.respond = True
        self.malformed = False
        self.missing_rx = False
        self.probe = b"ready"

    async def connect(self):
        self.is_connected = True

    async def disconnect(self):
        self.is_connected = False
        self.disconnected_callback(self)

    async def read_gatt_char(self, uuid):
        assert uuid == bridge.TX_UUID
        return self.probe

    async def start_notify(self, uuid, callback):
        assert uuid == bridge.TX_UUID
        self.callback = callback

    def get_characteristic(self, uuid):
        assert uuid == bridge.RX_UUID
        return None if self.missing_rx else self

    async def write_gatt_char(self, characteristic, data, *, response):
        assert characteristic is self and response and len(data) <= 20
        self.writes.append(data)
        if self.expected is None:
            self.expected = int.from_bytes(data[:2], "little")
            self.pending.extend(data[2:])
        else:
            self.pending.extend(data)
        if len(self.pending) == self.expected:
            self.requests.append(bytes(self.pending))
            self.pending.clear()
            self.expected = None
            if self.respond:
                body = '200 application/json\n\n{"name":"Lumière 🌈"}\n\n'.encode()
                framed = len(body).to_bytes(2, "little") + body
                if self.malformed:
                    self.callback(None, bytearray([1, 0, 42, 43]))
                else:
                    for offset in range(0, len(framed), 20):
                        self.callback(None, bytearray(framed[offset:offset + 20]))
        await asyncio.sleep(0)


class ClientTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.patcher = patch.object(bridge, "BleakClient", FakePeripheral)
        self.patcher.start()
        self.client = bridge.BleApiBridgeClient("test", timeout=0.1)
        await self.client.connect()

    async def asyncTearDown(self):
        await self.client.disconnect()
        self.patcher.stop()

    async def test_chunks_follow_att_budget_and_preserve_utf8(self):
        response = await self.client.request("post", "/json/state", '{"on":true,"bri":128}')
        self.assertEqual(response.status, 200)
        self.assertEqual(response.body, '{"name":"Lumière 🌈"}\n\n')
        self.assertEqual(self.client.client.requests, [b'POST /json/state\n\n{"on":true,"bri":128}'])
        self.assertTrue(all(len(chunk) <= 20 for chunk in self.client.client.writes))

    async def test_concurrent_requests_are_serialized(self):
        await asyncio.gather(*(self.client.request("get", "/json/info") for _ in range(5)))
        self.assertEqual(self.client.client.requests, [b"GET /json/info\n\n"] * 5)

    async def test_timeout_disconnects_before_retry(self):
        self.client.client.respond = False
        with self.assertRaises(TimeoutError):
            await self.client.request("get", "/json")
        self.assertFalse(self.client.client.is_connected)
        self.assertIsNone(self.client._response)
        self.client.client.respond = True
        await self.client.connect()
        self.assertEqual((await self.client.request("get", "/json")).status, 200)

    async def test_cancellation_closes_connection_and_future(self):
        self.client.client.respond = False
        task = asyncio.create_task(self.client.request("get", "/json"))
        while not self.client.client.writes:
            await asyncio.sleep(0)
        task.cancel()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertFalse(self.client.client.is_connected)
        self.assertIsNone(self.client._response)

    async def test_malformed_frame_disconnects(self):
        self.client.client.malformed = True
        with self.assertRaises(ValueError):
            await self.client.request("get", "/json")
        self.assertFalse(self.client.client.is_connected)

    async def test_request_bounds_and_missing_characteristics(self):
        with self.assertRaises(ValueError):
            await self.client.request("post", "/json", "x" * 4096)
        self.assertFalse(self.client.client.writes)
        self.client.client.missing_rx = True
        with self.assertRaises(ValueError):
            await self.client.request("get", "/json")
        self.assertIsNone(self.client._response)

    async def test_pairing_probe_is_required(self):
        self.client.client.probe = b"not WLED"
        with self.assertRaises(ValueError):
            await self.client.connect()

    def test_uuid_contract_matches_firmware(self):
        header = pathlib.Path(__file__).resolve().parents[1] / "ble_api_bridge.h"
        values = dict(re.findall(r'constexpr char (\w+_UUID)\[\] = "([^"]+)";', header.read_text()))
        for name in ("SERVICE_UUID", "RX_UUID", "TX_UUID", "LIVE_UUID"):
            self.assertEqual(values[name], getattr(bridge, name))


if __name__ == "__main__":
    unittest.main()
# AI: end
