"""Hardware smoke tooling rejects incomplete or corrupt file readback."""
# AI: below section was generated by an AI
import base64
import hashlib
import json
import pathlib
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).parents[1]))
from client_example import BridgeResponse
from parity_hil import ParitySmoke


class ReadClient:
    def __init__(self, replies):
        self.replies = iter(replies)

    async def request(self, method, path, body):
        assert method == "POST" and path == "/ble/fs"
        assert json.loads(body)["op"] == "read"
        return BridgeResponse(200, "application/json", json.dumps(next(self.replies)))


def chunk(data, start, count, revision=None):
    end = min(len(data), start + count)
    return {"offset": start, "next": end, "size": len(data), "eof": end == len(data),
            "revision": revision or hashlib.sha256(data).hexdigest(),
            "data": base64.b64encode(data[start:end]).decode("ascii")}


class ParitySmokeTests(unittest.IsolatedAsyncioTestCase):
    async def test_reassembles_binary_and_checks_digest(self):
        data = bytes(range(256))
        smoke = ParitySmoke(ReadClient([chunk(data, 0, 128), chunk(data, 128, 128)]))
        smoke.chunk = 128
        self.assertEqual(await smoke.read_file(), data)

    async def test_rejects_mixed_contents_with_same_reported_revision(self):
        data = b"original"
        smoke = ParitySmoke(ReadClient([chunk(data, 0, 4), chunk(b"origXXXX", 4, 4, hashlib.sha256(data).hexdigest())]))
        smoke.chunk = 4
        with self.assertRaisesRegex(AssertionError, "checksum mismatch"):
            await smoke.read_file()

    async def test_rejects_no_progress_without_looping(self):
        reply = chunk(b"fixture", 0, 0)
        smoke = ParitySmoke(ReadClient([reply]))
        smoke.chunk = 4
        with self.assertRaisesRegex(AssertionError, "read progress"):
            await smoke.read_file()


if __name__ == "__main__":
    unittest.main()
# AI: end
