"""Check the shipped BLE profiles against their resolved upstream base targets.

Run with the Python environment that contains PlatformIO. These checks deliberately
use PlatformIO's interpolation and inheritance, not a second INI resolver.
"""

# AI: below section was generated by an AI
import csv
import shlex
import tempfile
import unittest
from pathlib import Path

from platformio.project.config import ProjectConfig


ROOT = Path(__file__).resolve().parents[3]
PROFILES = {
    "esp32dev_ble_api_bridge": "esp32dev",
    "esp32s3dev_ble_api_bridge": "esp32s3dev_8MB_opi",
    "esp32dev_8MB_ble_api_bridge": "esp32dev_8M",
}


def load_profiles():
    """Resolve the distributable sample without a developer's local overrides."""
    config = ProjectConfig(str(ROOT / "platformio.ini"), parse_extra=False)
    config.read(str(ROOT / "usermods/ble_api_bridge/platformio_override.ini.sample"), parse_extra=False)
    return config


def words(value):
    """Tokenize both PlatformIO lists and custom string options."""
    return shlex.split(" ".join(value) if isinstance(value, list) else value)


def definitions(value):
    """Normalize the two GCC spellings of a preprocessor definition."""
    tokens = iter(words(value))
    result = set()
    for token in tokens:
        if token == "-D":
            result.add(next(tokens))
        elif token.startswith("-D"):
            result.add(token[2:])
    return result


def assert_parity(config, profile, base):
    """Allow only the intentional OTA removal; preserve other features and data."""
    def option(target, name, default=""):
        return config.get("env:" + target, name, default)

    def effective(target):
        flags = definitions(option(target, "build_flags", []))
        flags -= definitions(option(target, "build_unflags", []))
        return {flag for flag in flags if not flag.startswith("WLED_RELEASE_NAME=")}

    base_flags, ble_flags = effective(base), effective(profile)
    missing = base_flags - ble_flags - {"WLED_ENABLE_AOTA"}
    disabled = {flag for flag in ble_flags - base_flags
                if flag.startswith("WLED_DISABLE_") and flag != "WLED_DISABLE_OTA"}
    if missing or disabled:
        raise AssertionError(f"{profile}: lost flags {sorted(missing)}, added restrictions {sorted(disabled)}")
    base_mods = set(words(option(base, "custom_usermods")))
    ble_mods = set(words(option(profile, "custom_usermods")))
    if not base_mods | {"ble_api_bridge"} <= ble_mods:
        raise AssertionError(f"{profile}: omitted base usermods or BLE bridge")
    if "MYNEWT_VAL_BLE_SM_SC_ONLY=1" not in ble_flags:
        raise AssertionError(f"{profile}: Secure Connections pairing is required")
    if "WLED_DISABLE_OTA" not in ble_flags or "WLED_ENABLE_AOTA" in ble_flags:
        raise AssertionError(f"{profile}: USB-only builds must disable all OTA paths")
    if option(profile, "board_build.app_partition_name") != "app0":
        raise AssertionError(f"{profile}: size checks must target the factory app partition")
    for name in ("lib_deps", "lib_ignore", "board",
                 "board_build.arduino.memory_type", "board_build.flash_mode",
                 "board_upload.flash_size", "board_upload.maximum_size"):
        if option(profile, name) != option(base, name):
            raise AssertionError(f"{profile}: changes base {name}")

    # One factory app replaces the two OTA slots. NVS, filesystem and coredump
    # retain their upstream offsets and capacities, even if the base is edited.
    path = ROOT / option(profile, "board_build.partitions")
    rows = {}
    with path.open() as handle:
        for row in csv.reader(line for line in handle if not line.lstrip().startswith("#")):
            if row:
                rows[row[0].strip()] = tuple(cell.strip() for cell in row)
    app_size, fs_offset, fs_size = ((0x300000, 0x310000, 0xF0000) if base == "esp32dev"
                                    else (0x400000, 0x410000, 0x3E0000))
    expected = {
        "nvs": ("data", "nvs", 0x9000, 0x5000),
        "app0": ("app", "factory", 0x10000, app_size),
        "spiffs": ("data", "spiffs", fs_offset, fs_size),
    }
    if base != "esp32dev":
        expected["coredump"] = ("data", "coredump", 0x7F0000, 0x10000)
    actual = {name: (row[1], row[2], int(row[3], 0), int(row[4], 0))
              for name, row in rows.items()}
    if actual != expected:
        raise AssertionError(f"{profile}: incorrect factory app or changed upstream data partitions")


class ProfileParityTests(unittest.TestCase):
    def test_c3_is_not_a_supported_ble_profile(self):
        self.assertFalse(load_profiles().has_section("env:esp32c3dev_ble_api_bridge"))

    def test_all_profiles_preserve_base_capabilities(self):
        config = load_profiles()
        for profile, base in PROFILES.items():
            with self.subTest(profile=profile):
                assert_parity(config, profile, base)

    def test_previous_feature_cuts_are_rejected(self):
        # Exercise each kind of regression that produced the earlier compact
        # profiles, rather than only asserting today's configuration text.
        for option, value in (
            ("custom_usermods", "ble_api_bridge"),
            ("build_flags", "${env:esp32dev.build_flags} ${ble_api_bridge.build_flags} -D WLED_DISABLE_2D"),
            ("build_flags", "${env:esp32dev.build_flags} ${ble_api_bridge.build_flags} -D WLED_DISABLE_INFRARED"),
            ("build_unflags", "${env:esp32dev.build_unflags} -D WLED_ENABLE_DMX_INPUT"),
            ("build_unflags", "${env:esp32dev.build_unflags} -D WLED_ENABLE_GIF"),
            ("build_unflags", "${env:esp32dev.build_unflags} -D WLED_DISABLE_OTA"),
            ("lib_ignore", "${env:esp32dev.lib_ignore}\nesp_dmx"),
            ("board_build.partitions", "${esp32.default_partitions}"),
            ("board_build.app_partition_name", "missing"),
        ):
            with self.subTest(option=option, value=value):
                config = load_profiles()
                config.set("env:esp32dev_ble_api_bridge", option, value)
                with self.assertRaises(AssertionError):
                    assert_parity(config, "esp32dev_ble_api_bridge", "esp32dev")

    def test_arduino_ota_cannot_reenable_wireless_updates(self):
        config = load_profiles()
        target = "env:esp32dev_ble_api_bridge"
        config.set(target, "build_unflags", "${env:esp32dev.build_unflags}")
        config.set(target, "build_flags",
                   "${env:esp32dev.build_flags} ${ble_api_bridge.build_flags} -D WLED_ENABLE_AOTA")
        with self.assertRaises(AssertionError):
            assert_parity(config, "esp32dev_ble_api_bridge", "esp32dev")

    def test_changing_both_base_and_ble_cannot_hide_storage_cut(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "partitions.csv"
            original = (ROOT / "tools/WLED_ESP32_4MB_NOOTA.csv").read_text()
            path.write_text(original.replace("0xF0000", "0x40000"))
            config = load_profiles()
            for target in ("esp32dev", "esp32dev_ble_api_bridge"):
                config.set("env:" + target, "board_build.partitions", str(path))
            with self.assertRaises(AssertionError):
                assert_parity(config, "esp32dev_ble_api_bridge", "esp32dev")


if __name__ == "__main__":
    unittest.main()
# AI: end
