"""Check actual Xtensa stack frames for the nested filesystem transfer path.

Set WLED_BLE_STACK_ELF and WLED_BLE_OBJDUMP to a built ESP32/S3 image and its
matching objdump. The target compiler's generated code is the source of truth;
source-level checks miss inlining of large arrays into callers.
"""
# AI: below section was generated by an AI
import os
import re
import subprocess
import unittest


class TransferStackBudgetTests(unittest.TestCase):
    @unittest.skipUnless(os.environ.get("WLED_BLE_STACK_ELF") and os.environ.get("WLED_BLE_OBJDUMP"),
                         "Requires a compiled Xtensa image and matching objdump")
    def test_nested_transfer_frames_leave_room_for_filesystem_calls(self):
        text = subprocess.check_output([os.environ["WLED_BLE_OBJDUMP"], "-d", "-C", os.environ["WLED_BLE_STACK_ELF"]], text=True)
        frames = {}
        for match in re.finditer(r"^[0-9a-f]+ <([^\n]+)>:\n([^\n]*)", text, re.M):
            entry = re.search(r"\bentry\s+a1,\s+(0x[0-9a-f]+|[0-9]+)", match[2])
            if entry:
                frames[match[1]] = int(entry[1], 0)
        selected = {}
        for function, maximum in (("::dispatchTransfer(", 1024), ("::dispatchFileRead(", 1024),
                                  ("::fileDigest(", 512), ("::dispatchDDP(", 512)):
            found = [size for name, size in frames.items() if "ble_api_bridge::" in name and function in name]
            self.assertEqual(len(found), 1, "Expected one compiled frame for " + function)
            selected[function] = found[0]
            self.assertLessEqual(found[0], maximum, "Loop-task stack budget exceeded by " + function)
        self.assertLessEqual(sum(selected[name] for name in ("::dispatchTransfer(", "::dispatchFileRead(", "::fileDigest(")), 2048)


if __name__ == "__main__":
    unittest.main()
# AI: end
