"""Execute the same ingress guards used by firmware, under memory sanitizers."""
# AI: below section was generated by an AI
import pathlib
import shutil
import subprocess
import tempfile
import unittest


@unittest.skipUnless(shutil.which("clang++"), "Native storage tests require clang++")
class StorageProtocolTests(unittest.TestCase):
    def test_storage_ingress(self):
        source = pathlib.Path(__file__).with_name("storage_protocol_test.cpp")
        with tempfile.TemporaryDirectory(prefix="wled-storage-") as temporary:
            binary = pathlib.Path(temporary) / "test"
            subprocess.run([shutil.which("clang++"), "-std=c++17", "-Wall", "-Wextra", "-Werror",
                            "-fsanitize=address,undefined", str(source), "-o", str(binary)], check=True)
            result = subprocess.run([str(binary)], capture_output=True, text=True, check=True)
            self.assertIn("Passed storage", result.stdout)


if __name__ == "__main__":
    unittest.main()
# AI: end
