"""Exercise actual bridge completion scheduling with controlled storage outcomes."""
# AI: below section was generated by an AI
import pathlib
import shutil
import subprocess
import tempfile
import unittest

from test_admission import production_method


@unittest.skipUnless(shutil.which("clang++"), "Native completion test requires clang++")
class PersistenceReplyTests(unittest.TestCase):
    def test_reply_waits_for_write_and_reboot_waits_for_indication(self):
        directory = pathlib.Path(__file__).parent
        source = (directory.parent / "ble_api_bridge_admin.cpp").read_text()
        methods = [production_method(source, name) for name in
                   ("serviceBridgeOperations", "deferReboot", "queuePersistenceReply", "resetBridgeSession")]
        with tempfile.TemporaryDirectory(prefix="wled-persistence-") as temporary:
            temporary = pathlib.Path(temporary)
            (temporary / "persistence_methods.inc").write_text("namespace ble_api_bridge {\n" + "\n".join(methods) + "\n}")
            binary = temporary / "test"
            subprocess.run([shutil.which("clang++"), "-std=c++17", "-Wall", "-Wextra", "-Werror",
                            "-fsanitize=address,undefined", "-I", str(temporary),
                            str(directory / "persistence_reply_test.cpp"), "-o", str(binary)], check=True)
            ran = subprocess.run([str(binary)], text=True, capture_output=True, check=True)
            self.assertIn("Passed deferred", ran.stdout)


if __name__ == "__main__":
    unittest.main()
# AI: end
