"""Compile real firmware callback methods against a minimal host fixture (no radio)."""
# AI: below section was generated by an AI
import pathlib
import re
import shutil
import subprocess
import tempfile
import unittest


METHODS = ("acceptConnection", "onConnect", "onDisconnect", "onAuthenticationComplete",
           "onWrite", "onSubscribe", "onStatus")


def production_method(source, name):
    """Keep actual callback code, excluding surrounding Arduino/FreeRTOS dependencies."""
    start = re.search(r"^(?:bool|void) BleApiBridgeUsermod::" + re.escape(name) + r"\([^\n]*\) \{",
                      source, re.MULTILINE)
    if start is None:
        raise AssertionError(f"Production callback {name} needs a host adapter update")
    # Ignore braces in C++ comments/quoted literals while locating the method's closing brace.
    tokens = re.compile(r'//[^\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|[{}]')
    depth = 1
    for token in tokens.finditer(source, start.end()):
        if token.group() == "{":
            depth += 1
        elif token.group() == "}":
            depth -= 1
            if depth == 0:
                return source[start.start():token.end()]
    raise AssertionError(f"Production callback {name} is incomplete")


@unittest.skipUnless(shutil.which("clang++"), "Native admission regression requires clang++")
class AdmissionTests(unittest.TestCase):
    def compile_and_run(self, source):
        directory = pathlib.Path(__file__).resolve().parent
        methods = "\n\n".join(production_method(source, name) for name in METHODS)
        with tempfile.TemporaryDirectory(prefix="wled-admission-") as temporary:
            temporary = pathlib.Path(temporary)
            (temporary / "admission_callbacks.inc").write_text("namespace ble_api_bridge {\n" + methods + "\n}\n")
            binary = temporary / "admission-test"
            command = [shutil.which("clang++"), "-std=c++17", "-Wall", "-Wextra", "-Werror",
                       "-fsanitize=address,undefined", "-fno-omit-frame-pointer", "-I", str(temporary),
                       str(directory / "admission_test.cpp"), "-o", str(binary)]
            built = subprocess.run(command, capture_output=True, text=True, timeout=45)
            self.assertEqual(built.returncode, 0, built.stderr)
            return subprocess.run([str(binary)], capture_output=True, text=True, timeout=15)

    def test_real_callbacks_keep_security_and_subscription_events_before_delayed_connect(self):
        directory = pathlib.Path(__file__).resolve().parent
        source = (directory.parent / "ble_api_bridge_transport.cpp").read_text()
        ran = self.compile_and_run(source)
        self.assertEqual(ran.returncode, 0, ran.stdout + ran.stderr)
        self.assertIn("Passed 8 callback-order permutations", ran.stdout)

    def test_harness_rejects_the_original_connect_only_admission_behavior(self):
        directory = pathlib.Path(__file__).resolve().parent
        source = (directory.parent / "ble_api_bridge_transport.cpp").read_text()
        guard = "  if (!acceptConnection(info)) return;\n"
        self.assertEqual(source.count(guard), 3, "Update regression mutation for changed callback structure")
        # Negative control: simulate the original missing admission at auth/subscribe/write.
        # Compile success is mandatory; the executable must fail an observable ordering assertion.
        ran = self.compile_and_run(source.replace(guard, ""))
        self.assertNotEqual(ran.returncode, 0, "The fixture failed to detect CONNECT-only admission")
        self.assertIn("Assertion", ran.stderr)


if __name__ == "__main__":
    unittest.main()
# AI: end
