"""Exercise production callbacks and loop scheduling against host fakes, without a radio."""
# AI: below section was generated by an AI
import pathlib
import shutil
import subprocess
import tempfile
import unittest

from test_admission import METHODS, production_method


@unittest.skipUnless(shutil.which("clang++"), "Native LIVE readiness regression requires clang++")
class LiveReadinessTests(unittest.TestCase):
    def setUp(self):
        self.directory = pathlib.Path(__file__).resolve().parent
        self.core = (self.directory.parent / "ble_api_bridge_core.cpp").read_text()
        self.transport = (self.directory.parent / "ble_api_bridge_transport.cpp").read_text()

    def compile_and_run(self, core=None, transport=None):
        core = self.core if core is None else core
        transport = self.transport if transport is None else transport
        methods = [production_method(core, name) for name in ("loop", "clearRequestAssembly", "clearResponse")]
        names = METHODS + ("enqueue", "handleEvents", "resetConnection", "failConnection", "stopBle",
                           "refreshBleConfiguration", "processWriteChunk", "sendNextResponseChunk")
        methods.extend(production_method(transport, name) for name in names)
        with tempfile.TemporaryDirectory(prefix="wled-live-readiness-") as temporary:
            temporary = pathlib.Path(temporary)
            (temporary / "live_readiness_methods.inc").write_text(
                "namespace ble_api_bridge {\n" + "\n\n".join(methods) + "\n}\n")
            binary = temporary / "live-readiness-test"
            command = [shutil.which("clang++"), "-std=c++17", "-Wall", "-Wextra", "-Werror",
                       "-fsanitize=address,undefined", "-fno-omit-frame-pointer", "-I", str(temporary),
                       str(self.directory / "live_readiness_test.cpp"), "-o", str(binary)]
            built = subprocess.run(command, capture_output=True, text=True, timeout=45)
            self.assertEqual(built.returncode, 0, built.stderr)
            return subprocess.run([str(binary)], capture_output=True, text=True, timeout=15)

    def test_real_callbacks_and_loop_gate_live_until_authenticated_complete_application_rx(self):
        ran = self.compile_and_run()
        self.assertEqual(ran.returncode, 0, ran.stdout + ran.stderr)
        self.assertIn("Passed LIVE readiness", ran.stdout)

    def test_harness_rejects_original_live_before_application_rx(self):
        gate = "_livePushPending && _liveSessionReady && _secure"
        self.assertEqual(self.core.count(gate), 1, "Update regression mutation for changed loop structure")
        ran = self.compile_and_run(core=self.core.replace(gate, "_livePushPending && _secure"))
        self.assertNotEqual(ran.returncode, 0, "Fixture missed LIVE delivery before central readiness")
        self.assertIn("Assertion", ran.stderr)

    def test_harness_rejects_readiness_surviving_connection_reset(self):
        reset = "  _liveSessionReady = false;\n"
        self.assertEqual(self.transport.count(reset), 1, "Update regression mutation for changed reset structure")
        ran = self.compile_and_run(transport=self.transport.replace(reset, ""))
        self.assertNotEqual(ran.returncode, 0, "Fixture missed readiness leaking into a subsequent connection")
        self.assertIn("Assertion", ran.stderr)


if __name__ == "__main__":
    unittest.main()
# AI: end
