"""Harness safety/reporting tests; these deliberately do not certify BLE hardware."""
# AI: below section was generated by an AI
import copy
import json
import pathlib
import sys
import tempfile
import unittest
from unittest.mock import Mock

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import client_example as bridge
import hil_runner as hil


class FakeDevice:
    """A shared state backend allows independent identity and restoration assertions."""
    def __init__(self):
        self.state = {"on": False, "bri": 117,
                      "seg": [{"id": 0, "col": [[12, 34, 56, 78], [1, 2, 3, 4], [0, 0, 0, 0]]}]}
        self.info = {"mac": "aabbccddeeff", "ble": {"protocol": 1, "maxRequest": 4096},
                     "uptime": 100, "freeheap": 65000}
        self.posts = []
        self.connect_fails = False
        self.live = []
        self.subscribed = False

    def snapshot(self):
        return copy.deepcopy({"state": self.state, "info": self.info})

    def update(self, update):
        self.posts.append(copy.deepcopy(update))
        if "on" in update:
            self.state["on"] = update["on"]
        if "bri" in update:
            if update["bri"] == 0:
                self.state["on"] = False
            else:
                self.state["bri"] = update["bri"]
        for segment in update.get("seg", []):
            existing = next(s for s in self.state["seg"] if s["id"] == segment["id"])
            existing["col"][:len(segment["col"])] = copy.deepcopy(segment["col"])
        if self.subscribed:
            self.live.append(self.snapshot())


class FakeClient:
    """Only the public runner contract is emulated; protocol correctness has separate tests."""
    def __init__(self, device, **kwargs):
        self.device = device
        self.timeout = kwargs["timeout"]
        self.write_budget = kwargs["chunk_size"]
        self.client = self
        self.is_connected = False

    async def connect(self):
        if self.device.connect_fails:
            raise ConnectionError("sensitive payload must not be printed")
        self.is_connected = True

    async def disconnect(self):
        self.is_connected = False

    async def request(self, method, path, body=""):
        if not self.is_connected:
            raise ConnectionError("Disconnected")
        method = method.upper()
        path = path.split("?")[0].rstrip("/")
        status = 200
        value = {}
        if method == "GET":
            if path in ("/json", "/json/si"):
                value = self.device.snapshot()
            elif path == "/json/state":
                value = self.device.state
            elif path == "/json/info":
                value = self.device.info
            elif path in ("/json/effects", "/json/fxdata"):
                value = ["test"]
            elif path == "/json/cfg":
                value = {"wifi": {"password": "DO-NOT-LOG"}, "pairing-code": "654321"}
            elif path != "/json/pins":
                status = 404
        elif method == "POST":
            if path not in ("/json", "/json/state"):
                status = 404
            else:
                try:
                    update = json.loads(body)
                    if not isinstance(update, dict):
                        raise ValueError()
                except ValueError:
                    status = 400
                else:
                    self.device.update(update)
                    value = self.device.snapshot() if update.get("v") else {"success": True}
        else:
            status = 405
        return bridge.BridgeResponse(status, "application/json", json.dumps(value))

    async def subscribe_live(self):
        self.device.subscribed = True
        self.device.live = [self.device.snapshot()]

    async def unsubscribe_live(self):
        self.device.subscribed = False

    async def next_live(self, timeout=None):
        if not self.device.live:
            raise TimeoutError()
        return self.device.live.pop(0)

    async def stop_notify(self, uuid):
        pass

    async def start_notify(self, uuid, callback):
        self.raw_callback = callback

    async def write_gatt_char(self, uuid, data, response=True):
        if getattr(self.device, "fault_reply", False):
            self.raw_callback(None, bytearray(b"unexpected TX"))
        self.is_connected = False


class FakeOracle:
    def __init__(self, device):
        self.device = device
        self.closed = False

    async def open(self):
        pass

    async def close(self):
        self.closed = True

    async def snapshot(self, update=None):
        if update is not None:
            self.device.update(update)
        return self.device.snapshot()


class RunnerTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.args = hil.parse_args(["--address", "test", "--output", self.directory.name])
        self.device = FakeDevice()

    def runner(self, oracle=None):
        return hil.HilRunner(self.args, client_factory=lambda _address, **kwargs: FakeClient(self.device, **kwargs),
                             oracle=oracle)

    async def test_smoke_restores_baseline_and_never_persists_configuration(self):
        before = copy.deepcopy(self.device.state)
        oracle = FakeOracle(self.device)
        runner = self.runner(oracle)
        self.assertEqual(await runner.run(), 0)
        self.assertEqual(self.device.state, before)
        self.assertTrue(oracle.closed)
        self.assertFalse(runner.client.is_connected)
        for path in pathlib.Path(self.directory.name).iterdir():
            text = path.read_text()
            self.assertNotIn("DO-NOT-LOG", text)
            self.assertNotIn("654321", text)
        result = json.loads((pathlib.Path(self.directory.name) / "results.json").read_text())
        self.assertEqual(result["outcome"], "passed_selected_coverage")
        self.assertTrue(result["coverage_limits"])
        self.assertEqual(len(result["health_samples"]), 2)
        self.assertEqual(next(r for r in result["records"] if r["name"] == "final_health")["status"], "pass")

    async def test_missing_oracle_is_incomplete_not_pass(self):
        runner = self.runner()
        self.assertEqual(await runner.run(), 2)
        self.assertEqual(next(r for r in runner.records if r["name"] == "independent_oracle")["status"], "skip")
        self.assertEqual(json.loads((pathlib.Path(self.directory.name) / "results.json").read_text())["outcome"], "incomplete")

    async def test_wrong_oracle_mac_blocks_all_state_writes(self):
        wrong = FakeDevice()
        wrong.info["mac"] = "112233445566"
        runner = self.runner(FakeOracle(wrong))
        self.assertEqual(await runner.run(), 1)
        self.assertEqual(self.device.posts, [])
        self.assertEqual(wrong.posts, [])
        self.assertIsNone(runner.baseline)

    async def test_setup_failure_still_creates_all_reports(self):
        self.device.connect_fails = True
        runner = self.runner()
        self.assertEqual(await runner.run(), 1)
        for filename in ("results.json", "junit.xml", "report.md", "cases.jsonl"):
            path = pathlib.Path(self.directory.name) / filename
            self.assertTrue(path.is_file())
            self.assertNotIn("sensitive payload", path.read_text())

    async def test_successful_recovery_preserves_original_failure(self):
        runner = self.runner()
        await runner.setup()

        async def broken():
            raise AssertionError("Deliberate observed defect")

        self.assertFalse(await runner.case("broken", broken))
        self.assertEqual(runner.records[-1]["status"], "fail")
        self.assertEqual(runner.records[-1]["recovery"], [{"attempt": 1, "status": "pass"}])
        self.assertEqual(runner.exit_code(), 1)
        await runner.disconnect()

    async def test_failed_recovery_stops_after_two_attempts(self):
        runner = self.runner()
        await runner.setup()
        self.device.connect_fails = True

        async def broken():
            raise TimeoutError()

        await runner.case("broken", broken)
        self.assertTrue(runner.aborted)
        self.assertEqual(len(runner.records[-1]["recovery"]), 2)

    async def test_uptime_rollback_is_failure(self):
        runner = self.runner()
        await runner.setup()
        self.device.info["uptime"] = 1
        with self.assertRaisesRegex(AssertionError, "unexpected restart"):
            await runner.sample()
        await runner.disconnect()

    async def test_restore_rejects_independent_readback_mismatch(self):
        oracle = FakeOracle(self.device)
        runner = self.runner(oracle)
        await runner.setup()
        await runner.post({"bri": 42})
        original_snapshot = oracle.snapshot

        async def wrong_readback(update=None):
            value = await original_snapshot(update)
            value["state"]["bri"] = 43
            return value

        oracle.snapshot = wrong_readback
        with self.assertRaisesRegex(AssertionError, "Independent oracle: baseline"):
            await runner.restore()
        await runner.disconnect()

    async def test_optional_heap_metrics_are_recorded_only_when_available(self):
        runner = self.runner()
        self.device.info.update(minfreeheap=5000, largestfreeblock=4000, minheap="not a metric")
        await runner.setup()
        sample = runner.samples[-1]
        self.assertEqual(sample["minfreeheap"], 5000)
        self.assertEqual(sample["largestfreeblock"], 4000)
        self.assertNotIn("minheap", sample)
        self.assertNotIn("maxallocheap", sample)
        await runner.disconnect()

    async def test_semantic_errors_do_not_mutate_state(self):
        runner = self.runner()
        await runner.setup()
        await runner.semantic_errors()
        self.assertEqual(self.device.posts, [])
        await runner.disconnect()

    async def test_chunk_matrix_records_actual_budget_and_exact_sizes(self):
        runner = self.runner()
        await runner.setup()
        tested = await runner.chunk_boundaries()
        self.assertEqual({row["chunk_cap"] for row in tested}, {3, 20, 65, 182, 244})
        self.assertIn(4096, {row["request_bytes"] for row in tested})
        self.assertTrue(all(row["actual_write_budget"] <= row["chunk_cap"] for row in tested))
        self.assertTrue(all(set(update) == {"v", "_hil"} for update in self.device.posts))
        await runner.disconnect()

    async def test_framing_fault_cannot_pass_from_client_induced_disconnect(self):
        runner = self.runner()
        await runner.setup()
        self.device.fault_reply = True
        with self.assertRaisesRegex(AssertionError, "returned TX data"):
            await runner.framing_fault([b"\x00\x00"], wait_seconds=0.01)
        await runner.disconnect()

    def test_serial_panic_causes_failure_without_persisting_raw_text(self):
        oracle = hil.SerialOracle("unused", 0.1)
        oracle.serial = Mock()
        oracle.serial.in_waiting = 50
        oracle.serial.read.return_value = b"Guru Meditation sensitive-content-that-must-not-be-recorded"
        oracle.serial.read_until.return_value = b'{"state":{},"info":{}}\n'
        with self.assertRaisesRegex(AssertionError, "Serial crash"):
            oracle._snapshot(None)
        self.assertEqual(oracle.events[0]["event"], "panic")
        self.assertNotIn("sensitive-content", json.dumps(oracle.events))

    def test_utf8_request_sizes_use_bytes_not_characters(self):
        for size in (64, 65, 182, 244, 255, 256, 4096):
            body = hil.padded_request_body(size)
            self.assertEqual(len(("POST /json/state\n\n" + body).encode("utf-8")), size)
            self.assertEqual(json.loads(body)["_hil"], "é🌈")

    def test_restore_payload_is_allowlisted(self):
        original = {**self.device.state, "psave": 4, "rb": True, "playlist": {"ps": [1, 2]}, "transition": 70}
        self.assertEqual(set(hil.restorable_state(original)), {"on", "bri", "seg", "tt"})

    def test_invalid_or_secret_bearing_http_urls_rejected(self):
        for url in ("file:///tmp/example", "http://user:pass@wled", "http://wled/json", "http://wled/?token=secret"):
            with self.assertRaises(ValueError):
                hil.HttpOracle(url, 1)

    def test_safe_connection_errors_keep_known_details_only(self):
        self.assertEqual(hil.safe_error(ConnectionError("WLED disconnected")), "ConnectionError: WLED disconnected")
        self.assertNotIn("SECRET", hil.safe_error(ConnectionError("WLED disconnected with payload SECRET")))

    def test_heap_summary_describes_warmup_and_final_plateau_without_verdict(self):
        values = [1000, 900, 800, 800, 800, 800, 800, 800]
        summary = hil.health_summary([{"at": index * 60, "uptime": index * 60, "freeheap": value}
                                      for index, value in enumerate(values)])
        metric = summary["heap_metrics"]["freeheap"]
        self.assertEqual(metric["net_change_bytes"], -200)
        self.assertEqual(metric["final_quarter"]["trend_bytes_per_minute"], 0)
        self.assertEqual(metric["final_quarter"]["range_bytes"], 0)
        self.assertEqual(set(summary["heap_metrics"]), {"freeheap"})
        self.assertNotIn("status", metric)
        self.assertNotIn("pass", metric)


if __name__ == "__main__":
    unittest.main()
# AI: end
