"""Fault injection for persistence-harness recovery; no Bluetooth client is constructed."""
# AI: below section was generated by an AI
import argparse
import asyncio
import base64
import contextlib
import copy
import hashlib
import io
import json
from pathlib import Path
import stat
import sys
import tempfile
import unittest
from unittest.mock import AsyncMock, patch
from urllib.parse import parse_qs

sys.path.insert(0, str(Path(__file__).parents[1]))
import parity_persistence_hil as hil
from client_example import BridgeResponse


class MemoryClient:
    """A stateful transport double with explicit applied-but-lost form replies."""

    def __init__(self):
        self.mac = "aabbccddeeff"
        self.is_connected = False
        self.max_request_bytes = 65535
        self.cfg = {"id": {"name": "Original fixture", "sui": True}, "hw": {"led": {"total": 30}}}
        self.state = {"on": True, "bri": 128, "transition": 7, "mainseg": 0, "lor": 0,
                      "udpn": {"send": False, "recv": True, "sgrp": 3, "rgrp": 5},
                      "pl": -1, "nl": {"on": False}, "seg": [{"id": 0, "start": 0, "stop": 30,
                      "on": True, "fx": 0, "bri": 255, "col": [[12, 34, 56]], "sel": True}]}
        self.files = {"/presets.json": b'{"0":{}, "5":{"n":"Keep exact spacing", "bri":98}}\n'}
        self.pin = ""
        self.authorized = True
        self.flags = {"NO": False, "OW": True, "AO": False, "SU": True}
        self.requests = []
        self.form_failures = set()
        self.reject_blank_pin = False
        self.before_form = None
        self.corrupt_reads = set()
        self.transfers = {}
        self.uptime_ms = 60000
        self.uptime_after_reset = 1000

    async def connect(self, **_):
        self.is_connected = True
        self.authorized = not self.pin

    async def disconnect(self):
        self.is_connected = False
        self.authorized = not self.pin
        self.transfers.clear()

    async def refresh_capabilities(self):
        return {"mac": self.mac, "ble": {"api": 2}, "live": False}

    @staticmethod
    def reply(value, status=200):
        return BridgeResponse(status, "application/json", json.dumps(value))

    async def request(self, method, path, body=""):
        self.requests.append((method, path, body))
        if path == "/ble/capabilities":
            return self.reply({"maxChunk": 64})
        if path == "/uptime":
            return BridgeResponse(200, "text/plain", str(self.uptime_ms))
        if path == "/ble/auth":
            if method == "POST":
                payload = json.loads(body)
                if payload.get("lock"):
                    self.authorized = not self.pin
                elif payload.get("pin") != self.pin:
                    return self.reply({"authorized": False}, 401)
                else:
                    self.authorized = True
            return self.reply({"authorized": self.authorized, "pinRequired": bool(self.pin)})
        if not self.authorized:
            return self.reply({"error": "locked"}, 401)
        if path == "/reset":
            await self.disconnect()
            self.uptime_ms = self.uptime_after_reset
            return self.reply({"success": True, "reboot": True})
        if path == "/json/cfg":
            return self.reply(self.cfg)
        if path == "/json/state":
            if method == "GET":
                return self.reply(self.state)
            payload = json.loads(body)
            self.state.update({key: value for key, value in payload.items() if key not in ("v", "tt", "udpn")})
            self.state["udpn"].update({key: value for key, value in payload.get("udpn", {}).items() if key != "nn"})
            return self.reply({"success": True, "saved": True})
        if path == "/settings/s.js?p=6":
            return BridgeResponse(200, "application/javascript", "".join(
                f"d.Sf.{field}.checked={int(enabled)};" for field, enabled in self.flags.items()))
        if path in ("/settings/ui", "/settings/sec"):
            fields = parse_qs(body, keep_blank_values=True)
            if self.before_form:
                self.before_form(path, fields)
            if path == "/settings/ui":
                self.cfg["id"].update(name=fields["DS"][0], sui="SU" in fields)
            else:
                if self.reject_blank_pin and fields["PIN"] == [""]:
                    return self.reply({"success": False}, 507)
                self.pin = fields["PIN"][0]
                self.authorized = not self.pin
                self.flags = {field: field in fields for field in self.flags}
            if path in self.form_failures:
                self.form_failures.remove(path)
                await self.disconnect()
                raise TimeoutError("Sensitive backend response must not appear in public reports")
            return self.reply({"success": True, "saved": True})
        if path == "/ble/fs":
            payload = json.loads(body)
            operation = payload["op"]
            destination = payload.get("path")
            if operation == "read":
                if destination not in self.files:
                    return self.reply({"error": "missing"}, 404)
                data = self.files[destination]
                offset = payload["offset"]
                end = min(len(data), offset + payload["length"])
                revision = hashlib.sha256(data).hexdigest()
                if destination in self.corrupt_reads:
                    self.corrupt_reads.remove(destination)
                    revision = "0" * 64
                return self.reply({"size": len(data), "offset": offset, "next": end, "eof": end == len(data),
                                   "revision": revision, "data": base64.b64encode(data[offset:end]).decode()})
            if operation == "delete":
                existed = self.files.pop(destination, None) is not None
                return self.reply({"success": existed}, 200 if existed else 404)
            if operation == "begin":
                identifier = "12345678"
                self.transfers[identifier] = {"path": destination, "bytes": bytearray()}
                return self.reply({"id": identifier, "maxChunk": 64})
            transfer = self.transfers.get(payload["id"])
            if transfer is None:
                return self.reply({"error": "stale transfer"}, 409)
            if operation == "write":
                transfer["bytes"].extend(base64.b64decode(payload["data"], validate=True))
                return self.reply({"id": payload["id"], "next": len(transfer["bytes"])})
            if operation == "commit":
                data = bytes(transfer["bytes"])
                self.files[transfer["path"]] = data
                del self.transfers[payload["id"]]
                return self.reply({"success": True, "saved": True, "size": len(data),
                                   "sha256": hashlib.sha256(data).hexdigest()})
            if operation == "abort":
                del self.transfers[payload["id"]]
                return self.reply({"success": True})
        raise AssertionError(f"Unexpected fake request: {method} {path}")


class PersistenceSafetyTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.client = MemoryClient()
        args = argparse.Namespace(address="test-only", expected_mac=self.client.mac,
                                  output=Path(self.directory.name) / "run", chunk_size=64, timeout=1,
                                  connect_timeout=1, commission=False, settings_pin_env=None,
                                  pair=False, allow_reboot=False, exercise_pin=True,
                                  case_timeout=5, run_timeout=10, cleanup_timeout=5)
        # Patch before construction: even a mistaken production constructor would
        # fail this expectation rather than initialize Core Bluetooth.
        with patch.object(hil, "BleApiBridgeClient", return_value=self.client) as constructor:
            self.harness = hil.PersistenceHil(args)
            constructor.assert_called_once()
        self.baseline_cfg = copy.deepcopy(self.client.cfg)
        self.baseline_presets = self.client.files["/presets.json"]

    def skip_cases_before_pin(self):
        for name in ("presets_case", "ui_case", "disconnect_case"):
            setattr(self.harness, name, AsyncMock())

    async def execute(self):
        with contextlib.redirect_stdout(io.StringIO()), patch.object(hil.asyncio, "sleep", new=AsyncMock()):
            return await self.harness.execute()

    async def test_wrong_device_identity_prevents_all_writes(self):
        self.client.mac = "001122334455"
        self.assertEqual(await self.execute(), 1)
        self.assertEqual(self.client.requests, [])
        self.assertEqual(self.harness.report["cleanup"], "not_needed")
        self.assertFalse(self.harness.report["hardware_validated"])

    async def test_baselines_and_recovery_journal_are_private_and_exact(self):
        await self.harness.setup()
        for directory in (self.harness.output, self.harness.private):
            self.assertEqual(stat.S_IMODE(directory.stat().st_mode), 0o700)
        for file in self.harness.output.rglob("*"):
            if file.is_file():
                self.assertEqual(stat.S_IMODE(file.stat().st_mode), 0o600)
        self.assertEqual((self.harness.private / "presets.json").read_bytes(), self.baseline_presets)
        self.assertEqual(json.loads((self.harness.private / "configuration.json").read_text()), self.baseline_cfg)
        journal = json.loads((self.harness.private / "recovery.json").read_text())
        self.assertEqual(journal["phase"], "backed_up")
        self.assertEqual(journal["original_presets_sha256"], hashlib.sha256(self.baseline_presets).hexdigest())
        self.assertEqual([entry for entry in self.client.requests if entry[0] == "POST" and entry[1] != "/ble/fs"], [])

    async def test_unknown_existing_pin_is_not_replaced(self):
        self.client.pin = "2468"
        self.client.authorized = False
        self.assertEqual(await self.execute(), 2)
        self.assertEqual(self.client.pin, "2468")
        self.assertFalse(any(method == "POST" for method, _, _ in self.client.requests))

    async def test_lost_ui_form_reply_restores_complete_configuration(self):
        self.harness.presets_case = AsyncMock()
        self.client.form_failures.add("/settings/ui")
        self.assertEqual(await self.execute(), 1)
        self.assertEqual(self.client.cfg, self.baseline_cfg)
        self.assertEqual(self.client.files["/presets.json"], self.baseline_presets)
        self.assertEqual(self.harness.report["cleanup"], "restored_and_verified")
        self.assertFalse(self.harness.report["recovery_needed"])

    async def test_lost_pin_reply_uses_journaled_pin_and_restores_blank(self):
        self.skip_cases_before_pin()
        self.client.form_failures.add("/settings/sec")

        def check_journal_before_apply(path, fields):
            if path == "/settings/sec" and fields["PIN"] != [""]:
                journal = json.loads((self.harness.private / "recovery.json").read_text())
                self.assertTrue(journal["pin_may_have_changed"])
                self.assertEqual(journal["temporary_pin"], fields["PIN"][0])
                self.assertEqual(journal["original_pin"], "")

        self.client.before_form = check_journal_before_apply
        self.assertEqual(await self.execute(), 1)
        self.assertEqual(self.client.pin, "")
        self.assertEqual(self.client.cfg, self.baseline_cfg)
        self.assertEqual(self.harness.report["cleanup"], "restored_and_verified")
        self.assertFalse(self.harness.report["recovery_needed"])
        public = (self.harness.output / "results.json").read_text()
        self.assertNotIn(self.harness.test_pin, public)
        self.assertNotIn("Sensitive backend", public)
        self.assertFalse(self.harness.report["hardware_validated"])

    async def test_failed_pin_removal_retains_recovery_credential(self):
        self.skip_cases_before_pin()
        self.client.form_failures.add("/settings/sec")
        self.client.reject_blank_pin = True
        self.assertEqual(await self.execute(), 1)
        journal = json.loads((self.harness.private / "recovery.json").read_text())
        self.assertEqual(self.client.pin, journal["temporary_pin"])
        self.assertTrue(journal["pin_may_have_changed"])
        self.assertTrue(self.harness.report["recovery_needed"])
        self.assertEqual(self.harness.report["cleanup"], "failed")
        self.assertFalse(self.harness.report["hardware_validated"])

    async def test_corrupt_current_presets_do_not_prevent_known_backup_restore(self):
        await self.harness.setup()
        self.harness.library_dirty = True
        self.client.files["/presets.json"] = b'{"damaged":"temporary contents"}'
        self.client.corrupt_reads.add("/presets.json")
        await self.harness.cleanup()
        self.assertEqual(self.client.files["/presets.json"], self.baseline_presets)
        self.assertFalse(self.harness.library_dirty)

    async def test_failed_disconnected_transfer_destination_is_removed(self):
        await self.harness.setup()
        self.harness.temporary_file_dirty = True
        self.client.files[self.harness.temporary_path] = b"incorrectly committed by failing firmware"
        self.client.corrupt_reads.add(self.harness.temporary_path)
        await self.harness.cleanup()
        self.assertNotIn(self.harness.temporary_path, self.client.files)
        self.assertFalse(self.harness.temporary_file_dirty)
        self.assertEqual(self.harness.report["cleanup"], "restored_and_verified")

    async def test_runtime_udp_override_is_restored_after_drift(self):
        await self.harness.setup()
        baseline = copy.deepcopy(self.client.state["udpn"])
        self.harness.runtime_dirty = True
        self.client.state["udpn"] = {"send": True, "recv": True, "sgrp": 1, "rgrp": 1}
        await self.harness.cleanup()
        self.assertEqual(self.client.state["udpn"], baseline)
        self.assertFalse(self.harness.runtime_dirty)

    async def test_link_loss_without_uptime_reset_cannot_certify_reboot(self):
        await self.harness.setup()
        self.harness.args.allow_reboot = True
        self.client.uptime_after_reset = self.client.uptime_ms + 1
        with patch.object(hil.asyncio, "sleep", new=AsyncMock()):
            with self.assertRaisesRegex(hil.HarnessError, "without verified device uptime reset"):
                await self.harness.reboot()
        self.assertEqual(self.harness.report.get("reboots", []), [])
        self.assertTrue(self.harness.runtime_dirty)

    async def test_verified_uptime_reset_records_evidence(self):
        await self.harness.setup()
        self.harness.args.allow_reboot = True
        with patch.object(hil.asyncio, "sleep", new=AsyncMock()):
            await self.harness.reboot()
        self.assertEqual(len(self.harness.report["reboots"]), 1)
        self.assertEqual(self.harness.report["reboots"][0]["before_ms"], 60000)
        self.assertEqual(self.harness.report["reboots"][0]["after_ms"], 1000)

    async def test_repeated_cancellation_does_not_cancel_recovery(self):
        started, restoring, release = asyncio.Event(), asyncio.Event(), asyncio.Event()
        original_cleanup = self.harness.cleanup

        async def pending_mutation():
            self.harness.runtime_dirty = True
            self.client.state["bri"] = 5
            self.harness.write_journal()
            started.set()
            await asyncio.Event().wait()

        async def blocked_cleanup():
            restoring.set()
            await release.wait()
            await original_cleanup()

        self.harness.presets_case = pending_mutation
        self.harness.cleanup = blocked_cleanup
        with contextlib.redirect_stdout(io.StringIO()):
            running = asyncio.create_task(self.harness.execute())
            await asyncio.wait_for(started.wait(), 1)
            running.cancel()
            await asyncio.wait_for(restoring.wait(), 1)
            running.cancel()
            await asyncio.sleep(0)
            self.assertFalse(running.done())
            release.set()
            self.assertEqual(await asyncio.wait_for(running, 2), 130)
        self.assertEqual(self.client.state["bri"], 128)
        self.assertEqual(self.harness.report["cleanup"], "restored_and_verified")
        self.assertFalse(self.harness.report["recovery_needed"])
        self.assertFalse(self.harness.report["hardware_validated"])


if __name__ == "__main__":
    unittest.main()
# AI: end
